/**
 * GINI'S TRUTH LAYER — the router, and the light half of what he knows.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * THE ONE RULE, AND IT IS STRUCTURAL, NOT ASPIRATIONAL:
 *
 *   Gini may only ever say sentences that are ALREADY WRITTEN AND STORED in
 *   this repository. He retrieves; he never composes. There is no model call
 *   in this file and there must never be one.
 *
 * Why it is built this way. Iron Rule 1 says never publish a guessed answer —
 * wrong answers harm student pilots. A language model asked to "explain this
 * question" will produce fluent, confident, occasionally wrong aviation
 * teaching, and it would be doing so in the mascot's voice, on the site that
 * publishes /how-answers-are-verified. The only defence that actually holds is
 * to make invention impossible rather than unlikely: every string Gini speaks
 * comes out of a data file a human wrote.
 *
 * When there is nothing verified to say, he says so. That refusal is a feature.
 * It is also honest in a way no competitor in this market is.
 * ────────────────────────────────────────────────────────────────────────────
 *
 * HOW HE IS PUT TOGETHER (2026-08-20 rebuild):
 *
 *   types.ts      the reply shape and the refusal sentences
 *   match.ts      how a typed sentence is matched to a stored one
 *   context.ts    which page the student is standing on
 *   persona.ts    greetings, small talk, study wisdom      (light)
 *   marketing.ts  what the Captain offers, and when to say so  (light)
 *   knowledge.ts  THIS FILE — FAQ, structure, and the router (light)
 *   deep.ts       the 4,400-question bank             (LAZY — see below)
 *
 * "Light" means it ships with the page. deep.ts does not: it is pulled in with
 * a dynamic import the first time a student asks something the light layer
 * cannot answer, because Gini renders on every route and the bank is megabytes.
 * Use ask() when you need a synchronous answer, askDeep() when you can await.
 *
 * Corpus figures come from lib/gini/generated/corpus-stats.ts, regenerated by
 * `npx tsx tools/gini/build-corpus-stats.mts` and drift-checked by
 * `npx tsx tools/audit/gini-selftest.mts`.
 */

import { FAQS, type FaqEntry } from "@/lib/faq";
import { keyFactsFor } from "@/lib/chapter-key-facts";
import { verificationFor, LEVEL_LABEL } from "@/lib/verification-status";
import { CPL_SUBJECTS, type Subject } from "@/lib/subjects";
import { LIVE_CLASS_SUBJECTS } from "@/lib/live-classes";

import { answer, refuse, REFUSALS, type GiniReply, type GiniSource, type RefusalReason } from "./types";
import { Index, mentions } from "./match";
import { readContext, type GiniContext } from "./context";
import { smallTalk, wisdomFor } from "./persona";
import { offerFor } from "./marketing";
import { CORPUS, corpusFor } from "./generated/corpus-stats";

export type { GiniReply, GiniSource, RefusalReason };
export { REFUSALS };
export { readContext, type GiniContext } from "./context";
export { PITCHES, choosePitch, offerFor, PITCH_RULES, type Pitch, type PitchState } from "./marketing";
export { greeting, smallTalk, HELP_TEXT, WISDOM, partOfDay, suggestionsFor, type Spoken } from "./persona";

/* ──────────────────────────── site questions ──────────────────────────── */

/**
 * The FAQ is the canonical published answer to the questions students actually
 * type, so it is tried before everything except manners. Matching is a ranked
 * lookup over stored entries, never a search over prose that could be stitched
 * into a new sentence.
 *
 * The floor is deliberately high. A single incidental shared word is not a
 * match, and answering on one is how an assistant confidently answers the
 * question the student did not ask.
 */
const FAQ_INDEX = new Index<FaqEntry>(
  FAQS.map(f => ({ item: f, title: f.q, body: f.a })),
);

/**
 * MEASURED, NOT GUESSED. At 0.5 the question "how should I study for the exam"
 * scored 0.53 against "Why is the DGCA Navigation paper so large?" — an entry
 * that shares the word "paper" and mentions studying in its answer. It would
 * have replied with a true fact about the Navigation syllabus to a student
 * asking how to revise. The probe table in tools/audit/gini-selftest.mts is
 * what this number is tuned against; change it and re-run that.
 */
const FAQ_FLOOR = 0.6;

export function answerFromFaq(query: string): GiniReply {
  // bestByTitle, not best: an entry that only mentions the topic in its answer
  // text is about something else, however many words it happens to share.
  const hit = FAQ_INDEX.bestByTitle(query, FAQ_FLOOR);
  if (!hit) return refuse("not-verified");
  return answer(hit.item.a, { type: "faq", question: hit.item.q }, hit.item.href);
}

/* ────────────────────────── chapters & structure ────────────────────────── */

/** The verified one-liners for a chapter, if any exist. Never padded. */
export function chapterFacts(subjectId: string, chapterId: string): GiniReply {
  const facts = keyFactsFor(subjectId, chapterId);
  if (!facts || !facts.facts?.length) return refuse("not-verified");
  return answer(
    facts.facts.map(f => f.fact).join(" "),
    { type: "key-fact", subjectId, chapterId },
  );
}

/**
 * Structural facts — derived from the data, so they cannot go stale, except for
 * the two counts, which come from the generated corpus file precisely so that
 * putting Gini on every page does not put the question bank on every page.
 */
export function describeSubject(subjectId: string): GiniReply {
  const s = CPL_SUBJECTS.find(x => x.id === subjectId);
  if (!s) return refuse("out-of-scope");

  const v = verificationFor(subjectId);
  const status = v ? ` Its answers are currently ${LEVEL_LABEL[v.level].toLowerCase()}.` : "";
  const counts = corpusFor(subjectId);
  const bank = counts
    ? ` and ${counts.total} practice questions. I can explain ${counts.speakable} of them in full.`
    : ".";
  const live = LIVE_CLASS_SUBJECTS[subjectId]
    ? " The Captain also teaches this one live."
    : "";

  return answer(
    `${s.name} has ${s.chapters.length} chapters${bank}${status}${live}`,
    { type: "structure" },
    `/cpl/${s.id}`,
  );
}

/** Which subject is the student talking about, if any? */
const SUBJECT_INDEX = new Index<Subject>(
  CPL_SUBJECTS.map(s => ({ item: s, title: `${s.name} ${s.shortName} ${s.id.replace(/-/g, " ")}` })),
);

/** Where something lives on the site. Pure structure, always true. */
type ChapterRef = { href: string; label: string };

const CHAPTER_INDEX = new Index<ChapterRef>(
  CPL_SUBJECTS.flatMap(s =>
    s.chapters.map(c => ({
      item: {
        href: `/cpl/${s.id}/${c.id}/notes`,
        label: `${s.name} — Chapter ${c.number}: ${c.title}`,
      },
      title: c.title,
      body: `${s.name} ${c.description ?? ""}`,
    })),
  ),
);

/**
 * A LOWER FLOOR THAN ANYWHERE ELSE, DELIBERATELY, and the reason is what a
 * wrong answer costs here. Everywhere else a mediocre match means Gini states
 * a fact about the wrong topic. Here it means he points at a chapter that is
 * not quite the one you wanted — a link, one click, obviously right or wrong on
 * arrival. The floors are set by consequence, not by taste.
 *
 * It matters because chapter titles are two or three words, so one filler word
 * in the query ("how does a VOR *work*") halves the coverage score. At 0.5,
 * "how does a VOR work" refused while the site had a whole chapter called VOR.
 * bestByTitle still requires the match to be in the chapter's own title, so he
 * cannot arrive here on a passing mention in a description.
 */
export function findChapter(query: string): GiniReply {
  const hit = CHAPTER_INDEX.bestByTitle(query, 0.42);
  if (!hit) return refuse("not-verified");
  return answer(`That's ${hit.item.label}.`, { type: "structure" }, hit.item.href);
}

/**
 * "How many questions are in Meteorology", "is Air Regs verified", "how many
 * chapters" — questions about the shape of the site rather than its content.
 */
/**
 * Is the student asking about THIS SITE's material, rather than about the DGCA?
 *
 * "How many questions are in Meteorology" is genuinely ambiguous — the paper
 * has 50, the bank here has hundreds — and both answers are true. The FAQ
 * carries the exam answer and the Captain confirmed it, so that reading wins
 * by default. Only an explicit site-scoped phrasing overrides it. Guessing
 * which one they meant, in either direction, is what this avoids.
 */
const SITE_SCOPED = /\b(on (this|the|your) site|in the bank|question bank|do you have|you have|here|available)\b/i;

function structureAnswer(query: string, ctx: GiniContext, siteScopedOnly = false): GiniReply | null {
  if (siteScopedOnly && !SITE_SCOPED.test(query)) return null;

  const asksAboutShape = mentions(query, "questions", "notes", "verify", "exam") ||
    /\b(how many|how much|what does .* (cover|include)|syllabus)\b/i.test(query);
  if (!asksAboutShape) return null;

  const subject = SUBJECT_INDEX.best(query, 0.5);
  if (subject) {
    const r = describeSubject(subject.item.id);
    if (r.kind === "answer") return r;
  }

  // "how many questions do you have" with no subject named — answer for the site.
  if (/\b(how many|how much)\b/i.test(query) && mentions(query, "questions")) {
    return answer(
      `${CORPUS.total} practice questions across the subjects, chapter by chapter and free. ` +
      `${CORPUS.speakable} of them carry a worked explanation I can read to you.`,
      { type: "structure" },
      "/question-bank",
    );
  }

  // Standing in a chapter and asking about "this" — read its verified key facts.
  if (ctx.subjectId && ctx.chapterId && /\b(this|here|current)\b/i.test(query)) {
    const facts = chapterFacts(ctx.subjectId, ctx.chapterId);
    if (facts.kind === "answer") return facts;
  }

  return null;
}

/* ────────────────────────────── the router ────────────────────────────── */

/**
 * THE SINGLE ENTRY POINT, light half.
 *
 * Order is a safety property, not a preference:
 *   1. MANNERS first. "hi" is not a request for exam content, and answering it
 *      with "I have no verified answer" is how an assistant reads as broken.
 *   2. The FAQ, because it is the canonical published answer.
 *   3. Study wisdom, only when the student clearly asked for advice.
 *   4. What the Captain offers — his classes, groups and channels. These are
 *      his own facts, not retrieved teaching.
 *   5. Structure — counts, verification status, which chapter covers what.
 *   6. Otherwise refuse. Never a generated sentence.
 */
export function ask(query: string, ctx: GiniContext = readContext("/")): GiniReply {
  const q = query.trim();
  if (!q) return refuse("out-of-scope");

  const manners = smallTalk(q, ctx);
  if (manners) return manners;

  // Only an explicitly site-scoped question jumps ahead of the FAQ — see
  // SITE_SCOPED above for why the ambiguous phrasings deliberately do not.
  const scoped = structureAnswer(q, ctx, true);
  if (scoped) return scoped;

  const faq = answerFromFaq(q);
  if (faq.kind === "answer") return faq;

  const wise = wisdomFor(q);
  if (wise) return wise;

  const offer = offerFor(q, ctx);
  if (offer) return offer;

  const structure = structureAnswer(q, ctx);
  if (structure) return structure;

  if (/\b(where|find|which chapter|show me|take me|locate)\b/i.test(q)) {
    const found = findChapter(q);
    if (found.kind === "answer") return found;
  }

  return refuse("not-verified");
}

/**
 * THE FULL ANSWER, including the question bank.
 *
 * Tries the light layer first — it is instant and covers manners, the FAQ, the
 * offers and the structure. Only if that comes up empty does it pull in
 * deep.ts, which is where the megabytes live. Most visitors never trigger it;
 * nobody triggers it before they have typed something.
 *
 * A failed dynamic import must never turn into a guess: on any failure the
 * honest refusal from the light layer is what the student gets.
 */
export async function askDeep(query: string, ctx: GiniContext = readContext("/")): Promise<GiniReply> {
  const light = ask(query, ctx);
  if (light.kind === "answer") return light;
  if (light.reason === "out-of-scope") return light;

  let deep: typeof import("./deep") | null = null;
  try {
    deep = await import("./deep");
  } catch {
    // Offline, or the chunk failed to load. A failed lookup must never become
    // a guess, so everything below is simply skipped.
  }

  if (deep) {
    // A confident, multi-concept match on a question the student more or less
    // asked. This is the good case and it goes first.
    const fromBank = deep.answerFromBank(query, ctx.subjectId);
    if (fromBank.kind === "answer") return fromBank;

    // The bank knows this question but has no explanation written for it. That
    // is a more useful thing to be told than "not verified", so it wins.
    if (fromBank.reason === "no-explanation" || fromBank.reason === "needs-figure") return fromBank;
  }

  // "What is drift" is a request for a definition, and the bank is full of
  // applied problems that merely contain the word. Where the site teaches the
  // topic, the chapter is the better answer than a tangential question.
  const found = findChapter(query);
  if (found.kind === "answer") {
    return answer(
      found.text.replace(/^That's /, "That's taught in "),
      { type: "structure" },
      found.href,
    );
  }

  // Last resort: a single-concept match, still verified and still labelled with
  // the question it came from, so the student can see what he matched.
  if (deep) {
    const solo = deep.answerFromBank(query, ctx.subjectId, true);
    if (solo.kind === "answer") return solo;
  }

  return light;
}
