# (chapter, CAE figure, heading regex, caption, alt text)
# Alt texts were written looking at each cropped image (see MET_NOTES_AUDIT).
P = [
 ("met-01","1.1",r"Thermal Structure","Mean tropopause height and temperature by latitude band, January and July","Fan diagram of tropopause heights by latitude in January and July: about 54,000 to 57,000 ft over the tropics, falling to 31,000-37,000 ft over the polar regions."),
 ("met-02","2.1",r"Pressure as Weight","Pressure is the weight of the column of air above","A column of air of unit cross-section, with the total weight of the atmosphere above marked at the bottom of the column."),
 ("met-02","2.2",r"Measurement Instruments","The mercury barometer","Mercury barometer: a tube with a vacuum at the top standing in a dish of mercury, atmospheric pressure acting on the open surface, with a scale beside the column."),
 ("met-02","2.3",r"Measurement Instruments","The aneroid barometer","Aneroid barometer: stacked evacuated capsules linked by levers to a pointer moving over a scale."),
 ("met-02","2.5",r"Measurement Instruments","The barograph","Barograph: the capsule and lever system drives a pen over a rotating chart drum, producing a time-pressure trace."),
 ("met-02","3.2",r"Vertical Variation","Pressure falls faster with height in cold air","A cold column and a warm column on the same sea-level pressure: the pressure levels sit lower over the cold air and higher over the warm air."),
 ("met-02","2.7",r"Pressure Settings","Airfield pressure and mean sea level pressure","An aerodrome on a headland with the QFE of 980 hPa at the airfield and the sea-level pressure of 1000 hPa below."),
 ("met-02","2.10",r"Pressure Patterns","Isobars on an analysis chart","Surface analysis chart with isobars labelled in hPa and a low pressure centre in the top right."),
 ("met-02","9.8",r"Altimetry","Altitude, height, elevation and flight level","Aircraft above sloping ground: altitude above mean sea level, flight level above the standard pressure setting 1013 hPa, and elevation and height above an aerodrome."),
 ("met-02","9.9",r"Under-Reading","Altimeter error when the true pressure differs from the setting","Altimeter showing 4000 ft with 1010 hPa set while the true sea-level pressure is 1005 hPa, so the true height is 3865 ft."),
 ("met-03","5.1",r"Instruments","The Stevenson screen","Stevenson screen: a louvred white box on legs, with the thermometers 4 ft above the ground."),
 ("met-03","5.2",r"Instruments","The thermograph","Thermograph: a clockwork drum carrying a chart and a pen arm that records temperature."),
 ("met-03","5.4",r"Instruments","Electrical thermometer","Digital electrical thermometer with a display reading 25.6 degrees Celsius."),
 ("met-03","5.5",r"Insolation","Insolation and reflection","Sun's rays reaching the ground as insolation, with part of the radiation reflected by cloud and by water or snow."),
 ("met-03","5.10",r"Methods of Heat Transfer","Heat processes in the atmosphere","Diagram of incoming solar radiation, absorption, reflection, terrestrial radiation, conduction, convection and latent heat exchange between Earth and atmosphere."),
 ("met-03","5.11",r"Definition|Temperature Scales","Temperature falls with height","Graph of height against temperature with a straight line sloping to lower temperature at greater height."),
 ("met-03","5.12",r"Heat and Temperature|Terrestrial Radiation","Inversions","Temperature-height profile showing a surface inversion on a clear night, an isothermal layer and an inversion above the tropopause."),
 ("met-03","5.13",r"Insolation","Effect of latitude on heating","Sun's rays striking high latitudes obliquely over a large area and low latitudes more directly over a small area."),
 ("met-03","5.15",r"Diurnal Variation","Diurnal variation of temperature","Temperature over 24 hours: large daily swing in clear calm conditions, smaller with cloud or strong wind, and smallest over the sea."),
 ("met-03","5.16",r"Effect of Clouds","Cloud cover by day","Cloud reflecting part of the sun's rays so that the maximum air temperature near the surface is reduced."),
 ("met-03","5.20",r"Diurnal Variation","Why the sea has a small diurnal range","Sunlight penetrating into the sea and heat mixed down through an absorption layer, so the surface warms little."),
 ("met-04","3.1",r"Latitudinal Variation","Density by latitude","Cross-section of the atmosphere from pole to equator: higher density near the pole at low level and a tropopause of 26,000 ft at the pole against 56,000 ft at the equator."),
 ("met-04","3.2",r"Factors Affecting Air Density","Pressure decrease with height in cold and warm air","Cold and warm air columns on the same ground pressure; pressure surfaces are lower over the cold column."),
 ("met-05","6.1",r"Three Phases","Change of state and latent heat","Solid, liquid and gas with arrows showing latent heat absorbed when changing towards gas and released when changing back."),
 ("met-05","6.2",r"Key Humidity Terms","Water vapour the air can hold at saturation","Graph of grams of water vapour per cubic metre of saturated air against temperature, rising steeply from 0 to +30 degrees Celsius."),
 ("met-05","6.4",r"Temperature Parameters","Wet and dry bulb hygrometer","Dry and wet bulb thermometers side by side, the wet bulb wrapped in a cotton wick dipping into a distilled water container."),
 ("met-05","6.5",r"Relative Humidity","Diurnal variation of relative humidity","Relative humidity and temperature over 24 hours: relative humidity is highest near dawn and lowest in the afternoon."),
 ("met-06","4.1",r"Forces Acting|Types of Calculated","A depression on a surface chart","Surface analysis chart over north-west Europe with a low at the centre, closed isobars labelled in hPa and station plots around it."),
 ("met-06","4.4",r"Types of Calculated","An anticyclone on a surface chart","Surface analysis chart over north-west Europe with a high at the centre, isobars labelled in hPa, fronts on its edge and station plots."),
 ("met-06","10.1",r"Wind Measurement","Wind direction and aircraft heading","Aircraft heading 090 with a wind from 090: the wind is a headwind."),
 ("met-06","10.3",r"Backing & Veering","Veering and backing","Wind veering from 090 to 190 degrees (clockwise) and backing from 340 to 240 degrees (anticlockwise)."),
 ("met-06","10.7",r"Coriolis","Coriolis deflection","Air deflected to the right in the northern hemisphere and to the left in the southern hemisphere, with the reason shown for the lag in speed of the Earth's surface."),
 ("met-06","10.10",r"Types of Calculated","Geostrophic wind","Pressure gradient force and Coriolis force balancing as the wind turns until it blows along the isobars."),
 ("met-06","10.12",r"Types of Calculated","Gradient wind around a low","Forces on air curving round a low: pressure gradient force, Coriolis force and centrifugal force marked along the radius, with the wind velocity V at right angles."),
 ("met-06","10.13",r"Types of Calculated","Gradient wind around a high","Forces on air curving round a high: pressure gradient force, Coriolis force and centrifugal force marked along the radius, with the wind velocity V at right angles."),
 ("met-06","10.14",r"Surface Friction","Surface wind crosses the isobars","Pressure gradient, Coriolis force and surface wind between a low and a high, the wind turned across the isobars towards low pressure."),
 ("met-06","10.15",r"Surface Friction","Friction over land","Geostrophic wind 250/30 kt and the surface wind over land 220/15 kt, backed by 30 degrees."),
 ("met-06","10.16",r"Surface Friction","Friction over sea","Geostrophic wind 250/30 kt and the surface wind over sea 240/20 kt, backed by 10 degrees."),
 ("met-06","10.17",r"Surface Friction","Surface wind by day and night","By day, mixing brings fast air down and veers the surface wind; at night, with no mixing, the surface wind is lighter and backs."),
 ("met-07","15.1",r"Types of Fog","Radiation fog","Terrestrial radiation cooling the ground at night and the air conductively cooled to dew point under an inversion."),
 ("met-07","15.2",r"Types of Fog","Hill fog","Cloud covering the hills with clear air above and in the valleys."),
 ("met-07","15.3",r"Types of Fog","Advection fog","Wind up to 15 kt carrying moist air across a colder land or sea surface with air temperature 5 and dew point 3 degrees."),
 ("met-07","15.4",r"Types of Fog","Steaming fog","Very cold air over a warmer sea surface with evaporation rising from the sea."),
 ("met-07","15.7",r"Types of Fog","Frontal fog","Warm front with nimbostratus, precipitation falling into the cold air and a belt of fog up to 200 nm wide."),
 ("met-07","15.9",r"Definition of Visibility","Visibility from marker objects","Control tower with objects at 1 km, 5 km, 10 km and 20 km used to judge visibility."),
 ("met-07","15.10",r"Instruments","Runway visual range","Side and plan views of the observer position 15 ft above the ground and 76 m from the runway, with marker boards and lights along the runway."),
 ("met-07","15.11",r"Instruments","Transmissometer","A projector and a detector on either side of the runway measuring light transmitted over a baseline and displaying RVR."),
 ("met-07","15.12",r"Instruments","Instrumented RVR","Transmissometer pairs at the touchdown, midpoint and stop end of the runway."),
 ("met-08","12.1",r"Cloud Base","Cloud base by balloon","A pilot balloon released and timed until it enters the cloud base."),
 ("met-08","12.3",r"Cloud Base","Laser ceilometer","A laser ceilometer beside the runway measuring the cloud base."),
 ("met-08","12.5",r"Cloud Base","Stratiform cloud seen from an aircraft","A layer of stratiform cloud on the horizon seen from an aircraft, with the tailplane in view."),
 ("met-08","12.7",r"Clouds . Classification","Cloud classification by height","Cloud types by level (temperate-latitude heights): high clouds CS, CC, CI above 16,500 ft, medium clouds NS, AS, AC from 6,500 to 16,500 ft, low clouds ST, SC, CU, CB below 6,500 ft. In the tropics the levels are higher."),
 ("met-08","12.8",r"Low Clouds","Stratus","Two photographs of low grey stratus over a runway."),
 ("met-08","12.9",r"Low Clouds","Stratocumulus","Photograph of a continuous layer of stratocumulus with dark patches."),
 ("met-08","12.10",r"Low Clouds","Nimbostratus","Photograph of a thick, dark grey nimbostratus layer over open ground with a windsock in the foreground."),
 ("met-08","12.11",r"Vertical Development","Fair weather cumulus","Photograph of fair weather cumulus over flat country."),
 ("met-08","12.12",r"Vertical Development","Cumulonimbus","Photograph of a large cumulonimbus with an anvil top."),
 ("met-08","12.13",r"Medium Clouds","Altocumulus","Photograph of altocumulus in small rolls."),
 ("met-08","12.14",r"Medium Clouds","Altocumulus lenticularis and other altocumulus","Two photographs: a lenticular cloud over a ridge, and banded altocumulus."),
 ("met-08","12.16",r"Medium Clouds","Altostratus","Photograph of altostratus with the sun visible as a dull disc."),
 ("met-08","12.17",r"High Clouds","Cirrus","Photograph of white wispy cirrus filaments in a blue sky."),
 ("met-08","12.18",r"High Clouds","Cirrostratus","Photograph of a thin cirrostratus veil."),
 ("met-08","12.19",r"High Clouds","Cirrocumulus","Photograph of cirrocumulus: a field of small white grains in rows."),
 ("met-09","7.5",r"Inversion","Variable environmental lapse rate","Temperature-height profile with steps: sections of isothermal and inverted layers."),
 ("met-09","13.5",r"Stability and Instability|Lapse Rates","Environmental lapse rate, DALR and SALR","Rising parcel following the DALR to the dew point and the SALR above, compared with the environmental lapse rate (ELR)."),
 ("met-09","13.6",r"Stability Criteria","Condensation level and critical temperature","Heating the ground raises a rising parcel along the DALR until it reaches the dew point, forming cloud; the critical temperature is the surface temperature needed for cloud."),
 ("met-09","13.7",r"Tephigram","Finding cloud base and tops on a temperature-height diagram","ELR, DALR and SALR lines drawn on a diagram, with cloud base and tops found where they cross."),
 ("met-09","13.12",r"Inversion","Inversion limiting cloud top","Cloud base at the dew point and a cloud top stopped by an inversion in the ELR."),
 ("met-11","13.13",r"Theories of Precipitation","How a raindrop grows","Cloud droplets in an updraught colliding, growing to about 2 mm and falling as rain when too heavy for the updraught."),
 ("met-11","13.14",r"Rainy Day","Rainfall recorder","Cutaway of a tipping siphon rain gauge with its parts labelled A to H."),
 ("met-12","16.1",r"Types of Airframe Ice","Clear ice formation","Large supercooled water droplets running back over a wing leading edge and freezing as clear ice."),
 ("met-12","16.2",r"Types of Airframe Ice","Rime ice formation","Small supercooled water droplets freezing at once on the leading edge as rime ice."),
 ("met-12","16.3",r"Temperature Range","Freezing rain","A warm front with warm air above 0 C, rain falling through freezing air below and a freezing level near the ground."),
 ("met-12","16.4",r"Cloud Forms","Cumulonimbus and icing","A large cumulonimbus, in which supercooled water droplets are concentrated."),
 ("met-12","16.5",r"Effects","Thin wing sections collect ice faster","Airflow streamlines round a thin and a thick aerofoil section, the thinner one collecting ice more rapidly."),
 ("met-12","16.6",r"Temperature Range","Icing and the freezing level","Cumulonimbus with the freezing level, +20 C near the ground on one side and -20 C on the other."),
 ("met-12","14.12",r"Effects","Ice on a tailplane and underwing","Photographs of ice build-up on a tailplane and on the underside of a wing."),
 ("met-13","14.1",r"Life Cycle","Cumulus (building) stage","Updraughts throughout the cloud with turbulence around the cloud and inflow at the base."),
 ("met-13","14.2",r"Life Cycle","Mature stage","Updraught and downdraught side by side with lightning, a gust front at ground level and the upper wind."),
 ("met-13","14.4",r"Life Cycle","Gust front and roll cloud","Storm movement, downdraughts spreading as a gust front ahead of the storm, warm air inflow and a possible roll cloud."),
 ("met-13","14.5",r"Life Cycle","Dissipating stage","Downdraught through the whole cloud and an anvil drifting downwind of the storm."),
 ("met-13","14.6",r"Types of Thunderstorms","Squall line","Surface chart of a line of thunderstorms ahead of a cold front."),
 ("met-13","14.7",r"Types of Thunderstorms","Conditions for a supercell","Cold dry upper air at 400 hPa and warm moist low-level air at 850 hPa crossing at an angle over a low."),
 ("met-13","14.10",r"Aviation Hazards","Thunderstorm hazards","Cumulus, mature and dissipating stages showing updraughts, downdraughts, ice, snow, turbulence, rain and the gust front."),
 ("met-13","14.13",r"Aviation Hazards","Lightning","A photograph of a lightning strike and a radome damaged by a strike."),
 ("met-13","14.15",r"Air Pocket|Microburst","Microburst","Strong downdraught spreading outward at ground level: increasing headwind, then downdraught, then increasing tailwind along an approach."),
 ("met-13","19.19",r"Tornado","Wind shear and rotation","Horizontal rolls caused by wind shear tilted into vertical rotation."),
 ("met-13","19.23",r"Tornado","A tornado","Photograph of a tornado funnel reaching the ground beneath a dark cloud."),
 ("met-14","17.13",r"Western Disturbances|Fronts","Development of a frontal depression","Five stages of a frontal wave from a straight front to a closed low on a polar front, with divergence aloft."),
 ("met-14","17.19",r"Cold Front","Cold front speed","Chart with a cold front, a geostrophic interval and the distance 80 nm used to find the front's speed."),
 ("met-14","17.22",r"Warm Front","Warm sector section","Cross-section of a warm sector with tropical maritime air, a cold front on the left and a warm front on the right, stratus and cumulus."),
 ("met-14","18.2",r"Occluded Front","A warm occlusion","Occlusion with a point of occlusion, mTw warm air and mPc air on both sides, Cb, As, Ns and Cs cloud."),
 ("met-14","18.4",r"Occluded Front","A cold occlusion","Cold occlusion with colder air behind pushing under the cool air ahead."),
 ("met-14","18.6",r"Occluded Front","Back-bent occlusion on a weather map","Weather map with front symbols, warm front and cold front joining in an occlusion."),
 ("met-15","11.2",r"Definition","300 hPa chart with jet stream","Upper chart at 300 hPa with contours and jet axes marked in blue, with speeds in knots."),
 ("met-15","11.4",r"Definition","Dimensions of a jet stream","A flat tube of fast air: 1500 nm long, about 200 nm wide and about 2 nm deep, 60 kt minimum."),
 ("met-15","11.6",r"Types of Jet Streams","Sub-tropical jet streams","Warm air between cold columns on each side, the Hadley cell and the jet streams above the cold-warm boundaries."),
 ("met-15","11.8",r"Temperature Distribution","Jet streams cross-section","Cold air on either side of a warm column with the jet at the tropopause break, shown in cross-section and in plan view."),
 ("met-15","11.10",r"Cause|Clouds","Cloud pattern at a jet stream","Cirrus jet stream cloud lying along the warm-air side of the jet axis, behind a surface warm front."),
 ("met-15","11.12",r"Cause|Clouds","Jet streams on a significant weather chart","Significant weather chart marked with the sub-tropical jet, the tropical easterly jet and the polar front jet."),
 ("met-16","8.1",r"Causes","Thermal turbulence","Air rising over fields and falling over woods, with different heating by ground type."),
 ("met-18","19.12",r"Flying Hazards","Avoiding a tropical revolving storm","Aircraft route round a low of 960 hPa with dashed lines showing safe deviations."),
 ("met-18","19.13",r"Frequency","Tropical revolving storms of the world","World map of the main hurricane, typhoon and cyclone regions with the months and percentage frequency of each."),
 ("met-19","20.18",r"SW Monsoon","The monsoon winds in January and July","Two maps of southern Asia: the north-east monsoon in January and the south-west monsoon in July."),
 ("met-19","20.27",r"SW Monsoon","North-east monsoon","Map of the north-east monsoon winds blowing across southern Asia in winter."),
 ("met-19","20.14",r"Winter Season","Surface pressure in January","World map of pressure systems in January: Siberian high, Aleutian and Icelandic lows and the sub-tropical highs."),
 ("met-19","20.15",r"SW Monsoon","Surface pressure in July","World map of pressure systems in July with a large low over Asia."),
 ("met-20","20.2",r"Three Cell","The three cell model","Cross-section of the atmosphere from the equator to the pole with Hadley, Ferrel and polar cells and the surface wind belts."),
 ("met-20","20.3",r"Three Cell","World climatic zones","Bands of equatorial, savannah, arid, warm and cool temperate and polar climates and the winter and summer movement."),
 ("met-20","20.16",r"Surface Characteristics","Prevailing surface winds in January","World map of prevailing surface wind arrows in January with the ITCZ line."),
 ("met-20","20.39",r"Standing Waves|Rossby","Upper winds in July","World map of upper westerlies, polar front jets and sub-tropical jets, and the equatorial easterlies."),
 ("met-20","20.32",r"General Circulation of the Tropical|Rossby","Equatorial upper winds in January","World map of isotachs (red lines of equal wind speed) and streamlines for the equatorial upper winds in January."),
 ("met-20","20.33",r"General Circulation of the Tropical|Rossby","Equatorial upper winds in July","World map of isotachs (red lines of equal wind speed) and streamlines for the equatorial upper winds in July."),
 ("met-21","28.1",r"Aviation Met Offices","Volcanic Ash Advisory Centres","World map of the Volcanic Ash Advisory Centre areas of responsibility."),
 ("met-21","28.2",r"Aviation Met Offices","Regional Specialised Meteorological Centres","World map of RSMC areas."),
 ("met-22","14.9",r"Radar Scopes","Radar mosaic","Pixelated radar picture of rain echoes in shades of grey over the British Isles."),
 ("met-22","24.2",r"Cloud Characteristics","North Sea fog from a satellite","Grey-scale satellite picture of an area of low cloud and fog over the North Sea with the coast of land showing dark."),
 ("met-22","24.4",r"Cloud Characteristics","Satellite visible image","Grey-scale satellite visible image of a spiral cloud band of a depression with open cellular cumulus behind it."),
 ("met-22","24.6",r"Cloud Characteristics","Weather map and satellite image","Satellite cloud picture with isobars, fronts and pressure values drawn over a depression west of Europe."),
 ("met-23","12.3",r"Instrument Classification","Laser ceilometer","A laser ceilometer unit beside a runway."),
 ("met-23","15.11",r"Instrument Classification","Transmissometer","Transmissometer with a projector and detector either side of a runway."),
 ("met-27","27.1",r"SIGMET","Significant weather chart for Europe","European significant weather chart with fronts, cloud and icing areas."),
]
