# (k, chapter, heading regex, caption, alt)   k = index in jep_cat.json (Jeppesen book)
J = [
 (1,"met-01",r"Composition and Structure","Composition of dry air near the surface","Pie chart of dry air by volume: nitrogen 78.09 per cent, oxygen 20.95 per cent, argon 0.93 per cent and carbon dioxide 0.03 per cent."),
 (3,"met-01",r"Thermal Structure","Temperature through the layers of the atmosphere","Graph of temperature against height from the surface to 300 km: the temperature falls through the troposphere, rises through the stratosphere, falls through the mesosphere and rises again in the thermosphere, with the tropopause, stratopause and mesopause marked."),
 (4,"met-01",r"Atmospheric Layers in Detail","Tropopause height is highest over the tropics, lower in winter and higher in summer","Three globes with a grey wedge for the tropopause: the tropical tropopause the highest, the polar tropopause lower, and the winter and summer tropopause heights compared."),
 (2,"met-05",r"Introduction","The water cycle","Sketch of the water cycle: sea, river, a hill with rain falling from cloud, and water vapour rising from the sea."),
 (45,"met-05",r"SVP over Water vs Ice","Saturation vapour pressure over water and over ice","Graph of vapour pressure in hPa against temperature from minus 25 to plus 10 degrees: the curve for water lies above the ice curve below 0 degrees and the two meet at 0 degrees."),
 (44,"met-05",r"Key Humidity Terms","Mixing ratio at saturation against temperature","Graph of saturation mixing ratio in g per kg against temperature from minus 30 to plus 30 degrees, rising steeply above 10 degrees."),
 (11,"met-02",r"Pressure as Weight","Pressure falls with height","A column of air with two levels: the height of the column above the upper level is less than above the lower level, so the pressure there is less."),
 (14,"met-02",r"Semi-Diurnal","Semi-diurnal pressure variation","Pressure curve over 24 hours with peaks at 10:00 and 22:00 and troughs at 04:00 and 16:00; the swing is typically 3 hPa in the tropics and 1 hPa in temperate latitudes."),
 (18,"met-02",r"Pressure Patterns","Low pressure: air converges and rises","Vertical section of a low: air converging at the surface, ascending, and diverging aloft at 30,000 to 35,000 ft."),
 (21,"met-02",r"Pressure Patterns","High pressure: air descends and spreads out","Vertical section of a high: air converging aloft, descending, and diverging at the surface."),
 (192,"met-02",r"Pressure Patterns","Pressure systems on a surface chart","Surface chart showing highs, lows, a col, ridges of high pressure, a trough of low pressure and a secondary low."),
 (24,"met-02",r"Pressure Patterns","A trough of low pressure","V-shaped isobars around a trough line, with pressures from 996 to 1004 hPa."),
 (26,"met-02",r"Pressure Patterns","A ridge of high pressure","U-shaped isobars extending from a high, pressures from 1004 to 1010 hPa."),
 (29,"met-02",r"Pressure Settings","QFE and QNH at an elevated aerodrome","Aeroplane at 3500 ft above sea level over a hill aerodrome: QFE 988 and QNH 1010, a difference of 22 hPa, or 594 ft at 27 ft per hPa, giving a height above the aerodrome of 2906 ft."),
 (30,"met-02",r"Relation between QNH","Finding QNH from QFE","Aerodrome with QFE 965 hPa and 1500 ft above sea level, equal to 56 hPa, so QNH is 1021 hPa."),
 (34,"met-02",r"Under-Reading","Flying towards lower pressure the altimeter over-reads","Aeroplane descending as it flies from an area of 1020 hPa towards 1010 hPa with the same altimeter setting: the 10 hPa difference is 270 ft, so the true height is less than the altimeter shows."),
 (35,"met-02",r"Relation between QNH","QFF and QNH at different temperatures","Three columns above a sea level line showing QFF greater than QNH, equal to QNH and greater than QNH for different temperatures relative to ISA, with QFE 1035 at the aerodrome."),
 (51,"met-04",r"Density Altitude","Density altitude against pressure altitude","Three columns: ISA plus 1 degree, ISA, and ISA minus 1 degree, each 120 ft apart; warmer than ISA gives a higher density altitude."),
 (50,"met-04",r"Density Altitude","Warmer-than-ISA air has the same density at a higher height","A warm column and an ISA column both holding 1000 g per cubic metre at different heights."),
 (53,"met-09",r"Lapse Rates","DALR and SALR on a temperature-height graph","The red dry adiabatic line is straight; the green saturated adiabatic curve starts steeper and approaches the DALR with height."),
 (54,"met-09",r"Lapse Rates","Dry and saturated parcel cooling","A parcel of dry air cooling 3 degrees per 1000 ft and a saturated parcel cooling less, 1.5 degrees per 1000 ft at first, shown at 1000 ft steps from 15 degrees at the surface."),
 (55,"met-09",r"Stability Criteria","Stability regions by ELR","Graph with the DALR and SALR dividing the plot into absolute instability, conditional instability and absolute stability."),
 (82,"met-06",r"Names of Winds","Foehn effect over a mountain","Air at 15 degrees at sea level cools at the DALR to the cloud base at 1000 ft and then at the SALR to the crest at 4000 ft, with cloud on the windward side; on the lee side the descending air warms at the DALR and arrives much warmer."),
 (117,"met-06",r"Wind Measurement","Three-cup anemometer","Three-cup anemometer on a base."),
 (119,"met-06",r"Local Winds","Sea breeze by day","The sun heats the land: warm air rises over the land with low pressure, cool air flows from the sea at the surface, and a return flow aloft."),
 (120,"met-06",r"Local Winds","Land breeze by night","The land cools: cool air flows from land to sea at the surface with the return flow aloft towards the land."),
 (121,"met-06",r"Local Winds","Katabatic wind","At night air in contact with the ground cools, becomes denser and flows down the slope, typically 10 kt, collecting in the valleys."),
 (122,"met-06",r"Local Winds","Anabatic wind","By day the air in contact with the ground warms, becomes less dense and flows up the slope, typically no more than 5 kt."),
 (164,"met-06",r"Thermal Wind","Thermal wind: a warm column and a cold column","A warm column at 24 degrees and a cold column at 18 degrees, both 8000 ft tall and separated by 200 nm."),
 (165,"met-06",r"Thermal Wind","The thermal wind component","Vector triangle: the geostrophic wind and the thermal wind component add to give the upper wind."),
 (182,"met-06",r"Contours","Thickness: cold air gives low thickness, warm air high","Two columns between 1000 hPa and 500 hPa: the cold column is thinner than the warm column."),
 (184,"met-06",r"Wind Shear","Windshear on the approach: loss of headwind","Aeroplane crossing a shear line from a 30 kt headwind to 10 kt: the indicated airspeed falls from 130 kt to 110 kt."),
 (186,"met-06",r"Wind Shear","Downdraught and angle of attack","Aeroplane flying through a downdraught with the relative airflow and a decreasing angle of attack."),
 (97,"met-07",r"Vertical and Slant","Types of visibility","Aeroplane showing downward visibility, slant visibility and oblique visibility."),
 (101,"met-07",r"Vertical and Slant","Visibility above a shallow fog layer","An aeroplane above a shallow fog layer sees the aerodrome clearly; one flying lower cannot see it."),
 (102,"met-07",r"Types of Fog","Radiation fog and wind speed","Three panels at night under a clear sky: calm gives dew only, a light wind gives radiation fog, and a moderate wind gives low stratus."),
 (103,"met-07",r"Types of Fog","Advection fog","Warm moist air blowing from warm land over a cold sea, and warm moist air moving landwards over a cold land."),
 (110,"met-12",r"Engine Icing","Carburettor icing","Cutaway of a carburettor with intake air, fuel and ice forming at the venturi and throttle."),
 (92,"met-13",r"Life Cycle","The three stages of a thunderstorm","Growth stage with updraught only, mature stage with updraught and downdraught, and dissipating stage with downdraught."),
 (128,"met-14",r"Air Masses","Air mass source regions affecting Europe","Map of Europe with arrows for maritime Arctic, maritime polar, continental polar, maritime tropical and continental tropical air."),
 (85,"met-14",r"Warm Front","Warm front cross-section","Warm air rising over cold air along a gentle slope with the cloud sequence CI, CS, AS, NS and ST towards the surface front."),
 (86,"met-14",r"Cold Front","Cold front cross-section","Cold air undercutting warm air on a steep slope with CU/CB at the front, NS behind it and CI ahead."),
 (170,"met-15",r"Definition","Isotachs across a jet stream","Cutaway of a jet stream with the 80, 100, 120 and 150 kt contours around the core."),
 (178,"met-15",r"Cause","Clear air turbulence around the jet","Cross-section with primary CAT areas 1 and secondary CAT areas 2 around the jet cores."),
 (179,"met-15",r"Cause","A jet stream seen from space","Satellite view of a long band of cirrus lying along a jet stream."),
 (189,"met-17",r"Associated Clouds","Mountain wave and its clouds","Air flowing over a mountain range: cap cloud over the ridge, lenticular clouds at the wave crests, a roll cloud in the rotor and turbulence."),
 (275,"met-18",r"Easterly Waves","Easterly waves and the ITCZ","Map with trough axes of easterly waves, an intermediate stage, a tropical storm and thunderstorms south of the trade winds, above the ITCZ."),
 (276,"met-18",r"Easterly Waves","Convergence and divergence at a wave trough","Streamlines bunching at the trough axis, with convergence on one side and divergence on the other."),
 (278,"met-18",r"Tropical Cyclones","Cross-section of a tropical revolving storm","The eye with descending air, the wall of cloud around it, vertical currents spiralling upwards, stratiform layers and rain, and surface winds rotating about the eye."),
 (263,"met-19",r"Post Monsoon","Winter monsoon winds","North-westerly winds flowing out of the Siberian high over China and then over the Indian Ocean in winter."),
 (264,"met-19",r"SW Monsoon","Summer monsoon winds","South-easterly trades cross the equator to become south-westerly over the Indian Ocean and India with a long maritime track."),
 (230,"met-20",r"Three Cell","The idealised three-cell circulation","Globe with Polar, Ferrel and Hadley cells, polar front, horse latitudes, doldrums and equatorial lows, with the pressure belts and winds of each zone."),
 (234,"met-20",r"Three Cell","Vertical section of the cells and jet streams","Polar, Ferrel and Hadley cells in height with the polar front jet stream, the sub-tropical jet stream, the ITCZ cumulonimbus and the tropopause."),
 (240,"met-20",r"Hadley Cell","Hadley cells","Section from 30 degrees north to 30 degrees south: trade winds at the surface, antitrade winds aloft and rising air at the ITC."),
 (233,"met-20",r"Surface Characteristics","Surface pressure in January","World map of January pressure systems with the ITCZ."),
 (235,"met-20",r"Surface Characteristics","Surface pressure in July","World map of July pressure systems with the ITCZ."),
 (236,"met-20",r"Standing Waves|Rossby","Mean upper wind in January","World map of westerly winds and jet streams in January."),
 (237,"met-20",r"Standing Waves|Rossby","Mean upper wind in July","World map of westerly winds and jet streams in July."),
 (208,"met-24",r"Station Model Layout","Layout of the station model","Station circle for total cloud cover with positions marked for high, medium and low cloud, visibility, air temperature, present weather, dew point and the wind symbol."),
 (218,"met-24",r"Total Cloud Amount","Total cloud amount symbols","Circle symbols for sky clear, 1/8 to 8/8 and obscured."),
 (219,"met-24",r"Station Model Layout","Wind speed symbols","Wind staff symbols for calm, 1 to 2 kt, 5, 10, 15, 20, 50, 60 and 65 kt."),
 (210,"met-24",r"Cloud Codes","Low cloud symbols","Symbols for small cumulus, large cumulus, cumulonimbus, stratocumulus, stratus and fractostratus."),
 (215,"met-24",r"Cloud Codes","Medium cloud symbols","Symbols for altostratus and altocumulus types."),
 (217,"met-24",r"Cloud Codes","High cloud symbols","Symbols for cirrus, cirrostratus and cirrocumulus types."),
 (221,"met-28",r"National Significant","Symbols for significant weather","Chart symbols for thunderstorms, tropical cyclone, turbulence, mountain waves, icing, fog, hail, rain, snow, haze, dust and volcanic eruption."),
 (222,"met-28",r"National Significant","Fronts, convergence zones and other chart symbols","Symbols for surface fronts, convergence line, freezing level, tropopause height and the jet stream."),
 (223,"met-28",r"National Significant","Lines and symbols on a significant weather chart","Symbols for the speed of a front, an area of significant weather, an area of clear air turbulence and the freezing level."),
]
