import type { DemoQuestion } from "./demo-questions";

export const AIR_REGS_CH1_QUESTIONS: DemoQuestion[] = [
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "Which of the following is obligating for members of ICAO?",
    opts: [
      "ICAO shall approve the pricing of tickets on international airline connections",
      "ICAO must be informed about changes in the national regulations",
      "ICAO must be informed about differences from the standards in any of the Annexes to the convention",
    ],
    ans: 2,
    exp: "Article 38 obligates states to notify ICAO about differences from international standards in the Annexes (within 60 days for amendments).",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "For aircraft flying over the high seas, which rules shall be in force?",
    opts: [
      "The rules established by the state of the operator of the aircraft",
      "The rules established by the state(s) adjacent to the high seas overflown",
      "The rules established under the Convention of international civil aviation",
    ],
    ans: 2,
    exp: "Article 12 of the Chicago Convention: Over the high seas, the rules in force are those established under this Convention.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "Annex 14 to the convention on international civil aviation contains SARPs for:",
    opts: [
      "Air Traffic Services",
      "Aerodromes",
      "Facilitation",
    ],
    ans: 1,
    exp: "Annex 14 covers Aerodromes (Vol I: Aerodrome Design and Operations; Vol II: Heliports).",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "The Warsaw Convention and later amendments deals with:",
    opts: [
      "Limitation of the operator's responsibility vis-a-vis passengers and goods transported",
      "Operator's license for international scheduled aviation",
      "The security system at airports",
    ],
    ans: 0,
    exp: "The Warsaw Convention deals with the financial liability of airlines (operators) regarding passengers, baggage, and cargo.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "Annex 17 to the Convention of Chicago covers:",
    opts: [
      "Aerodromes",
      "Security",
      "Facilitation",
    ],
    ans: 1,
    exp: "Annex 17: Safeguarding International Civil Aviation against Acts of Unlawful Interference (Security).",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "The State has to notify the Council of ICAO if a state finds that it is impracticable to comply with an International Standard. The notice period is:",
    opts: [
      "It shall give 45 days notice to ICAO",
      "It shall give 60 days notice to ICAO of the differences between its own practices and the International Standard",
      "It shall give immediate notice to ICAO",
    ],
    ans: 1,
    exp: "Article 38: Exactly 60 days. This is a critical exam number.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "The international convention defining rules relative to the responsibilities of international air carriers for the carriage of passengers, baggage and freight is the:",
    opts: [
      "Hague Convention",
      "Warsaw Convention",
      "Tokyo Convention",
    ],
    ans: 1,
    exp: "Warsaw Convention 1929 defines the financial liability of air carriers for carriage of persons, baggage, and cargo.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "The 'Standards' contained in the Annexes to the Chicago Convention are to be considered:",
    opts: [
      "Binding for the member states that have not notified ICAO about a national difference",
      "Advice and guidance for the aviation legislation within the member states",
      "Binding for all airline companies with international traffic",
    ],
    ans: 0,
    exp: "ICAO Standards are binding (mandatory) for member states unless they have formally notified ICAO of a difference under Article 38.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "An aircraft flying over the territory of another state must:",
    opts: [
      "Follow the rules of the Air of the State it is overflying, provided they follow the ICAO rules",
      "Follow the rules of the Air of the State of the Operator, if registered in other State",
      "Follow the rules of the Air of the State of Registration to the extent that they do not conflict with the rules published by the State having jurisdiction over the territory overflown",
    ],
    ans: 2,
    exp: "Article 12: The State of registration's rules apply, but they must not conflict with the rules of the state having jurisdiction over the territory overflown.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "An airplane is planning a flight that will require a technical landing in a neighboring state. Which freedom of the air will be exercised?",
    opts: [
      "3rd freedom",
      "4th freedom",
      "2nd freedom",
    ],
    ans: 2,
    exp: "2nd Freedom: The privilege to land for non-traffic purposes (e.g., a technical/fuel stop).",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "The Tokyo Convention applies to:",
    opts: [
      "Offences caused in the territory of a contracting state or in a ship or aircraft registered therein, by an aircraft registered in the territory of another contracting state",
      "Offences only caused in the territory of a contracting state by any aircraft registered in the territory of another contracting state",
      "Offences caused in the territory of a contracting state by any aircraft regardless of the registration",
    ],
    ans: 0,
    exp: "Tokyo Convention applies to offences and acts committed on board aircraft registered in a contracting State, while in flight or on the surface of the high seas or any other area outside the territory of any State.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "The International Civil Aviation Organisation (ICAO) was established by the international convention of:",
    opts: [
      "Warsaw",
      "Chicago",
      "Montreal",
    ],
    ans: 1,
    exp: "ICAO was established by the Chicago Convention, 1944.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "The Rome Convention and later amendments deals with:",
    opts: [
      "Damage caused by foreign aircraft to third parties on the surface",
      "Offences and certain other acts committed on board aircraft",
      "Regulation of transportation of dangerous goods",
    ],
    ans: 0,
    exp: "Rome Convention 1952 covers damage caused by foreign aircraft to third parties on the surface of the earth.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "The convention on offences and certain acts committed on board aircraft is:",
    opts: [
      "The convention of Rome",
      "The convention of Tokyo",
      "The convention of Chicago",
    ],
    ans: 1,
    exp: "Tokyo Convention 1963: Convention on Offences and Certain Other Acts Committed on Board Aircraft.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "The aircraft commander, when he has reasonable grounds to believe that a person has committed or is about to commit, on board the aircraft, an offence against penal law:",
    opts: [
      "May not require or authorise the assistance of other crew members",
      "May require the assistance of passengers to restrain such persons",
      "May deliver such person to the competent authorities",
    ],
    ans: 2,
    exp: "Article 6 of Tokyo Convention: Commander may restrain and deliver such person to competent authorities. Note: Commander may request but NOT require passengers; can require crew.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "If a person is injured by a part falling from an aircraft flying over the state but registered in another state, which convention covers this?",
    opts: [
      "Paris",
      "Chicago",
      "Rome",
    ],
    ans: 2,
    exp: "Rome Convention 1952 covers damage caused by foreign aircraft to third parties on the surface.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "India is a signatory to the International Air Transport Agreement, 1944:",
    opts: [
      "Yes",
      "Yes, but it does not subscribe to Technical Freedoms",
      "No",
    ],
    ans: 2,
    exp: "India has NOT ratified the International Air Transport Agreement 1944 (which grants Commercial Freedoms 3rd–5th). India only ratified the IASTA 1944 (Technical Freedoms — 1st and 2nd).",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "The convention signed by states moved by a desire to ensure adequate compensation for persons who suffer damage caused on the surface by foreign aircraft is:",
    opts: [
      "The Paris Convention",
      "The Rome Convention",
      "The Warsaw Convention",
    ],
    ans: 1,
    exp: "Rome Convention 1952: Liability for damage caused on the ground by foreign aircraft to third parties on the surface.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "Which Annex to the Chicago Convention covers dangerous goods carried in aircraft?",
    opts: [
      "Annex 16",
      "Annex 18",
      "Annex 17",
    ],
    ans: 1,
    exp: "Annex 18: Safe Transport of Dangerous Goods by Air. (Annex 16 = Environmental Protection; Annex 17 = Security)",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "Proposal to give effect to an International Convention in India is initiated by:",
    opts: [
      "Ministry of Civil Aviation",
      "Parliament",
      "DGCA",
    ],
    ans: 2,
    exp: "DGCA carries out amendments to the Aircraft Act, Aircraft Rules, and CARs for complying with ICAO Annex amendments, and initiates proposals for giving effect to international Conventions.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "The second freedom of the air is the:",
    opts: [
      "Right to operate a commercial passenger flight between two states",
      "Right to land for a technical stop",
      "Right to cabotage traffic",
    ],
    ans: 1,
    exp: "2nd Freedom: The privilege to land for non-traffic (technical) purposes — e.g., a fuel or maintenance stop.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "Which convention makes acts of violence on board, destruction of aircraft in flight, and destroying or damaging any air navigation facility punishable?",
    opts: [
      "The Tokyo Convention",
      "The Montreal Convention",
      "The Warsaw Convention",
    ],
    ans: 1,
    exp: "Montreal Convention 1971: Suppression of Unlawful Acts Against the Safety of Civil Aviation (sabotage, destroying aircraft, damaging navigation facilities).",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "According to which Convention may an aircraft commander impose measures upon a person committing a crime or an offence on board the aircraft?",
    opts: [
      "The Convention of Rome",
      "The Convention of Warsaw",
      "The Convention of Tokyo",
    ],
    ans: 2,
    exp: "Tokyo Convention 1963 grants the Aircraft Commander powers to impose reasonable measures including restraint upon a person committing or about to commit an offence on board.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "'Cabotage' refers to:",
    opts: [
      "Domestic air services",
      "A national air carrier",
      "Crop spraying",
    ],
    ans: 0,
    exp: "Cabotage (Article 7): The right of a State to refuse foreign airlines permission to carry passengers/cargo for hire between two points within the same territory — i.e., domestic air services.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "In case of a conflict between ICAO regulations and national regulations, which one takes precedence?",
    opts: [
      "ICAO regulations are always binding for all member states in the interest of uniformity",
      "ICAO regulations for the member states that have not notified ICAO about a national difference within a specified period",
      "National regulations always take precedence over ICAO regulations",
    ],
    ans: 1,
    exp: "ICAO Standards are binding for member states that have NOT notified ICAO of a national difference (Article 38). If a state notifies ICAO within 60 days, its own national regulation takes precedence for that state.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "Which convention is considered to be a forerunner of the Chicago Convention, 1944?",
    opts: [
      "Warsaw Convention, 1929",
      "Paris Convention, 1919",
      "Ibero-American Convention, 1926",
    ],
    ans: 1,
    exp: "Paris Convention 1919 is considered the forerunner (predecessor) of the Chicago Convention 1944. It established ICAN, while Chicago established ICAO.",
  },
  {
    subjectIds: ["air-regulations", "atpl-air-regulations"],
    chapterId: "ar-1",
    q: "ICAO is:",
    opts: [
      "An independent and autonomous agency, with a constituency status in the UNO",
      "A part and parcel of UNO as a non-specialised agency",
      "Not associated with UNO at all",
    ],
    ans: 0,
    exp: "ICAO is an independent and autonomous agency, with a constituency (specialized agency) status in the United Nations Organization, linked to the Economic and Social Council since 1947.",
  },
];
