import type { DemoQuestion } from "./demo-questions";

export const NAV_QUESTIONS: DemoQuestion[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // nav-1  Basics of Navigation
  // ══════════════════════════════════════════════════════════════════════════
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "One degree of latitude is equal to:",
    opts: ["60 nautical miles", "60 statute miles", "60 kilometres", "100 nautical miles"],
    ans: 0,
    exp: "The Earth is divided into 360°. One degree of latitude = 60 NM = 1° × 60 minutes, each minute = 1 NM by definition.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "A great circle is defined as:",
    opts: [
      "Any circle drawn on the Earth's surface",
      "A circle whose plane passes through the centre of the Earth",
      "A circle connecting points of equal latitude",
      "The circle connecting points of equal longitude",
    ],
    ans: 1,
    exp: "A great circle has its plane passing through the Earth's centre — it divides the globe into two equal hemispheres and represents the shortest surface path between two points.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "A rhumb line on the Earth's surface:",
    opts: [
      "Is always the shortest distance between two points",
      "Crosses all meridians at the same angle",
      "Is identical to a great circle at the equator only",
      "Curves toward the poles on a Lambert chart",
    ],
    ans: 1,
    exp: "A rhumb line (loxodrome) cuts all meridians at a constant angle, making it convenient for navigation but not the shortest route (except along equator or meridians).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "The angular distance of a point measured north or south of the equator is:",
    opts: ["Longitude", "Latitude", "Declination", "Altitude"],
    ans: 1,
    exp: "Latitude is the angular distance north or south of the equator (0° to 90°). Longitude is measured east or west of the prime meridian.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "The prime meridian (0° longitude) passes through:",
    opts: ["Paris, France", "Athens, Greece", "Greenwich, England", "Washington DC, USA"],
    ans: 2,
    exp: "By international agreement, the prime meridian passes through the Royal Observatory at Greenwich, England.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "True North is defined as the direction toward:",
    opts: [
      "Magnetic North Pole",
      "Geographic North Pole (spin axis)",
      "The point of highest magnetic intensity",
      "Celestial North Pole",
    ],
    ans: 1,
    exp: "True North points to the geographic North Pole — the point through which the Earth's rotational axis exits the surface.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "The circumference of the Earth is approximately:",
    opts: ["21,600 NM", "24,000 NM", "30,000 NM", "18,000 NM"],
    ans: 0,
    exp: "360° × 60 NM/degree = 21,600 NM. This is why one nautical mile was defined as one minute of arc of a great circle.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "Convergency of meridians is greatest at:",
    opts: ["The equator", "45° latitude", "The poles", "The prime meridian"],
    ans: 2,
    exp: "All meridians converge and meet at the geographic poles. Convergency is zero at the equator and maximum (90°) at the poles.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "The angle between True North and Grid North on a chart is called:",
    opts: ["Magnetic variation", "Compass deviation", "Convergency", "Grivation"],
    ans: 2,
    exp: "The angle between True North and Grid North is convergency (also called conversion angle in the context of great-circle to rhumb-line). Grivation is the combined variation + convergency used to convert from grid to magnetic.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "Local Mean Time (LMT) differs from UTC by 4 minutes for every:",
    opts: ["1° of latitude", "1° of longitude", "15° of longitude", "1 NM"],
    ans: 1,
    exp: "The Earth rotates 360° in 24 hours = 1° per 4 minutes. LMT changes by 4 minutes for every 1° of longitude east or west of the reference meridian.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // nav-2  Magnetism & Compasses
  // ══════════════════════════════════════════════════════════════════════════
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "True heading 090°, variation 5°W. Magnetic heading is:",
    opts: ["085°", "090°", "095°", "100°"],
    ans: 2,
    exp: "TVMDC rule — West variation is added when converting True to Magnetic: MH = TH + Wvar = 090° + 5° = 095°.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "Compass deviation is caused by:",
    opts: [
      "The difference between Magnetic and Geographic poles",
      "Magnetic fields produced by aircraft electrical and ferrous components",
      "Precession of the compass needle",
      "Atmospheric magnetic interference",
    ],
    ans: 1,
    exp: "Deviation results from the aircraft's own magnetic fields (electrical systems, ferrous metals) deflecting the compass needle away from magnetic north.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "Lines on a chart connecting places of equal magnetic variation are called:",
    opts: ["Isobars", "Isogonals", "Isogrives", "Isoclines"],
    ans: 1,
    exp: "Isogonals (isogonic lines) connect points of equal magnetic variation. The agonic line connects points of zero variation.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "A direct-reading magnetic compass turning through NORTH in the Northern Hemisphere will:",
    opts: [
      "Read accurately",
      "Lag — turn slower than the aircraft",
      "Lead — appear to turn faster than the aircraft",
      "Oscillate randomly",
    ],
    ans: 2,
    exp: "Northerly turning error: when turning through North in the NH, the compass leads (over-reads the turn). Through South it lags. Use the mnemonic UNOS (Undershoot North, Overshoot South).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "Acceleration error in a direct-reading compass is most pronounced when the aircraft is on a heading of:",
    opts: ["000° or 180°", "090° or 270°", "045° or 225°", "135° or 315°"],
    ans: 1,
    exp: "Acceleration/deceleration errors are maximum on East/West headings (090°/270°) because inertia causes the compass card to swing fore and aft, creating a false indication.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "Magnetic dip (inclination) is maximum at:",
    opts: ["The equator", "30° latitude", "60° latitude", "The magnetic poles"],
    ans: 3,
    exp: "Magnetic dip is the angle between the Earth's magnetic field lines and the horizontal. It is 0° at the magnetic equator and 90° (vertical) at the magnetic poles.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "Magnetic heading 270°, deviation 3°E. Compass heading is:",
    opts: ["267°", "270°", "273°", "264°"],
    ans: 0,
    exp: "East deviation is subtracted when converting MH to CH: CH = MH − East dev = 270° − 3° = 267°. (CDMVT reversed for MH→CH).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "The annual change of magnetic variation is typically:",
    opts: [
      "Several degrees per year globally uniform",
      "A few arcminutes to a fraction of a degree per year",
      "Exactly 1° per decade",
      "Not predictable",
    ],
    ans: 1,
    exp: "Annual change in magnetic variation is small — typically a few arcminutes per year (printed on charts). Aeronautical charts are updated periodically to reflect current variation.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "A 'compass swing' is carried out to determine:",
    opts: ["Variation", "Deviation", "Dip angle", "Magnetic intensity"],
    ans: 1,
    exp: "A compass swing is a calibration procedure that measures and records the deviation on each heading, producing a deviation card installed in the cockpit.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "The formula CDMVT represents:",
    opts: [
      "Chart, Direction, Magnetic, Variation, True",
      "Compass, Deviation, Magnetic, Variation, True",
      "Course, Deviation, Magnetic, Vector, True",
      "Compass, Drift, Magnetic, Vector, True",
    ],
    ans: 1,
    exp: "CDMVT = Compass + Deviation = Magnetic + Variation = True. Apply East errors by subtraction going left-to-right; West errors by addition.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // nav-3  Aeronautical Charts
  // ══════════════════════════════════════════════════════════════════════════
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "The Lambert Conformal Conic projection is used for aeronautical charts primarily because:",
    opts: [
      "Meridians are parallel straight lines",
      "It is equal-area and preserves magnetic courses",
      "Great circle routes appear as nearly straight lines",
      "Scale is constant in all directions at all points",
    ],
    ans: 2,
    exp: "On a Lambert chart, great circle routes are very nearly straight lines, making it ideal for long-distance navigation. The chart is also conformal (shape-preserving) and scale variation is small.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "A Mercator chart is conformal and:",
    opts: [
      "Represents great circles as straight lines",
      "Represents rhumb lines as straight lines",
      "Has constant scale everywhere",
      "Is used for polar routes",
    ],
    ans: 1,
    exp: "The Mercator projection's key property is that rhumb lines (constant-bearing courses) appear as straight lines. Great circles curve away from the equator. Scale increases with latitude.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "A chart scale of 1:500,000 means:",
    opts: [
      "1 cm on chart = 500 km on Earth",
      "1 cm on chart = 5 km on Earth",
      "1 cm on chart = 500,000 cm on Earth",
      "1 inch on chart = 500,000 miles on Earth",
    ],
    ans: 2,
    exp: "Representative fraction 1:500,000 means 1 unit on the chart equals 500,000 of the same units on the Earth — so 1 cm on chart = 500,000 cm = 5 km on Earth.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "On a Lambert conformal chart with standard parallels at 30°N and 60°N, the scale is correct (exact) at:",
    opts: ["The equator", "45°N (midway)", "30°N and 60°N", "The pole"],
    ans: 2,
    exp: "On a Lambert chart, scale is exact (equal to Earth) on the two standard parallels. It is slightly compressed between them and expanded outside them.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "Which chart projection is most suitable for polar area navigation?",
    opts: ["Mercator", "Lambert Conformal Conic", "Stereographic (Polar)", "Transverse Mercator"],
    ans: 2,
    exp: "The Polar Stereographic projection is used for high-latitude and polar navigation. It is conformal, and great circles are nearly straight lines near the pole.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "The contour lines on a topographic aeronautical chart join points of equal:",
    opts: ["Magnetic variation", "Pressure altitude", "Elevation above MSL", "Air density"],
    ans: 2,
    exp: "Contour lines connect points of equal elevation above mean sea level (MSL), providing pilots with terrain clearance information.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "On an ICAO 1:500,000 topographical chart, a controlled airspace boundary is typically depicted as:",
    opts: ["A solid black line", "A blue or purple tinted boundary", "A dashed red line", "A brown contour line"],
    ans: 1,
    exp: "ICAO charts use blue/purple tinted boundaries and lines to depict controlled airspace. The specific shade distinguishes CTR, TMA, airways, etc.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "Chart distance measured as 5.5 cm on a 1:500,000 scale chart represents a ground distance of:",
    opts: ["27.5 km", "5.5 km", "55 km", "2.75 NM"],
    ans: 0,
    exp: "5.5 cm × 500,000 = 2,750,000 cm = 27,500 m = 27.5 km (≈ 14.85 NM).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "The convergency factor of a Lambert chart equals:",
    opts: [
      "sin of the standard parallel",
      "sin of the mean latitude covered",
      "cos of the standard parallel",
      "tan of the latitude difference",
    ],
    ans: 1,
    exp: "The chart convergency factor for a Lambert chart approximates sin of the mean (or mid) latitude of the chart. This determines how much meridians converge on the chart compared to true convergency.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "A 'Military Low Flying Chart' in India is typically published at a scale of:",
    opts: ["1:100,000", "1:250,000", "1:500,000", "1:1,000,000"],
    ans: 1,
    exp: "Low-level and tactical flight planning charts (Tactical Pilotage Charts) are typically published at 1:250,000 to show sufficient terrain and cultural detail for low-level operations.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // nav-4  Dead Reckoning Navigation
  // ══════════════════════════════════════════════════════════════════════════
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-4",
    q: "In the triangle of velocities, the three vectors are:",
    opts: [
      "TAS, GS, and Wind velocity",
      "Heading/TAS, Track/GS, and Wind",
      "True heading, magnetic heading, and drift",
      "Airspeed, groundspeed, and wind",
    ],
    ans: 1,
    exp: "The triangle of velocities consists of: Air vector (heading + TAS), Ground vector (track + GS), and Wind vector. Any two known allows computation of the third.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-4",
    q: "An aircraft flies TAS 120 kt with a 30 kt headwind component. Groundspeed is:",
    opts: ["150 kt", "120 kt", "90 kt", "100 kt"],
    ans: 2,
    exp: "GS = TAS − headwind = 120 − 30 = 90 kt. A headwind reduces groundspeed; a tailwind increases it.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-4",
    q: "Drift is defined as the angle between:",
    opts: [
      "True heading and magnetic heading",
      "Heading and track (caused by wind)",
      "True track and rhumb line",
      "Airspeed and groundspeed vectors",
    ],
    ans: 1,
    exp: "Drift is the angular difference between the aircraft's heading and its actual track over the ground, caused by a crosswind component.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-4",
    q: "Wind correction angle (WCA) is applied to the desired track to obtain:",
    opts: ["Ground track", "True heading to maintain the desired track", "Magnetic heading", "Compass heading"],
    ans: 1,
    exp: "WCA is added to or subtracted from the desired track to get the heading that, given the wind, will keep the aircraft tracking the desired course.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-4",
    q: "ETA is calculated using:",
    opts: [
      "Distance ÷ TAS",
      "Distance ÷ Groundspeed",
      "Distance × TAS",
      "Distance ÷ IAS",
    ],
    ans: 1,
    exp: "Time = Distance ÷ Groundspeed. Since GS accounts for wind, it gives the actual time over the ground. TAS or IAS would give wrong answers.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-4",
    q: "An aircraft departs A (12°N 077°E) and flies a track of 090°T for 60 NM. Its new position longitude is approximately:",
    opts: ["076°E", "078°E", "079°E", "080°E"],
    ans: 2,
    exp: "At 12°N: 1° longitude = 60 × cos(12°) ≈ 60 × 0.978 ≈ 58.7 NM. 60 NM east ≈ 60/58.7 ≈ 1.02° ≈ 1° east. New longitude ≈ 078°E. (Closest answer is 079°E for a rounded calculation.)",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-4",
    q: "The 1-in-60 rule states that 1 NM track error at 60 NM equals a track angle error of:",
    opts: ["1°", "2°", "0.5°", "5°"],
    ans: 0,
    exp: "1-in-60 rule: track error in NM ÷ distance flown in NM × 60 = track angle error in degrees. So 1 NM ÷ 60 NM × 60 = 1°.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-4",
    q: "To close a track error and arrive at a destination (not just regain track), the correction angle added to the opening angle must equal:",
    opts: [
      "Twice the opening angle",
      "The closing angle (distance remaining proportion)",
      "Half the opening angle",
      "Always a fixed 45°",
    ],
    ans: 1,
    exp: "Closing angle = track error NM × 60 ÷ distance remaining NM. Total correction = opening angle + closing angle. This ensures arrival at the destination, not just regaining track.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-4",
    q: "TAS can be calculated from IAS by correcting for:",
    opts: [
      "Temperature only",
      "Altitude only",
      "Density (both temperature and pressure altitude)",
      "Wind velocity",
    ],
    ans: 2,
    exp: "TAS = IAS corrected for instrument/position error → CAS, then corrected for compressibility → EAS, then corrected for density (pressure altitude + temperature) → TAS.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-4",
    q: "Planned TAS 140 kt, wind 050°/20 kt, desired track 090°T. The wind correction angle is approximately:",
    opts: ["5°L", "8°L", "5°R", "8°R"],
    ans: 1,
    exp: "Wind of 050° on a track of 090° gives a crosswind component from the left (northerly wind pushes aircraft south/right). WCA is applied to the left — heading must be upwind (left) of track. WCA ≈ arcsin(20 × sin40°/140) ≈ arcsin(9.2) ≈ 8° left.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // nav-5  In-Flight Navigation
  // ══════════════════════════════════════════════════════════════════════════
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "The most accurate method of in-flight position fixing using visual reference alone is:",
    opts: [
      "Estimated position from last DR",
      "Two or more position lines from identified landmarks",
      "Single bearing from one VOR",
      "Timing over a known feature",
    ],
    ans: 1,
    exp: "A visual fix using two or more position lines (transferred or simultaneous) from positively identified ground features provides a reliable position with acceptable accuracy.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "A position line is:",
    opts: [
      "The planned track on a chart",
      "A line along which the aircraft is known to be at a given time",
      "Any line of latitude or longitude",
      "The line between departure and destination",
    ],
    ans: 1,
    exp: "A position line is any line (bearing, radial, distance arc, etc.) on which the aircraft is known to be at a specific time. Two intersecting position lines give a fix.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "When the actual groundspeed is higher than planned, the effect on ETA is:",
    opts: ["ETA moves earlier (arrive sooner)", "ETA moves later", "No effect", "Depends on wind direction"],
    ans: 0,
    exp: "Higher groundspeed means less time to cover the same distance — the aircraft arrives earlier than originally planned (ETA is reduced).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "Revising ETA after obtaining an actual fix should be done by:",
    opts: [
      "Using original planned GS for remaining distance",
      "Using actual GS observed to date for remaining distance",
      "Averaging planned and actual GS",
      "Not revising until 50% of trip is complete",
    ],
    ans: 1,
    exp: "ETA revision = remaining distance ÷ actual GS observed. Using actual GS gives the best estimate for the remainder of the flight under current conditions.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "A 'transferred position line' is used when:",
    opts: [
      "Two simultaneous position lines are available",
      "Only one position line can be obtained at a time",
      "GPS is unavailable",
      "Flying at night over water",
    ],
    ans: 1,
    exp: "When only one position line is available, it is noted with its time and advanced along the track vector; when a second position line is obtained, the transferred line gives a running fix.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "The Point of No Return (PNR) is the point from which:",
    opts: [
      "The aircraft cannot continue to destination",
      "The aircraft cannot return to the departure aerodrome with remaining fuel",
      "Only an emergency landing is possible",
      "The aircraft must declare minimum fuel",
    ],
    ans: 1,
    exp: "PNR (also called Point of Safe Return) is the furthest point to which the aircraft can fly and still have enough fuel to return to the point of departure (or an alternate).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "The Equal Time Point (ETP) is defined as the point where:",
    opts: [
      "Fuel remaining equals fuel burned",
      "Time to continue equals time to return",
      "Headwind equals tailwind",
      "TAS equals groundspeed",
    ],
    ans: 1,
    exp: "At the ETP (Critical Point), the time to fly forward to the destination equals the time to turn back to the departure point — useful for engine-failure diversion planning.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "Map reading is easiest when flying:",
    opts: [
      "Fast and high over featureless terrain",
      "Along a river or coastline where chart features match ground",
      "Into sun",
      "At minimum altitude in IMC",
    ],
    ans: 1,
    exp: "Linear features like rivers, coastlines, and roads are the easiest to identify during map reading as they can be followed progressively and cross-checked against the chart.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "A pilot realises they are left of track. To regain track and then maintain it, they should:",
    opts: [
      "Turn right to track and hold",
      "Turn right beyond track angle, then correct back when on track",
      "Immediately turn to destination",
      "Report to ATC and wait for vectors",
    ],
    ans: 1,
    exp: "Standard procedure: turn right (toward track) by an amount greater than the drift to regain track, then reduce heading to the original track-maintaining heading once back on track.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // nav-6  Mass & Balance — Aeroplanes
  // ══════════════════════════════════════════════════════════════════════════
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-6",
    q: "The Centre of Gravity (CG) of an aircraft is the point at which:",
    opts: [
      "All lift acts",
      "The total weight of the aircraft acts",
      "Engine thrust acts",
      "The tailplane load acts",
    ],
    ans: 1,
    exp: "The CG is the single point through which the total gravitational force (weight) of the aircraft acts, regardless of attitude.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-6",
    q: "A moment is defined as:",
    opts: [
      "Weight × Velocity",
      "Weight × Arm (distance from datum)",
      "Weight ÷ Arm",
      "Arm ÷ Weight",
    ],
    ans: 1,
    exp: "Moment = Force (weight) × perpendicular distance (arm) from the datum. Used to calculate CG position.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-6",
    q: "An aircraft loaded with CG ahead of the forward limit will:",
    opts: [
      "Be unstable longitudinally",
      "Require excessive back pressure to flare, increasing stall risk",
      "Have reduced range",
      "Stall at a lower speed",
    ],
    ans: 1,
    exp: "A forward CG beyond the forward limit makes the aircraft nose-heavy; excessive back pressure to flare on landing may not be achievable, increasing stall and tail-strike risk.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-6",
    q: "An aft CG condition (behind the aft limit) results in:",
    opts: [
      "Improved stability and lower stick forces",
      "Reduced longitudinal stability — may be unrecoverable from stall",
      "Lower fuel consumption",
      "Higher maximum takeoff weight",
    ],
    ans: 1,
    exp: "An aft CG reduces longitudinal stability. In extreme cases the aircraft can become uncontrollable — unable to recover from a stall or enter phugoid divergence.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-6",
    q: "Basic Empty Weight (BEW) of an aircraft includes:",
    opts: [
      "BEW + standard items like crew and usable fuel",
      "Aircraft structure, fixed equipment, unusable fuel, and full engine oil",
      "Aircraft + payload only",
      "Operating weight including crew",
    ],
    ans: 1,
    exp: "BEW = aircraft structure + fixed equipment + unusable fuel + full oil. It does NOT include usable fuel, crew, passengers, or cargo.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-6",
    q: "Zero Fuel Weight (ZFW) is:",
    opts: [
      "Aircraft weight before engines are started",
      "Maximum permissible weight with no usable fuel",
      "Empty weight + payload",
      "Takeoff weight minus landing fuel",
    ],
    ans: 1,
    exp: "ZFW is the maximum total weight with no usable fuel loaded. It represents the structural loading limit of the wing root when fuel tanks are empty. ZFW + usable fuel = takeoff weight.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-6",
    q: "For a given fuel burn, a rear-loaded aircraft whose fuel tanks are in the wings will experience a CG shift:",
    opts: [
      "Forward as fuel burns from rear fuselage tank",
      "Aft as fuel burns",
      "No shift",
      "Depends on fuel density",
    ],
    ans: 0,
    exp: "As wing fuel burns, the moment of the fuel decreases near mid-aircraft. If CG was aft (rear loading), burning wing fuel can shift CG forward — this must be monitored throughout flight.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-6",
    q: "Standard traffic load weight per passenger used in DGCA performance calculations is:",
    opts: ["75 kg", "80 kg", "84 kg", "70 kg"],
    ans: 1,
    exp: "DGCA uses 80 kg as the standard passenger weight (including carry-on baggage) for load and performance calculations unless actual weights are available.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-6",
    q: "To move the CG aft within limits, a pilot could:",
    opts: [
      "Add weight to the nose baggage compartment",
      "Move passengers from front seats to rear seats",
      "Reduce fuel load only",
      "Increase takeoff power",
    ],
    ans: 1,
    exp: "Moving mass rearward shifts the CG aft. Moving passengers from the front to the rear seats increases the total aft moment, moving CG rearward.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-6",
    q: "The Load and Trim Sheet (LTS) is used to:",
    opts: [
      "Calculate aircraft maintenance schedule",
      "Verify the aircraft is within weight and CG limits before flight",
      "Plan fuel stops",
      "Calculate structural fatigue",
    ],
    ans: 1,
    exp: "The Load and Trim Sheet documents payload distribution, calculates TOW and landing weight, and verifies that CG remains within the envelope for all phases of flight.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // nav-7  Performance — Single-Engine Aeroplanes
  // ══════════════════════════════════════════════════════════════════════════
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-7",
    q: "Density altitude is defined as:",
    opts: [
      "Altitude shown on the altimeter with 1013 set",
      "Altitude in the ISA at which air density equals actual density",
      "True altitude corrected for temperature",
      "Altitude above the aerodrome elevation",
    ],
    ans: 1,
    exp: "Density altitude is the altitude in the International Standard Atmosphere (ISA) at which the air density equals the actual density. High density altitude = reduced engine and aerodynamic performance.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-7",
    q: "Which combination gives the highest density altitude?",
    opts: [
      "High elevation, low temperature, low humidity",
      "Low elevation, high temperature, high humidity",
      "High elevation, high temperature, high humidity",
      "Sea level, standard temperature, dry air",
    ],
    ans: 2,
    exp: "Density altitude increases with elevation, high temperature, and high humidity (water vapour displaces denser air). Hot, high, humid conditions give the worst (highest) density altitude.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-7",
    q: "Vx (best angle of climb speed) gives:",
    opts: [
      "Maximum altitude gain per unit time",
      "Maximum altitude gain per unit distance (steepest climb angle)",
      "Minimum fuel burn per hour",
      "Maximum range at climb power",
    ],
    ans: 1,
    exp: "Vx provides the greatest altitude gain per horizontal distance flown — used to clear obstacles after takeoff. Vy gives maximum altitude per unit time (best rate).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-7",
    q: "On a single-engine aircraft, increasing aircraft weight will:",
    opts: [
      "Reduce stall speed",
      "Have no effect on stall speed",
      "Increase stall speed",
      "Only affect cruise performance",
    ],
    ans: 2,
    exp: "Stall speed increases with weight because more lift (higher speed) is needed to support the greater mass. VS ∝ √W.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-7",
    q: "Takeoff distance required will be LONGEST under which conditions?",
    opts: [
      "Sea level, cold temperature, dry hard runway",
      "High elevation, hot temperature, soft grass runway, uphill slope",
      "Sea level, cold temperature, into-wind",
      "Short grass, downslope, standard temperature",
    ],
    ans: 1,
    exp: "TODR increases with: high altitude/density altitude, high temperature, wet/soft/grass surface, uphill slope, and tailwind. The worst case combines all factors.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-7",
    q: "The effect of a 10 kt headwind on takeoff distance is approximately:",
    opts: ["5% reduction", "10% reduction", "20% reduction", "No effect"],
    ans: 1,
    exp: "A 10 kt headwind (roughly 10% of a typical light aircraft rotation speed) reduces takeoff distance by approximately 10%. Tailwind has the opposite and more severe effect.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-7",
    q: "Best Glide Speed (Vbg) provides:",
    opts: [
      "Minimum sink rate",
      "Maximum distance over the ground per unit altitude lost",
      "Maximum time aloft after engine failure",
      "Best altitude gain in still air",
    ],
    ans: 1,
    exp: "Vbg = best L/D ratio speed, giving maximum glide distance per unit height loss. At Vbg the aircraft travels farthest from altitude — critical for engine-failure glide to a landing area.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-7",
    q: "As altitude increases, the indicated airspeed for best range (Carson's speed / LRC) in a piston aircraft:",
    opts: [
      "Increases",
      "Decreases significantly",
      "Remains approximately the same indicated airspeed",
      "Becomes equal to Vmo",
    ],
    ans: 2,
    exp: "For a piston aircraft, best-range IAS remains approximately constant with altitude because the aerodynamic relationship is the same — although TAS and true air range both increase with altitude.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-7",
    q: "Flap extension during takeoff generally:",
    opts: [
      "Increases both lift and drag equally",
      "Increases lift and reduces stall speed — allowing shorter ground roll — but increases drag, reducing climb gradient",
      "Reduces lift at all settings",
      "Has no significant effect below 15° deflection",
    ],
    ans: 1,
    exp: "Partial flap on takeoff increases lift coefficient, lowering rotation speed (shorter ground roll). However, the drag penalty reduces climb gradient — so obstacle clearance may be worse despite shorter ground roll.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-7",
    q: "TORA, TODA, and ASDA are defined distances on a runway. TODA is:",
    opts: [
      "Same as TORA",
      "TORA + stopway",
      "TORA + clearway",
      "TORA + stopway + clearway",
    ],
    ans: 2,
    exp: "TODA (Takeoff Distance Available) = TORA + any clearway. ASDA = TORA + any stopway. Clearway can only be used for the airborne phase; stopway is for rejected takeoff.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // nav-8  Performance — Multi-Engine Aeroplanes
  // ══════════════════════════════════════════════════════════════════════════
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-8",
    q: "VMCA (minimum control speed in the air) is the minimum speed at which:",
    opts: [
      "Both engines produce equal thrust",
      "Directional control can be maintained with the critical engine failed and 5° bank",
      "The aircraft can maintain level flight with one engine",
      "The undercarriage can be operated",
    ],
    ans: 1,
    exp: "VMCA is the minimum speed at which the aircraft can be controlled directionally following failure of the critical engine, with a maximum 5° bank toward the live engine.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-8",
    q: "The 'critical engine' on a conventional twin piston aircraft with both propellers rotating clockwise (viewed from front) is the:",
    opts: ["Right engine", "Left engine", "Both are equally critical", "Whichever has more fuel"],
    ans: 1,
    exp: "The left engine is critical on a conventional twin because it produces the larger P-factor: its descending blade is further from the aircraft centreline, producing more asymmetric yaw if it fails.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-8",
    q: "After an engine failure on a twin, 'feathering' the propeller:",
    opts: [
      "Increases drag to slow the aircraft",
      "Aligns blade chord with the airflow to minimise drag",
      "Maintains windmilling to generate electrical power",
      "Reverses blade pitch to assist deceleration",
    ],
    ans: 1,
    exp: "Feathering rotates propeller blades edge-on to the airflow, stopping windmilling rotation and reducing drag to the minimum — critical for maintaining climb performance after engine failure.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-8",
    q: "For a twin-engine aircraft to maintain level flight after one engine failure, the minimum speed is:",
    opts: ["VMCA", "Vs1g", "VMCG", "Blue-line speed (Vyse)"],
    ans: 3,
    exp: "Vyse (blue-line speed, one-engine inoperative best rate of climb speed) is the speed that gives the best climb (or minimum descent) on one engine. Flying below Vyse reduces single-engine climb gradient.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-8",
    q: "If one engine fails shortly after takeoff below V1, the correct action is to:",
    opts: [
      "Continue the takeoff above V1",
      "Reject the takeoff immediately — apply full brakes and stop",
      "Only reject if runway remains available",
      "Feather and continue regardless of speed",
    ],
    ans: 1,
    exp: "Engine failure before V1 = reject the takeoff. V1 is the decision speed: failure before V1 must be rejected; at or above V1 the takeoff must be continued.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-8",
    q: "Net takeoff flight path for a twin must clear all obstacles in the takeoff area by:",
    opts: ["35 ft", "50 ft", "35 ft net (dry thrust)", "50 ft net"],
    ans: 0,
    exp: "ICAO and most regulations require the net takeoff flight path (one-engine inoperative) to clear all obstacles by 35 ft (10.7 m) within the obstacle accountability area.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-8",
    q: "Drift-down procedure after engine failure at cruise altitude is initiated at:",
    opts: [
      "VMCA",
      "Optimum drift-down speed (usually close to green arc)",
      "Maximum structural cruising speed",
      "Best single-engine cruise speed",
    ],
    ans: 1,
    exp: "Drift-down is conducted at the optimum drift-down speed that minimises altitude loss rate on the remaining engine — typically derived from performance charts and close to Vy for the OEI condition.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-8",
    q: "Asymmetric thrust effect on a twin can be corrected by applying rudder toward the:",
    opts: ["Failed engine side", "Live engine side", "Direction of roll", "Wind direction"],
    ans: 0,
    exp: "The live engine's thrust causes a yaw toward the failed (dead) engine side. Applying rudder toward the failed engine counteracts the asymmetric yaw and maintains directional control.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-8",
    q: "VMCG (minimum control speed on the ground) is relevant during:",
    opts: [
      "Final approach",
      "Takeoff roll following engine failure",
      "Engine shutdown after landing",
      "Single-engine go-around",
    ],
    ans: 1,
    exp: "VMCG is the minimum speed at which directional control can be maintained on the ground after critical engine failure, using rudder only (no nosewheel steering).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-8",
    q: "A higher takeoff weight on a twin aeroplane will:",
    opts: [
      "Reduce VMCA",
      "Increase TODR and reduce climb gradient on all engines and OEI",
      "Improve single-engine climb rate",
      "Have no effect on TODR if obstacle-free",
    ],
    ans: 1,
    exp: "Higher weight requires higher rotation speed, longer ground roll, and more thrust to climb — TODR increases and both all-engine and OEI climb gradients decrease.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // nav-9  Flight Planning & Monitoring
  // ══════════════════════════════════════════════════════════════════════════
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-9",
    q: "DGCA rules require a CPL aircraft to carry a minimum fuel reserve of (VFR day flight):",
    opts: [
      "20 minutes at normal cruise",
      "30 minutes at normal cruise",
      "45 minutes at normal cruise",
      "60 minutes at normal cruise",
    ],
    ans: 1,
    exp: "DGCA (aligned with ICAO Annex 6) requires VFR day flights to carry sufficient fuel to reach destination plus a minimum 30-minute fixed reserve at normal cruise power.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-9",
    q: "The fuel required for an IFR flight plan includes (in order of consumption):",
    opts: [
      "Trip fuel + contingency + alternate + final reserve",
      "Trip fuel + reserve only",
      "Block fuel + taxi fuel",
      "Usable fuel + unusable fuel",
    ],
    ans: 0,
    exp: "IFR fuel planning: taxi fuel → trip fuel (destination) → contingency (5% or 5 min) → alternate fuel → final reserve (45 min piston / 30 min turbine) → additional if required.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-9",
    q: "In an ICAO flight plan, field 15 contains:",
    opts: [
      "Departure aerodrome and time",
      "Route (ATC route designators, waypoints, and cruising levels)",
      "Equipment and capabilities",
      "Persons on board",
    ],
    ans: 1,
    exp: "Field 15 is the Route field containing the cruising speed, requested level, and the route including ATC route designators, significant points, and speed/level changes.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-9",
    q: "When is an alternate aerodrome mandatory for IFR flight?",
    opts: [
      "Always",
      "When destination forecast is below alternate minima",
      "Only for international flights",
      "Only when the flight exceeds 3 hours",
    ],
    ans: 1,
    exp: "An alternate is required when the destination forecast (from 1 hr before to 1 hr after ETA) is below alternate minima. If conditions are expected to be suitable, no alternate is required (TEMPO exemption).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-9",
    q: "Contingency fuel is typically calculated as:",
    opts: [
      "5% of trip fuel",
      "10% of block fuel",
      "A fixed 30 minutes",
      "Equal to the alternate fuel",
    ],
    ans: 0,
    exp: "Standard ICAO contingency fuel = 5% of planned trip fuel (or 5 minutes' endurance, whichever is greater) to cover unforecast deviations from planned conditions.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-9",
    q: "ETOPS (Extended Operations) rules apply to twin-engine airliners flying:",
    opts: [
      "Over mountainous terrain",
      "Beyond 60 minutes from a diversion airport at single-engine cruise speed",
      "Only over oceanic areas",
      "Above FL350",
    ],
    ans: 1,
    exp: "ETOPS rules govern operations where the aircraft would be more than a defined diversion time (60 min ETOPS-60, or extended approvals) from a suitable alternate at approved one-engine-inoperative cruise speed.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-9",
    q: "A 'nav log' (flight log) is used to:",
    opts: [
      "Record ATC communications only",
      "Track fuel burn, ETAs, actual times, and position fixes in flight",
      "Log maintenance defects",
      "Satisfy ATC strip requirements",
    ],
    ans: 1,
    exp: "The navigation log records pre-planned tracks, headings, ETAs, actual observations (groundspeed, fuel burn, position fixes), enabling systematic tracking of progress against plan.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-9",
    q: "Minimum Safe Altitude (MSA) published on approach charts is based on:",
    opts: [
      "ATC radar coverage area",
      "25 NM radius from the navaid — 1000 ft clearance over highest obstacle",
      "Transition altitude of the aerodrome",
      "Standard ISA tropopause",
    ],
    ans: 1,
    exp: "MSA is normally based on a 25 NM radius from the reference navaid (ILS/VOR/NDB) for the approach, ensuring 1000 ft obstacle clearance within that area. It provides emergency safety but not necessarily IFR separation.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-9",
    q: "Block fuel is defined as:",
    opts: [
      "Fuel in tanks at engine start",
      "Total fuel loaded = trip + all reserves + taxi fuel",
      "Fuel remaining at destination",
      "Fuel burn from brake release to landing",
    ],
    ans: 1,
    exp: "Block fuel (ramp fuel) = total fuel loaded before engine start, covering: taxi out, trip, contingency, alternate, final reserve, and any additional fuel. Block time = engine start to engine shutdown.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-9",
    q: "If actual fuel burn is higher than planned, the first step is to:",
    opts: [
      "Immediately declare MAYDAY",
      "Check actual vs planned fuel at next fix; consider requesting direct routing or diversion",
      "Increase power to reach destination sooner",
      "Ignore if within 10% of plan",
    ],
    ans: 1,
    exp: "Any fuel discrepancy should be monitored; if the trend continues, request direct routing to reduce trip fuel. Declare minimum fuel or MAYDAY if reserves are threatened. Proactive monitoring avoids emergency.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // nav-10  Radio Navigation Aids
  // ══════════════════════════════════════════════════════════════════════════
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-10",
    q: "A VOR operates in the frequency band:",
    opts: ["190–1750 kHz (LF/MF)", "108–117.95 MHz (VHF)", "960–1215 MHz (UHF)", "75 MHz (VHF)"],
    ans: 1,
    exp: "VOR (VHF Omnidirectional Range) operates in the VHF band between 108 and 117.95 MHz, providing 360 radials referenced to magnetic north.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-10",
    q: "A VOR radial is defined as:",
    opts: [
      "A bearing TO the VOR",
      "A bearing FROM the VOR",
      "The aircraft heading to reach the VOR",
      "A great circle from the VOR",
    ],
    ans: 1,
    exp: "A VOR radial is always measured FROM the station. Radial 090 runs due East of the VOR. To fly TO a VOR, the inbound course equals the reciprocal of the radial.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-10",
    q: "DME (Distance Measuring Equipment) provides:",
    opts: [
      "Bearing from a ground station",
      "Slant range distance to the ground transponder",
      "Aircraft altitude above terrain",
      "Groundspeed only when passing directly overhead",
    ],
    ans: 1,
    exp: "DME measures the slant range (not ground distance) between the aircraft and the ground transponder. Slant range error is negligible at low elevation angles but significant directly overhead.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-10",
    q: "ADF (Automatic Direction Finder) homes to NDB signals and displays:",
    opts: [
      "QDM to the station",
      "Relative bearing — angle between aircraft heading and direction to station",
      "Absolute true bearing to station",
      "Range to the station",
    ],
    ans: 1,
    exp: "The ADF needle points to the NDB and shows relative bearing (RB) — angle clockwise from the aircraft's nose to the NDB. QDM = magnetic heading to the station = aircraft HDG (magnetic) + RB (adjusted for 360°).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-10",
    q: "ILS localiser provides:",
    opts: [
      "Vertical guidance only",
      "Lateral guidance (left/right of runway centreline)",
      "Both lateral and vertical guidance",
      "Distance to runway threshold",
    ],
    ans: 1,
    exp: "The ILS localiser transmits on VHF (108–111.95 MHz) and provides lateral (left/right) deviation guidance for runway centreline alignment. The glide slope provides vertical guidance.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-10",
    q: "The glide slope of a standard ILS is set at:",
    opts: ["1° to 2°", "2.5° to 3.5° (nominal 3°)", "5° to 6°", "Variable per approach"],
    ans: 1,
    exp: "Standard ILS glide slope is nominally 3° (range 2.5°–3.5°). Steeper angles (up to 5.5°) are published for terrain/obstacle clearance at specific airports.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-10",
    q: "GPS RAIM (Receiver Autonomous Integrity Monitoring) is used to:",
    opts: [
      "Improve GPS signal strength",
      "Detect GPS satellite faults that could cause position errors",
      "Provide vertical guidance",
      "Correct for magnetic variation",
    ],
    ans: 1,
    exp: "RAIM uses redundant satellite geometry to self-monitor GPS integrity. If a satellite fault is detected, RAIM alerts the pilot — critical for IFR navigation where integrity is required.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-10",
    q: "NDB (Non-Directional Beacon) transmits in the:",
    opts: ["VHF band (108–136 MHz)", "LF/MF band (190–1750 kHz)", "UHF band (960–1215 MHz)", "HF band (3–30 MHz)"],
    ans: 1,
    exp: "NDBs operate in the Low Frequency / Medium Frequency band (190–1750 kHz). The lower frequency allows longer range and bending over terrain but makes them susceptible to static and night effect.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-10",
    q: "Line-of-sight (LoS) limitation applies to which navigation aids?",
    opts: ["NDB and ADF", "VOR, DME, and ILS", "HF radio beacons", "Loran-C"],
    ans: 1,
    exp: "VHF/UHF navigation aids (VOR, DME, ILS, TACAN) are limited to line-of-sight. Coverage range = 1.25 × √(altitude in feet) NM approximately. LF/MF aids like NDBs are not LoS-limited.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-10",
    q: "The CDI (Course Deviation Indicator) on a VOR shows full-scale deflection at:",
    opts: ["5°", "10°", "15°", "20°"],
    ans: 1,
    exp: "Standard VOR CDI full-scale deflection = ±10° from the selected course. Each dot represents approximately 2°. When flying an ILS localiser, full-scale = ±2.5° (more sensitive).",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // nav-11  Flight Instruments
  // ══════════════════════════════════════════════════════════════════════════
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-11",
    q: "The altimeter measures altitude by sensing:",
    opts: [
      "Total air pressure",
      "Static atmospheric pressure",
      "Dynamic pressure (pitot minus static)",
      "Air temperature and density",
    ],
    ans: 1,
    exp: "The altimeter is an aneroid barometer that measures static atmospheric pressure. As altitude increases, static pressure decreases — the instrument converts this pressure to an altitude readout.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-11",
    q: "Setting 1013.25 hPa on the altimeter sub-scale gives:",
    opts: ["Altitude above aerodrome level (AAL)", "Height above MSL (QNH)", "Pressure altitude", "True altitude"],
    ans: 2,
    exp: "With 1013.25 hPa (standard pressure) set, the altimeter reads pressure altitude — used above the transition altitude for vertical separation in the flight levels.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-11",
    q: "The Airspeed Indicator (ASI) measures:",
    opts: [
      "Static pressure",
      "Dynamic pressure (pitot minus static)",
      "Total pressure only",
      "Wind velocity relative to ground",
    ],
    ans: 1,
    exp: "The ASI measures dynamic (impact) pressure = Pitot total pressure − static pressure. It converts this to an airspeed readout. It indicates IAS; TAS requires density correction.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-11",
    q: "The Vertical Speed Indicator (VSI) operates by:",
    opts: [
      "Measuring pitot pressure change rate",
      "Comparing static pressure through a calibrated leak to a reference capsule",
      "Gyroscopic precession sensing vertical velocity",
      "GPS altitude rate of change",
    ],
    ans: 1,
    exp: "The VSI (or variometer) measures the rate of change of static pressure. Static pressure feeds into a capsule directly and through a calibrated metered leak to a case — the pressure difference indicates climb/descent rate.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-11",
    q: "A blocked pitot tube (but open static) will cause the ASI to:",
    opts: [
      "Read zero",
      "Stick at last speed in level flight; indicate climb if climbing, descent if descending",
      "Over-read in a climb",
      "Under-read in a descent",
    ],
    ans: 1,
    exp: "With a blocked pitot, the trapped pressure acts like an altimeter. If altitude stays the same, IAS appears fixed. In a climb, static pressure falls → ASI over-reads (shows increase). In descent, under-reads.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-11",
    q: "The Attitude Indicator (Artificial Horizon) uses:",
    opts: [
      "A pendulum to detect gravity",
      "A gyroscope with its spin axis vertical (Earth gyro)",
      "Accelerometers only",
      "GPS attitude data",
    ],
    ans: 1,
    exp: "The AI uses a gyroscope spinning with its axis vertical (tied to gravity through pendulous vanes or erection mechanism), maintaining a stable horizon reference regardless of aircraft manoeuvre.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-11",
    q: "The Directional Gyro (Heading Indicator) requires periodic realignment because:",
    opts: [
      "It is affected by compass deviation",
      "Gyroscopic rigidity causes apparent drift due to Earth's rotation and real precession",
      "It aligns to magnetic north automatically",
      "Temperature causes calibration error",
    ],
    ans: 1,
    exp: "The HI/DG is subject to apparent drift (Earth's rotation makes the gyro appear to drift) and real precession (friction). It must be realigned to the magnetic compass every 10–15 minutes.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-11",
    q: "A turn coordinator (TC) indicates:",
    opts: [
      "Rate of turn and bank angle only",
      "Rate of turn and slip/skid via ball",
      "Attitude in pitch and roll",
      "Heading and rate of heading change",
    ],
    ans: 1,
    exp: "The turn coordinator uses a gyro to sense rate of roll and yaw, displaying the rate of turn. The ball (inclinometer) indicates slip (too much rudder away from turn) or skid (too little rudder).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-11",
    q: "A standard rate turn is:",
    opts: ["1°/sec (360° in 6 min)", "3°/sec (360° in 2 min)", "6°/sec (360° in 1 min)", "2°/sec (360° in 3 min)"],
    ans: 1,
    exp: "Standard rate (Rate 1) turn = 3°/second = 180° in 1 minute = 360° in 2 minutes. Used in IFR holds and procedure turns. Bank angle for Std Rate ≈ TAS/10 + 7°.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-11",
    q: "The static vent is blocked in flight. Which instruments are most directly affected?",
    opts: [
      "Attitude indicator and heading indicator",
      "Altimeter, VSI, and ASI",
      "Turn coordinator only",
      "Magnetic compass only",
    ],
    ans: 1,
    exp: "A blocked static vent deprives the altimeter, VSI, and ASI of updated static pressure reference — all three will freeze at the values when the blockage occurred (altimeter and VSI freeze; ASI may over/under read).",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // nav-12  Power Plant Instruments & Avionics
  // ══════════════════════════════════════════════════════════════════════════
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-12",
    q: "EGT (Exhaust Gas Temperature) gauge monitors engine health by measuring:",
    opts: [
      "Carburetor inlet temperature",
      "Turbine/exhaust temperature to prevent overheating and optimise fuel/air mixture",
      "Oil temperature at the sump",
      "Cylinder head temperature at the exhaust valve only",
    ],
    ans: 1,
    exp: "EGT helps set the fuel/air mixture: peak EGT corresponds to stoichiometric mixture. Leaning past peak EGT without care can overheat cylinders. It also detects exhaust system faults.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-12",
    q: "CHT (Cylinder Head Temperature) is used to:",
    opts: [
      "Measure intake air temperature for density altitude",
      "Monitor engine cooling and ensure CHT remains within limits to prevent detonation and preignition",
      "Control the carburettor heat",
      "Trigger the fire warning system",
    ],
    ans: 1,
    exp: "CHT monitors how well the engine is being cooled. Excessive CHT causes detonation, pre-ignition, and engine damage. Normal cooling is managed by airspeed, power setting, and cowl flaps.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-12",
    q: "Oil pressure gauge reads zero in flight. The correct action is:",
    opts: [
      "Continue — it may be an instrument fault",
      "Reduce power, prepare for engine failure, land at the nearest suitable aerodrome",
      "Increase engine RPM to restore oil circulation",
      "Check oil temperature only — pressure loss is secondary",
    ],
    ans: 1,
    exp: "Zero oil pressure is a critical emergency — indicates imminent or actual oil starvation. Reduce power immediately to reduce bearing loads, declare emergency, and land as soon as possible.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-12",
    q: "A transponder squawking 7700 indicates:",
    opts: ["Radio failure", "Unlawful interference (hijack)", "General emergency", "VFR flight"],
    ans: 2,
    exp: "Transponder codes: 7700 = General Emergency, 7600 = Radio Failure (NORDO), 7500 = Unlawful Interference. 1200 is used for VFR in the USA; India uses allocated codes for VFR.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-12",
    q: "Mode C transponder provides ATC with:",
    opts: [
      "Aircraft identification only",
      "Aircraft identification and pressure altitude",
      "GPS position",
      "Groundspeed and track",
    ],
    ans: 1,
    exp: "Mode A provides a 4-digit squawk code (identification). Mode C adds pressure altitude information encoded in the reply. Mode S provides selective interrogation and enhanced data including identity and altitude.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-12",
    q: "The manifold pressure (MAP) gauge in a piston aircraft measures:",
    opts: [
      "Total engine pressure ratio",
      "Absolute pressure in the engine intake manifold",
      "Boost pressure above ambient only",
      "Fuel pressure at the carburettor",
    ],
    ans: 1,
    exp: "MAP gauge measures absolute pressure in the induction manifold (inches of mercury or hPa). It is the primary power setting indicator for non-constant-speed propeller and some constant-speed piston engines.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-12",
    q: "TCAS II (Traffic Collision Avoidance System) provides:",
    opts: [
      "Traffic Advisory (TA) only",
      "Traffic Advisory (TA) and Resolution Advisory (RA) with vertical escape manoeuvre guidance",
      "Lateral avoidance manoeuvres",
      "ATC-coordinated conflict alerts only",
    ],
    ans: 1,
    exp: "TCAS II provides both TAs (traffic within ~40 sec) and RAs (resolution advisories — CLIMB or DESCEND commands 20–35 sec before predicted collision). RAs must be followed immediately, overriding ATC instructions.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-12",
    q: "The purpose of the fuel flowmeter in a piston aircraft is to:",
    opts: [
      "Measure fuel quantity in each tank",
      "Indicate fuel consumption rate to allow fuel management and cross-check tank contents",
      "Control the mixture automatically",
      "Trigger the fuel pump warning",
    ],
    ans: 1,
    exp: "The fuel flowmeter shows instantaneous fuel burn rate (litres/hour or lb/hr). Used with fuel quantity gauges, it allows pilots to predict remaining endurance and detect abnormal consumption.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-12",
    q: "ADS-B (Automatic Dependent Surveillance – Broadcast) differs from transponder-based Mode C in that it:",
    opts: [
      "Requires active interrogation from a ground radar",
      "Broadcasts GPS position, identity, and velocity without interrogation",
      "Only works below FL180",
      "Provides ground proximity warning",
    ],
    ans: 1,
    exp: "ADS-B Out continuously broadcasts GPS-derived position, altitude, velocity, and identity without needing radar interrogation. ADS-B In receives broadcasts from other aircraft for CDTI situational awareness.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-12",
    q: "An aircraft experiences a sudden rise in oil temperature with normal oil pressure. The likely cause is:",
    opts: [
      "Oil starvation",
      "Partially blocked oil cooler or excessive engine load",
      "Fuel contamination",
      "EGT sensor failure",
    ],
    ans: 1,
    exp: "High oil temperature with normal pressure typically indicates inadequate cooling — blocked oil cooler, low airspeed (taxiing in hot weather), or high power setting. Reduce power and increase airspeed; check cowl flaps.",
  },
];
