import type { DemoQuestion } from "./demo-questions";

export const OXFORD_NAV_QUESTIONS: DemoQuestion[] = [
  // === nav-1: Basics of Navigation ===

  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "What is the approximate compression (flattening) of the Earth?",
    opts: ["3%", "0.03%", "0.3%", "1/3000"],
    ans: 2,
    exp: "The Earth's compression (ellipticity) is approximately 1/297, which is about 0.3%. This means the polar radius is slightly less than the equatorial radius.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "A Graticule is the name given to:",
    opts: [
      "A series of lines drawn on a chart",
      "A series of Latitude and Longitude lines drawn on a chart or map",
      "A selection of small circles as you get nearer to either pole",
      "The intersection of rhumb lines on a Mercator chart",
    ],
    ans: 1,
    exp: "The graticule is specifically the network of latitude and longitude lines (parallels and meridians) drawn on a chart or map, forming the geographic reference grid.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "Given that the compression value of the Earth is 1/297 and that the semi-major axis measured at the Equator is 6378.4 km, what is the semi-minor axis measured at the Poles?",
    opts: ["6399.9 km", "6356.9 km", "6378.4 km", "6367.0 km"],
    ans: 1,
    exp: "The polar radius = equatorial radius × (296/297) = 6378.4 × 0.99663 ≈ 6356.9 km. The Earth is slightly flattened at the poles.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "An ICAO nautical mile is defined as:",
    opts: ["6080 feet", "1852 metres", "1863 feet", "6062 feet"],
    ans: 1,
    exp: "The international (ICAO) nautical mile is defined as exactly 1852 metres. This replaced the older UK definition of 6080 feet.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "The circumference of the Earth is approximately:",
    opts: ["43200 NM", "10800 NM", "21600 NM", "5400 NM"],
    ans: 2,
    exp: "The distance from Equator to Pole is 90° × 60 NM = 5400 NM. The full circumference = 4 × 5400 = 21600 NM (360° × 60 NM/degree).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "Any Meridian Line is a:",
    opts: [
      "Rhumb Line",
      "Semi Great Circle",
      "Rhumb Line and a semi Great Circle",
      "Small circle",
    ],
    ans: 2,
    exp: "Every meridian is both a semi-great circle (it forms half of a great circle with its anti-meridian) and a rhumb line (it cuts all parallels at 90°, a constant angle).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "A Rhumb Line cuts all meridians at the same angle. This gives:",
    opts: [
      "The shortest distance between two points",
      "A line which could never be a Great Circle track",
      "A line of constant direction",
      "A line always curving towards the equator",
    ],
    ans: 2,
    exp: "The defining property of a rhumb line is that it crosses all meridians at the same angle, giving a line of constant (unchanging) direction — very useful for compass navigation.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "What is the position of the Rhumb Line between two points relative to the Great Circle between the same points if the points are in the Northern hemisphere?",
    opts: [
      "The rhumb line lies south of (nearer the equator than) the great circle",
      "The rhumb line lies north of (nearer the pole than) the great circle",
      "They are the same line",
      "The rhumb line lies east of the great circle",
    ],
    ans: 0,
    exp: "In the Northern hemisphere, the great circle curves toward the pole (northward), so it always lies closer to the pole than the rhumb line. The rhumb line lies nearer the equator.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "What is the maximum difference between geodetic and geocentric latitude?",
    opts: ["At 45° North and South", "At 90° North and South", "At 60° North and South", "At 0° (Equator)"],
    ans: 0,
    exp: "The difference between geodetic latitude (measured from the normal to the ellipsoid) and geocentric latitude (measured from Earth's centre) is maximum at about 45° latitude, where it reaches approximately 11.5 arc minutes.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "Departure is defined as:",
    opts: [
      "The great circle distance between two points on the same meridian",
      "The distance between two meridians along a specified parallel of latitude",
      "The departure angle from a runway heading",
      "The change in longitude converted to nautical miles",
    ],
    ans: 1,
    exp: "Departure is the east-west distance between two meridians measured along a specified parallel of latitude, expressed in nautical miles. It equals change-of-longitude (in minutes) × cosine latitude.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "Departure varies with latitude as the:",
    opts: ["Sine of the latitude", "Cosine of the latitude", "Tangent of the latitude", "Secant of the latitude"],
    ans: 1,
    exp: "Departure = change of longitude (minutes) × cosine latitude. Departure is maximum at the equator (cos 0° = 1) and zero at the poles (cos 90° = 0), varying as the cosine of latitude.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "At what latitude is the departure between two meridians equal to half their difference of longitude in minutes?",
    opts: ["0° (Equator)", "30° N/S", "45° N/S", "60° N/S"],
    ans: 3,
    exp: "Departure = ch.long (min) × cos lat. For departure to equal half the ch.long, cos lat must equal 0.5, which occurs at 60° N or S.",
  },

  // === nav-2: Magnetism & Compasses ===

  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "The sensitivity of a direct reading magnetic compass is:",
    opts: [
      "Inversely proportional to the horizontal component of the Earth's magnetic field",
      "Proportional to the horizontal component of the Earth's magnetic field",
      "Inversely proportional to the vertical component of the Earth's magnetic field",
      "Inversely proportional to both the vertical and horizontal components",
    ],
    ans: 1,
    exp: "Compass sensitivity depends on the horizontal component H of the Earth's field. A stronger H means a stronger directive force aligning the compass needle — greater sensitivity.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "What is the definition of magnetic variation?",
    opts: [
      "The angle between the direction indicated by a compass and Magnetic North",
      "The angle between True North and Compass North",
      "The angle between Magnetic North and True North",
      "The angle between Magnetic Heading and Magnetic North",
    ],
    ans: 2,
    exp: "Variation is the angle at a point between True North and the direction of the Earth's magnetic field (Magnetic North). It is named East or West depending on whether Magnetic North lies east or west of True North.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "At the magnetic equator:",
    opts: [
      "Dip is zero",
      "Variation is zero",
      "Deviation is zero",
      "The isogonal is an agonic line",
    ],
    ans: 0,
    exp: "The magnetic equator (also called the aclinic line) is defined as the line joining all points of zero magnetic dip. Variation and deviation may still have non-zero values at the magnetic equator.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "Which of these is a correct statement about the Earth's magnetic field?",
    opts: [
      "It acts as though there is a large blue magnetic pole in Northern Canada",
      "The angle of dip is the angle between the vertical and the total magnetic force",
      "It may be temporary, transient, or permanent",
      "It has no effect on aircraft deviation",
    ],
    ans: 0,
    exp: "The Earth's field behaves as if a large bar magnet were embedded in the Earth, with the blue (south-seeking) end of this imaginary magnet located near the geographic North Pole region (Northern Canada). Blue poles attract the red (north-seeking) end of compass needles.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "Where is a compass most effective?",
    opts: [
      "About midway between the Earth's magnetic poles",
      "In the region of the magnetic South Pole",
      "In the region of the magnetic North Pole",
      "On the geographic equator",
    ],
    ans: 0,
    exp: "The compass is most effective where the horizontal component H of the Earth's field is largest — this is approximately midway between the magnetic poles, near the magnetic equator where the field is most horizontal.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "The value of magnetic variation on a chart changes with time. This is due to:",
    opts: [
      "Movement of the magnetic poles, causing an increase",
      "Increase in the magnetic field, causing an increase",
      "Reduction in the magnetic field, causing a decrease",
      "Movement of the magnetic poles, which can cause either an increase or a decrease",
    ],
    ans: 3,
    exp: "The magnetic poles move over time (secular variation). Depending on the direction of that movement relative to a given location, the local variation value can either increase or decrease.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "The agonic line:",
    opts: [
      "Is midway between the magnetic North and South poles",
      "Follows the geographic equator",
      "Is the shorter distance between the respective True and Magnetic North and South poles",
      "Follows separate paths out of the North polar regions, one currently running through Western Europe and the other through the USA",
    ],
    ans: 3,
    exp: "The agonic line is the isogonal (line of equal variation) where variation = 0. It does not follow a simple geometric path but snakes across the Earth, currently running in two main branches — one through the Americas and one through Europe.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "What is the maximum possible value of dip angle?",
    opts: ["66°", "180°", "90°", "45°"],
    ans: 2,
    exp: "Magnetic dip is the angle between the horizontal and the Earth's total magnetic field. At the magnetic poles, the field is completely vertical, giving a dip of 90°. This is the maximum possible value.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "What is the dip angle at the South Magnetic Pole?",
    opts: ["0°", "90°", "180°", "64°"],
    ans: 1,
    exp: "At a magnetic pole, the Earth's total magnetic field is directed vertically — straight into or out of the Earth. The dip angle is therefore 90° at either magnetic pole.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "What is a line of equal magnetic variation?",
    opts: ["An isocline", "An isogonal", "An isogriv", "An isovar"],
    ans: 1,
    exp: "An isogonal is a line drawn on a chart joining all places of equal magnetic variation. The special case where variation = 0 is called the agonic line.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "Isogonal lines converge at:",
    opts: [
      "The North Magnetic Pole only",
      "The North and South Magnetic and both Geographical Poles",
      "The North and South Magnetic Poles",
      "The Magnetic equator",
    ],
    ans: 2,
    exp: "Isogonals (lines of equal variation) are defined by reference to Magnetic North. They therefore converge at the North and South Magnetic Poles, not at the geographic poles.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "If variation is West, then:",
    opts: [
      "True North is West of Magnetic North",
      "Compass North is West of Magnetic North",
      "True North is East of Magnetic North",
      "Magnetic North is West of Compass North",
    ],
    ans: 0,
    exp: "Variation West means Magnetic North is displaced west of True North — equivalently, True North lies to the EAST of Magnetic North. The mnemonic is 'Variation West — Magnetic Best' (magnetic heading is greater than true).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "European regulations (CS OPS-1) state that the maximum permissible residual deviation after compensation for the Direct Reading Compass is:",
    opts: ["10 degrees", "3 degrees", "1 degree", "2 degrees"],
    ans: 0,
    exp: "Under CS OPS-1 (European aviation regulations), the direct reading magnetic compass must be within ±10° after compensation on any heading. This is the accuracy limit for the standby compass.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "The aim of a compass swing is:",
    opts: [
      "Only to find deviation on the cardinal headings and calculate coefficients",
      "Only to record residual deviation and prepare a compass correction card",
      "To find deviation, eliminate or reduce coefficients, and record residual deviation",
      "None of the above",
    ],
    ans: 2,
    exp: "A compass swing has three aims: (1) observe deviation and calculate coefficients A, B, C; (2) correct/reduce those coefficients; and (3) record residual deviation on a deviation card for use by the pilot.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "Aircraft magnetism caused by vertical soft iron (VSI):",
    opts: [
      "Varies with magnetic heading but not with magnetic latitude",
      "Varies with magnetic latitude but not with heading",
      "Is not affected by magnetic latitude or heading",
      "Varies as the cosine of the compass heading",
    ],
    ans: 1,
    exp: "VSI magnetism is induced by the vertical component Z of the Earth's field. Z varies with magnetic latitude (zero at the equator, maximum at the poles) but is constant for a given latitude regardless of heading.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "Deviation due to coefficient A is mainly caused by:",
    opts: [
      "Hard iron force acting along the longitudinal axis",
      "Hard and soft iron forces acting along the lateral axis",
      "Vertical soft iron forces",
      "A misaligned lubber line",
    ],
    ans: 3,
    exp: "Coefficient A represents a constant deviation on all headings, and is mainly caused by a mechanical misalignment of the lubber line relative to the fore-aft axis of the aircraft. It is corrected by rotating the compass body.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-2",
    q: "What is a line of equal grivation called?",
    opts: ["An isocline", "An isogonal", "An isogriv", "An isovar"],
    ans: 2,
    exp: "An isogriv is a line on a chart joining all positions of equal grivation (the algebraic sum of variation and grid convergence). Isogrivs are plotted on gridded navigation charts.",
  },

  // === nav-3: Aeronautical Charts ===

  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "You are flying a VFR route and have become uncertain of your position. Which is the best course of action?",
    opts: [
      "Set heading towards a line feature — coastline, river or motorway",
      "Turn round and fly your flight plan tracks in reverse until you see something you recognised",
      "Fly a series of ever-expanding circles from your present position",
      "Turn round and fly your flight plan in reverse back to base",
    ],
    ans: 0,
    exp: "The correct lost procedure is to maintain contact with the ground and head for a recognisable line feature (coastline, motorway, major river). Once you reach it, you can follow it to a known point and resume navigation.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "An aircraft flying VFR using visual navigation crosses two parallel roads at right angles to the track. For what purpose could that information be used?",
    opts: [
      "Tracking check",
      "Ground speed check",
      "Heading check",
      "Deviation check",
    ],
    ans: 1,
    exp: "The time taken to travel between two parallel roads (of known spacing) at right angles to track gives the aircraft's ground speed. This is not useful for track checking because roads crossed at right angles give no tracking information.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "Which of the following would be most useful as a visual checkpoint when planning a flight?",
    opts: [
      "A small copse",
      "A large wood",
      "A large motorway junction",
      "A bend in a river",
    ],
    ans: 2,
    exp: "A large motorway junction is ideal because it is unique (no two junctions look alike), large (visible from altitude), has good contrast, and can be identified from a distance. A small copse may be too small; woods and river bends may not be unique.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "Scale is the relationship between:",
    opts: [
      "The latitude and longitude on the chart",
      "The length of a line on the chart and the distance on the Earth between the same two points",
      "The size of the chart and the area of the country",
      "The contours and the relief features shown",
    ],
    ans: 1,
    exp: "Scale = Chart Length / Earth Distance. It is always expressed with chart length as 1 (the Representative Fraction), and tells you how many units on Earth are represented by one unit on the chart.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "Which of the following is a LARGE scale chart?",
    opts: [
      "A world atlas (1:50,000,000)",
      "An ICAO 1:500,000 topographical chart",
      "A 1:5,000,000 small-scale en-route chart",
      "A chart covering the whole of Europe on one sheet",
    ],
    ans: 1,
    exp: "A large scale chart has more detail but covers less area. The 1:500,000 chart (smaller denominator) covers a smaller geographic area in greater detail than a 1:5,000,000 chart. Large scale = smaller denominator = more detail.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "Convergency (Earth convergence) is defined as:",
    opts: [
      "The angle between a great circle track and a rhumb line track",
      "The angle of inclination between two selected meridians measured at a given latitude",
      "The angle at which the great circle crosses the equator",
      "Half the difference between the initial and final great circle track",
    ],
    ans: 1,
    exp: "Convergency is the angle of inclination between two selected meridians measured at a given latitude. Formula: Convergency = Change in Longitude × sine (latitude). It equals zero at the equator and equals the change in longitude at the poles.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "Conversion angle is:",
    opts: [
      "Equal to convergency",
      "Half the convergency",
      "Twice the convergency",
      "Equal to the change of longitude",
    ],
    ans: 1,
    exp: "Conversion angle = ½ convergency = ½ × change of longitude × sine (mean latitude). It is the angular difference between the great circle direction and the rhumb line direction between two points.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "On a Mercator chart, the chart convergence is:",
    opts: [
      "Equal to Earth convergency everywhere",
      "Zero everywhere (constant across the chart)",
      "Correct at the standard parallels",
      "Equal to change of longitude × sine of latitude",
    ],
    ans: 1,
    exp: "On a Mercator chart, all meridians are drawn as parallel vertical lines, so their angle of inclination (chart convergence) is zero everywhere. Earth convergency is only zero at the equator — so Mercator chart convergence matches Earth convergency only at the equator.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "On a direct Mercator chart, rhumb lines are represented as:",
    opts: [
      "Curves concave to the Equator",
      "Curves convex to the Equator",
      "Complex curves",
      "Straight lines",
    ],
    ans: 3,
    exp: "The Mercator chart was specifically designed so that a straight line is a rhumb line (constant direction). This makes compass navigation straightforward — draw a straight line, measure the angle, and fly that constant heading.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "On a direct Mercator, with the exception of the meridians and the Equator, great circles are represented as:",
    opts: [
      "Curves concave to the nearer pole",
      "Curves convex to the Equator",
      "Curves concave to the Equator",
      "Straight lines",
    ],
    ans: 2,
    exp: "On a Mercator, great circles (other than meridians and the equator) appear as curves that bulge toward the equator — i.e. they are concave to the equator (or convex toward the nearer pole). The great circle always lies closer to the pole than the rhumb line.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "A normal Mercator chart is which type of projection?",
    opts: [
      "Cylindrical, perspective, and conformal",
      "Perspective, conformal, and conical",
      "Cylindrical, non-perspective, and conformal",
      "Non-perspective, conformal, and azimuthal",
    ],
    ans: 2,
    exp: "The Mercator chart is a cylindrical projection (based on a cylinder tangent at the equator), non-perspective (mathematically adjusted from the geometric projection), and conformal/orthomorphic (angles preserved locally).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "On a Mercator chart, scale:",
    opts: [
      "Is constant everywhere",
      "Is correct at the equator and expands as the secant of the latitude",
      "Is correct at the standard parallels",
      "Contracts away from the equator",
    ],
    ans: 1,
    exp: "Mercator scale is correct (matching the Reduced Earth) only at the equator. Away from the equator, scale expands proportionally to the secant of the latitude: Scale at lat = Scale at equator × sec(lat).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "On a Lambert's conformal conic chart, scale is:",
    opts: [
      "Constant everywhere",
      "Constant along a meridian of longitude",
      "Slightly variable with latitude; constant along a parallel of latitude",
      "Correct at the parallel of tangency and expands on either side",
    ],
    ans: 2,
    exp: "On a Lambert chart, scale is constant along any parallel of latitude but varies slightly with latitude. Scale is correct on the two standard parallels and slightly contracted between them and slightly expanded outside them.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "The convergence factor (constant of the cone) on a Lambert's conformal conic chart with standard parallels at 63°N and 41°N is:",
    opts: ["0.891", "0.788", "0.656", "0.707"],
    ans: 1,
    exp: "The constant of the cone = sine of the parallel of origin (midway between the standard parallels). Parallel of origin = (63+41)/2 = 52°N. Sin 52° ≈ 0.788.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "On which chart projection is it not possible to show the North Pole?",
    opts: ["Direct Mercator", "Lambert's conformal conic", "Transverse Mercator", "Polar stereographic"],
    ans: 0,
    exp: "On a direct Mercator chart, scale expands as the secant of latitude, becoming infinite at the poles. The poles can therefore never be shown on a direct Mercator chart.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "The chart convergence factor on a Polar Stereographic chart is:",
    opts: ["0", "1.0", "0.866", "0.5"],
    ans: 1,
    exp: "On a Polar Stereographic chart, the chart convergence = change of longitude × 1.0. The n factor (constant of the cone) is 1, meaning meridians on the chart subtend the same angle as on the Earth at the pole.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "The chart that is generally used for navigation in polar areas is based on a:",
    opts: [
      "Direct Mercator projection",
      "Gnomonic projection",
      "Lambert conformal projection",
      "Stereographic projection",
    ],
    ans: 3,
    exp: "The Polar Stereographic chart is the standard chart used for navigation in polar regions. It is an azimuthal projection centered on the pole, conformal (orthomorphic), and great circles near the pole approximate straight lines.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "How do rhumb lines (other than meridians) appear on a Polar Stereographic chart?",
    opts: [
      "Concave to the nearer pole",
      "Convex to the nearer pole (curves spiraling away from pole)",
      "Ellipses round the pole",
      "Straight lines",
    ],
    ans: 1,
    exp: "On a Polar Stereographic chart, rhumb lines (except meridians) appear as curves that are convex toward the pole — they spiral outward from the pole. Great circles appear as curves concave to the pole but with less curvature than rhumb lines.",
  },

  // === nav-4: Dead Reckoning (Triangle of Velocities) ===

  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-4",
    q: "The Triangle of Velocities has three vectors. They are:",
    opts: [
      "Heading, track, and drift",
      "Air vector (heading/TAS), wind vector (wind direction/speed), and ground vector (track/GS)",
      "True heading, magnetic heading, and compass heading",
      "TAS, GS, and wind component",
    ],
    ans: 1,
    exp: "The three vectors of the triangle of velocities are: (1) the air vector — the direction and speed of the aircraft through the air (heading + TAS); (2) the wind vector — the direction and speed the air is moving (W/V); and (3) the ground vector — the resulting direction and speed over the ground (track + GS).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-4",
    q: "Drift is defined as:",
    opts: [
      "The angle between True North and the aircraft's track",
      "The angle between the aircraft's heading and the aircraft's track",
      "The angle between the track made good and the planned track",
      "The wind's angular effect on compass heading",
    ],
    ans: 1,
    exp: "Drift is the angle between the aircraft's heading (the direction the nose is pointing) and the track (the direction the aircraft is actually moving over the ground). Port (left) drift means track is to the left of heading.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-4",
    q: "An aircraft is climbing at a constant CAS in ISA conditions. What will be the effect on TAS and Mach Number?",
    opts: [
      "TAS increases and Mach Number decreases",
      "Both increase",
      "Both decrease",
      "TAS decreases and Mach Number increases",
    ],
    ans: 1,
    exp: "At constant CAS, TAS increases with altitude as air density decreases. Temperature also falls with altitude in ISA, reducing the speed of sound. Since TAS increases AND speed of sound decreases, Mach Number (TAS/LSS) increases even more steeply. Both TAS and Mach Number increase.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-4",
    q: "What will be the effect on Mach Number and TAS if an aircraft flies at constant Mach Number while climbing?",
    opts: [
      "TAS remains constant; Mach Number decreases",
      "TAS decreases; Mach Number remains constant",
      "TAS increases; Mach Number remains constant",
      "Both remain constant",
    ],
    ans: 1,
    exp: "At constant Mach Number, TAS = Mach × LSS. As altitude increases in ISA, temperature (and therefore LSS) decreases, so TAS must decrease. Mach Number is held constant by the assumption.",
  },

  // === nav-5: In-Flight Navigation (1-in-60 rule) ===

  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "Track Error Angle is:",
    opts: [
      "The same as drift",
      "The angle between the planned track and the heading being flown",
      "The angle between the planned track and the track made good",
      "The angle between the heading and Magnetic North",
    ],
    ans: 2,
    exp: "Track Error Angle (TEA) is the angle between the planned track and the track actually made good (TMG). It is NOT the same as drift (which is the angle between heading and track). TEA = difference between planned track direction and TMG direction.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "You are flying from A to B. You find that your position is 60 NM outbound from A and 7 NM left of the required track. What is your track error angle?",
    opts: ["3°L", "4°L", "7°L", "9°L"],
    ans: 2,
    exp: "Using the 1-in-60 rule: Track Error Angle = (distance off track / distance gone) × 60 = (7/60) × 60 = 7°. The aircraft is 7° left of the required track.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "You are flying from G to H. Your position is 30 NM outbound from G and 4 NM left of the required track. What is your track error angle?",
    opts: ["4°L", "6°L", "8°L", "10°L"],
    ans: 2,
    exp: "Track Error Angle = (4/30) × 60 = 8°. The 1-in-60 rule states that 1 NM off track in 60 NM along track equals 1° of track error.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "You are flying from A to B on a required track of 045°(T). Your position is 80 NM outbound from A and 4 NM left of the required track. What is your track made good?",
    opts: ["038°(T)", "042°(T)", "048°(T)", "052°(T)"],
    ans: 1,
    exp: "TEA = (4/80) × 60 = 3°. The aircraft is 3° left of track, so the TMG = 045° - 3° = 042°(T).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "You are on an ILS 3° glide slope. Your DME range is 25 NM from the threshold. What is your height above the runway threshold elevation? (Use 1-in-60 rule, 6000 ft = 1 NM)",
    opts: ["8010 feet", "7450 feet", "6450 feet", "7550 feet"],
    ans: 0,
    exp: "At 3° slope, height per NM = 3 × 100 ft = 300 ft/NM (from 1-in-60). At 25 NM: 25 × 300 = 7500 ft. Add 50 ft threshold height = 7550... but the precise formula gives 25 × 6000 × 3/60 = 7500, plus 50 ft threshold crossing height ≈ 7550 ft. The best answer accounting for the actual 1-in-60 geometry is 8010 ft (from the exact trig: 25 NM × 6000 × tan 3° ≈ 7854 ft + 50 ft = 7904 ft, nearest answer 8010).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "You are flying from Q to R on a required track of 125°(T). Your position is 40 NM from R and 2 NM left of the required track. What track must you fly to arrive overhead R?",
    opts: ["122°(T)", "125°(T)", "128°(T)", "131°(T)"],
    ans: 2,
    exp: "Closing angle = (2/40) × 60 = 3°. To fly directly to R you must add the closing angle to the required track (since you are left of track, turn right): 125° + 3° = 128°(T).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "By what amount must you change your rate of descent given a 10-knot increase in headwind on a 3° glide slope?",
    opts: ["50 ft/min increase", "30 ft/min increase", "50 ft/min decrease", "30 ft/min decrease"],
    ans: 2,
    exp: "On a 3° glide slope, for every 1 knot change in ground speed, ROD changes by about 5 ft/min (100 ft per NM × 3°/60 min at 1 knot ≈ 5 ft/min). A 10-knot headwind increase REDUCES ground speed by 10 knots, so ROD must DECREASE by 10 × 5 = 50 ft/min to remain on slope.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "An aircraft has planned to fly from A to B, a total distance of 135 NM. After flying 45 NM the aircraft is 3 NM left of the planned track. Using the 1-in-60 rule, what would be the alteration of heading to fly directly to B?",
    opts: ["6° right", "4° right", "8° right", "4° left"],
    ans: 0,
    exp: "TEA = (3/45) × 60 = 4°. Distance remaining = 90 NM. Closing angle = (3/90) × 60 = 2°. Total heading change = TEA + CA = 4° + 2° = 6° right.",
  },

  // === nav-1 continued: Time topics ===

  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "When does perihelion (Earth closest to the Sun) occur?",
    opts: ["Early January", "Mid March", "Early July", "September 21"],
    ans: 0,
    exp: "Perihelion occurs around January 4th each year, when the Earth is at its closest point to the Sun in its elliptical orbit. Aphelion (furthest from Sun) occurs around July 4th.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "When do the equinoxes occur?",
    opts: ["December and June", "February and November", "March and September", "January and July"],
    ans: 2,
    exp: "The equinoxes occur around 21 March (Spring/Vernal equinox in NH) and 21 September (Autumn equinox in NH). At these times the Sun is overhead the equator and day and night are approximately equal length globally.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "When it is the Winter Solstice in the Southern hemisphere, the Declination of the Sun is:",
    opts: ["0°N/S", "23.5°N", "66.5°N", "23.5°S"],
    ans: 1,
    exp: "The Southern hemisphere Winter Solstice is the same date as the Northern hemisphere Summer Solstice (around June 21). At this time the Sun's declination is 23.5°N — the Sun is overhead the Tropic of Cancer.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "What is the angle between the plane of the Equator (Equinoctial) and the plane of the Ecliptic?",
    opts: ["66.5°", "23.5°", "Varies between 23.5°N and 23.5°S", "Varies between 66.5°N and 66.5°S"],
    ans: 1,
    exp: "The Earth's axis is tilted 23.5° from the perpendicular to its orbital plane. This means the plane of the equator is inclined at 23.5° to the plane of the ecliptic (Earth's orbital plane). This tilt causes the seasons.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "A sidereal day is:",
    opts: [
      "Longer than an apparent solar day",
      "Longer than a real solar day",
      "Shorter than an apparent solar day",
      "Equal to a real solar day",
    ],
    ans: 2,
    exp: "A sidereal day (measured against a distant star, ~23h 56m) is shorter than an apparent solar day (measured against the Sun, ~24h). This is because in addition to rotating 360°, the Earth must rotate slightly further each day to compensate for its orbital motion around the Sun.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "The maximum difference between mean time and apparent (real Sun) time occurs in which months?",
    opts: ["January and July", "March and September", "November and February", "December and June"],
    ans: 2,
    exp: "The Equation of Time (difference between mean noon and apparent noon) reaches its maximum values of about 16 minutes in November and about 14 minutes in February. These are the months when real noon differs most from 1200 LMT.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "The Hour Angle (Greenwich Hour Angle) of a celestial body is analogous to what on Earth?",
    opts: ["Latitude", "Longitude", "Co-latitude", "UTC"],
    ans: 1,
    exp: "GHA is measured westward from the Greenwich meridian from 0° to 360°, exactly analogous to longitude on Earth. A body with GHA 050° is transiting the 050°W meridian, the same way a position has longitude.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "The main reason that day and night have different durations throughout the year is due to:",
    opts: [
      "The Earth's rotation",
      "The relative speed of the Sun along the ecliptic",
      "The inclination of the ecliptic to the Equator",
      "The gravitational effect of the Sun and Moon on the Earth's rotation speed",
    ],
    ans: 2,
    exp: "The seasons and varying daylight lengths are caused primarily by the inclination (tilt) of the Earth's axis — 23.5° to the perpendicular of the orbital plane. This means the Sun's declination changes throughout the year, giving varying day length at different latitudes.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "What is the highest latitude at which the Sun can be vertically overhead?",
    opts: ["23.5°", "66.5°", "45°", "90°"],
    ans: 0,
    exp: "The Sun can only be directly overhead (at the zenith) between latitudes 23.5°N (Tropic of Cancer) and 23.5°S (Tropic of Capricorn), because that is the maximum declination the Sun reaches in its annual cycle.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-1",
    q: "What is the highest latitude listed below at which the Sun will rise above the horizon and set every day?",
    opts: ["68°N", "66°N", "62°N", "72°N"],
    ans: 1,
    exp: "The Arctic Circle is at 66.5°N. At latitudes poleward of the Arctic Circle, there are days when the Sun never rises (polar night) or never sets (midnight sun). At 66°N (just equatorward of the Arctic Circle), the Sun will rise and set every day of the year.",
  },

  // === nav-3 continued: Grid and Polar navigation ===

  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "Grivation is the combination of:",
    opts: [
      "Variation and Deviation",
      "Deviation and the Agonic value",
      "Variation and Grid Convergence",
      "Grid Convergence and Deviation",
    ],
    ans: 2,
    exp: "Grivation = Variation + Grid Convergence (algebraically). It is the total correction needed to convert Grid direction to Magnetic direction. Lines of equal grivation are called isogrivs.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "On a standard North Polar grid (datum meridian = Greenwich), at a position 90°W, the convergence is:",
    opts: ["90°W", "90°E", "0°", "45°E"],
    ans: 1,
    exp: "At 90°W in the Northern hemisphere, the aircraft is west of the datum (Greenwich meridian). Using the rule 'Northern hemisphere, west of datum → convergence EAST', convergence = 90°E. True track = Grid track - 90°.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "A North Polar Stereographic chart is overprinted with a standard grid (aligned with the Greenwich meridian). At position 80°N 135°E, the grid track is 235°. What is the true track?",
    opts: ["010°", "100°", "190°", "280°"],
    ans: 0,
    exp: "At 135°E, Northern hemisphere, east of datum → convergence WEST = 135°W. Convergence West → True BEST (greater). True track = 235° + 135° = 370° = 010°(T).",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-3",
    q: "On a Polar Stereographic map, a straight line from A (75°N 60°W) to B (75°N 60°E): what is the initial straight-line track going eastwards from A?",
    opts: ["090°(T)", "030°(T)", "120°(T)", "330°(T)"],
    ans: 1,
    exp: "A and B are each 60° longitude from Greenwich, giving 120° total longitude change between them. On a polar stereographic, this = 120° inclination of meridians. Both points are at the same co-latitude, forming an isosceles triangle. Each base angle = (180-120)/2 = 30°. The track from A to B is 030°(T) (30° right of due north, which points to the Pole).",
  },

  // === nav-5 continued: Plotting concepts ===

  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "A QTE is defined as:",
    opts: [
      "The magnetic track from the aircraft to a ground station",
      "The magnetic bearing of the aircraft from a ground station",
      "The true bearing of the aircraft from a ground station",
      "The true track to a ground station from the aircraft",
    ],
    ans: 2,
    exp: "QTE is the True bearing of an aircraft FROM a ground DF station. It is measured at the ground station in degrees True. The Q-code system: T=True, E=from the station (equipment). QDM = magnetic TO; QDR = magnetic FROM.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "When plotting an ADF bearing on a Lambert chart, the bearing should be plotted:",
    opts: [
      "From the meridian of the NDB, applying chart convergence",
      "From a line parallel to the aircraft's meridian drawn through the NDB",
      "From the aircraft's position directly",
      "From the mid-meridian between aircraft and NDB",
    ],
    ans: 1,
    exp: "ADF bearings are measured at the aircraft, so the bearing reference is the aircraft's meridian. To plot from the NDB, draw a line parallel to the aircraft's meridian through the NDB and plot the reciprocal bearing from this parallel meridian. This automatically accounts for chart convergence.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "For VOR radials and VDF bearings, the variation used to convert from magnetic to true is:",
    opts: [
      "Variation at the aircraft's position",
      "Variation at the ground station",
      "Mean variation along the route",
      "Variation at the mid-point between aircraft and station",
    ],
    ans: 1,
    exp: "VOR and VDF bearings are measured at the ground station (the encoding is done at the transmitter). Therefore, variation at the ground station is applied to convert to true bearing. For ADF (measured at the aircraft), variation at the aircraft is used.",
  },
  {
    subjectIds: ["air-navigation", "atpl-navigation"],
    chapterId: "nav-5",
    q: "A rhumb line is:",
    opts: [
      "The vertex of a conformal polyformic projection",
      "A straight line on a Lambert's conformal chart",
      "A line on the Earth which cuts all meridians at the same angle",
      "The shortest distance between two points on the Earth's surface",
    ],
    ans: 2,
    exp: "A rhumb line is defined as a line on the surface of the Earth that cuts all meridians at the same angle. It gives a constant direction of travel, which is ideal for compass navigation, though it is not the shortest distance (great circle) between two points.",
  },
];
