import type { DemoQuestion } from "./demo-questions";

// Curated exam-style questions authored from "Technical General for Aviators"
// by Capt. Pankaj Pahil (the site's own book) — Parts I & II (tg-1..tg-18).
const S = "Technical General for Aviators";
const IDS = ["technical-general"];

export const TECHBOOK_QUESTIONS_1: DemoQuestion[] = [
  // ── tg-1 The Atmosphere and Its Properties ─────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-1", subtopic: "The Atmosphere and Its Properties", source: S,
    q: "Air density is directly proportional to:",
    opts: ["Static pressure", "Temperature", "Humidity", "Altitude"],
    ans: 0, exp: "Density varies directly with static pressure and inversely with temperature and humidity — which is why density falls as you climb." },
  { subjectIds: IDS, chapterId: "tg-1", subtopic: "The Atmosphere and Its Properties", source: S,
    q: "In the ICAO Standard Atmosphere, temperature falls steadily with altitude up to about:",
    opts: ["18,000 ft", "26,000 ft", "36,000 ft", "46,000 ft"],
    ans: 2, exp: "ISA temperature decreases up to roughly 36,000 ft, then remains constant through the lower stratosphere." },
  { subjectIds: IDS, chapterId: "tg-1", subtopic: "The Atmosphere and Its Properties", source: S,
    q: "Dynamic pressure is given by the formula:",
    opts: ["q = ρ v", "q = ½ ρ v²", "q = 2 ρ v²", "q = ρ / v²"],
    ans: 1, exp: "Dynamic pressure is the kinetic energy of the air per unit volume: q = ½ ρ v², where ρ is density and v is TAS." },
  { subjectIds: IDS, chapterId: "tg-1", subtopic: "The Atmosphere and Its Properties", source: S,
    q: "A pitot tube facing into the airflow senses:",
    opts: ["Static pressure only", "Dynamic pressure only", "Total (static + dynamic) pressure", "Density"],
    ans: 2, exp: "The pitot tube senses Total (Pitot) Pressure = Static + Dynamic; the static vent, parallel to the flow, senses static pressure alone." },
  { subjectIds: IDS, chapterId: "tg-1", subtopic: "The Atmosphere and Its Properties", source: S,
    q: "The correct order of airspeed corrections from indicated to true airspeed is:",
    opts: ["IAS → EAS → CAS → TAS", "IAS → CAS → EAS → TAS", "IAS → TAS → CAS → EAS", "CAS → IAS → EAS → TAS"],
    ans: 1, exp: "IAS corrected for position/pressure error gives CAS; CAS corrected for compressibility gives EAS; EAS corrected for density gives TAS." },

  // ── tg-2 Fundamental Aerodynamic Principles ────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-2", subtopic: "Fundamental Aerodynamic Principles", source: S,
    q: "According to the principle of continuity (incompressible flow), a reduction in the cross-sectional area of a streamtube causes:",
    opts: ["A decrease in velocity", "An increase in velocity", "An increase in density", "No change in velocity"],
    ans: 1, exp: "With Area × Velocity constant at low subsonic speeds, narrowing the tube must speed the flow up — the basis of aerofoil lift." },
  { subjectIds: IDS, chapterId: "tg-2", subtopic: "Fundamental Aerodynamic Principles", source: S,
    q: "Bernoulli's theorem states that for an ideal fluid in steady flow:",
    opts: ["Static pressure plus dynamic pressure remains constant", "Static pressure equals dynamic pressure", "Velocity is constant along a streamline", "Density increases as velocity increases"],
    ans: 0, exp: "Static + Dynamic = Total (Pitot) pressure = constant, so an increase in velocity must reduce static pressure — the key to lift." },
  { subjectIds: IDS, chapterId: "tg-2", subtopic: "Fundamental Aerodynamic Principles", source: S,
    q: "Changes in air density may be ignored (incompressible flow assumed) below approximately:",
    opts: ["Mach 0.4", "Mach 0.7", "Mach 0.84", "Mach 1.0"],
    ans: 0, exp: "Below about M0.4 (≈300 kt) density changes are insignificant, simplifying continuity to Area × Velocity = constant." },
  { subjectIds: IDS, chapterId: "tg-2", subtopic: "Fundamental Aerodynamic Principles", source: S,
    q: "An increase in flow velocity over the upper surface of a wing causes the static pressure there to:",
    opts: ["Increase", "Decrease", "Stay constant", "Equal total pressure"],
    ans: 1, exp: "By Bernoulli, faster flow = lower static pressure; the upper-surface suction provides most of the lift." },
  { subjectIds: IDS, chapterId: "tg-2", subtopic: "Fundamental Aerodynamic Principles", source: S,
    q: "Total pressure is also referred to as:",
    opts: ["Ambient pressure", "Pitot pressure", "Vapour pressure", "Gauge pressure"],
    ans: 1, exp: "The sum of static and dynamic pressure is Total or Pitot pressure — what the pitot tube senses." },

  // ── tg-3 The Aerofoil and Subsonic Airflow ─────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-3", subtopic: "The Aerofoil and Subsonic Airflow", source: S,
    q: "The angle of incidence is the fixed angle between:",
    opts: ["Chord line and relative airflow", "Chord line and the aircraft's longitudinal axis", "Mean camber line and chord line", "Relative airflow and flight path"],
    ans: 1, exp: "Incidence is built in by the designer: chord line vs longitudinal axis. Chord line vs relative airflow is the angle of ATTACK." },
  { subjectIds: IDS, chapterId: "tg-3", subtopic: "The Aerofoil and Subsonic Airflow", source: S,
    q: "A symmetrical aerofoil is one in which:",
    opts: ["The thickness/chord ratio is zero", "The mean camber line and chord line coincide", "The leading edge radius is zero", "Maximum camber is at 50% chord"],
    ans: 1, exp: "No camber means the mean camber line lies on the chord line — upper and lower surfaces are mirror images." },
  { subjectIds: IDS, chapterId: "tg-3", subtopic: "The Aerofoil and Subsonic Airflow", source: S,
    q: "Lift is defined as the component of the Total Reaction acting:",
    opts: ["Parallel to the chord line", "Perpendicular to the relative airflow", "Parallel to the relative airflow", "Perpendicular to the longitudinal axis"],
    ans: 1, exp: "Lift acts perpendicular to the relative airflow; the parallel component of the total reaction is drag." },
  { subjectIds: IDS, chapterId: "tg-3", subtopic: "The Aerofoil and Subsonic Airflow", source: S,
    q: "The Centre of Pressure is the point:",
    opts: ["Where the aircraft's weight acts", "On the chord line through which total lift is considered to act", "Where the relative airflow is fastest", "At 50% of the chord"],
    ans: 1, exp: "The CP is the point on the chord line through which the total lift force effectively acts; its position moves with angle of attack." },
  { subjectIds: IDS, chapterId: "tg-3", subtopic: "The Aerofoil and Subsonic Airflow", source: S,
    q: "The Relative Air Flow (RAF) is:",
    opts: ["Parallel and opposite to the aircraft's flight path", "Always horizontal", "Parallel to the chord line", "Perpendicular to the flight path"],
    ans: 0, exp: "RAF is parallel and opposite to the flight path, with magnitude equal to TAS." },

  // ── tg-4 Lift, Drag, and the Angle of Attack ───────────────────────────────
  { subjectIds: IDS, chapterId: "tg-4", subtopic: "Lift, Drag, and the Angle of Attack", source: S,
    q: "In the lift formula L = Cʟ × ½ρv² × S, the term ½ρv² represents:",
    opts: ["Static pressure", "Dynamic pressure", "Total pressure", "Wing loading"],
    ans: 1, exp: "½ρv² is dynamic pressure; Cʟ accounts for AOA and aerofoil shape, and S is wing area." },
  { subjectIds: IDS, chapterId: "tg-4", subtopic: "Lift, Drag, and the Angle of Attack", source: S,
    q: "As the angle of attack increases towards the stall, the Centre of Pressure:",
    opts: ["Moves aft", "Moves forward", "Stays fixed", "Moves to the wingtip"],
    ans: 1, exp: "The point of lowest upper-surface pressure moves forward with rising AOA, taking the CP forward — most forward just before the stall." },
  { subjectIds: IDS, chapterId: "tg-4", subtopic: "Lift, Drag, and the Angle of Attack", source: S,
    q: "If IAS is doubled in level flight, to keep lift constant the coefficient of lift must reduce to:",
    opts: ["One half", "One quarter", "Three quarters", "It must double"],
    ans: 1, exp: "Dynamic pressure varies with v², so doubling IAS quadruples it; Cʟ (via AOA) must fall to a quarter to keep L constant." },
  { subjectIds: IDS, chapterId: "tg-4", subtopic: "Lift, Drag, and the Angle of Attack", source: S,
    q: "The maximum lift/drag ratio of a typical aerofoil occurs at approximately:",
    opts: ["4° AOA", "8° AOA", "12° AOA", "16° AOA"],
    ans: 0, exp: "L/D max occurs at the optimum AOA of about 4°; flying here gives best glide range and maximum endurance. 16° is the stalling angle." },
  { subjectIds: IDS, chapterId: "tg-4", subtopic: "Lift, Drag, and the Angle of Attack", source: S,
    q: "The angle of attack for maximum L/D ratio with a change in aircraft weight:",
    opts: ["Increases with weight", "Decreases with weight", "Does not change, but the IAS to achieve it does", "Changes with altitude only"],
    ans: 2, exp: "The optimum AOA is fixed by the aerofoil; a heavier aircraft simply needs a higher IAS to fly at that same AOA." },

  // ── tg-5 Three-Dimensional Airflow and Wing Design ─────────────────────────
  { subjectIds: IDS, chapterId: "tg-5", subtopic: "Three-Dimensional Airflow and Wing Design", source: S,
    q: "Aspect ratio is defined as:",
    opts: ["Span divided by chord squared", "Wing span squared divided by wing area", "Tip chord divided by root chord", "Wing area divided by span"],
    ans: 1, exp: "AR = b²/S. Sailplanes ~35, transport jets ~12, fighters ~3." },
  { subjectIds: IDS, chapterId: "tg-5", subtopic: "Three-Dimensional Airflow and Wing Design", source: S,
    q: "Wingtip vortices are strongest when the aircraft is:",
    opts: ["Fast and heavy", "Slow, heavy and in the clean configuration", "Fast and light", "On the ground with engines at idle"],
    ans: 1, exp: "Vortex strength rises with pressure differential: heavy weight, low speed (high AOA) and clean configuration give the strongest vortices." },
  { subjectIds: IDS, chapterId: "tg-5", subtopic: "Three-Dimensional Airflow and Wing Design", source: S,
    q: "Induced drag is caused by:",
    opts: ["Skin friction in the boundary layer", "Wingtip vortices tilting the lift vector rearward", "The mixing of airflows at component junctions", "Shock-wave formation"],
    ans: 1, exp: "Downwash from the tip vortices effectively tilts total lift rearward; its horizontal component is induced drag — an unavoidable by-product of lift." },
  { subjectIds: IDS, chapterId: "tg-5", subtopic: "Three-Dimensional Airflow and Wing Design", source: S,
    q: "Wake vortex generation begins:",
    opts: ["When takeoff power is set", "When the nose wheel lifts off at rotation", "At 50 ft above the runway", "When the gear is retracted"],
    ans: 1, exp: "Vortices begin at rotation (nosewheel lift-off) and end when the nosewheel touches down on landing." },
  { subjectIds: IDS, chapterId: "tg-5", subtopic: "Three-Dimensional Airflow and Wing Design", source: S,
    q: "To avoid wake turbulence when landing behind a large aircraft, you should:",
    opts: ["Stay below its flight path and land short of its touchdown point", "Stay above its flight path and land beyond its touchdown point", "Follow its exact flight path", "Land on the upwind edge of the runway"],
    ans: 1, exp: "Vortices sink below the generating aircraft's path — stay above the path and touch down beyond its touchdown point." },

  // ── tg-6 A Deeper Dive into Drag ───────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-6", subtopic: "A Deeper Dive into Drag", source: S,
    q: "Total drag is the sum of:",
    opts: ["Form drag and skin friction", "Parasite drag and induced drag", "Interference drag and induced drag", "Profile drag and form drag"],
    ans: 1, exp: "Total Drag = Parasite Drag (skin friction + form + interference) + Induced Drag." },
  { subjectIds: IDS, chapterId: "tg-6", subtopic: "A Deeper Dive into Drag", source: S,
    q: "If airspeed is doubled, parasite drag will:",
    opts: ["Double", "Quadruple", "Halve", "Remain the same"],
    ans: 1, exp: "Parasite drag increases as the square of airspeed — double the speed, four times the parasite drag." },
  { subjectIds: IDS, chapterId: "tg-6", subtopic: "A Deeper Dive into Drag", source: S,
    q: "Vmd, the minimum drag speed, occurs where:",
    opts: ["Parasite drag is zero", "Induced drag equals parasite drag", "Induced drag is maximum", "Thrust equals weight"],
    ans: 1, exp: "The total drag curve bottoms out where the induced and parasite drag curves intersect; this corresponds to the AOA for L/D max." },
  { subjectIds: IDS, chapterId: "tg-6", subtopic: "A Deeper Dive into Drag", source: S,
    q: "At speeds below Vmd an aircraft is speed-unstable because:",
    opts: ["Parasite drag rises sharply as speed falls", "Induced drag rises sharply as speed falls", "Thrust increases as speed falls", "The CG moves aft"],
    ans: 1, exp: "On the 'back side' of the drag curve a speed loss raises induced drag, deepening the deceleration unless the pilot adds thrust — the region of reversed command." },
  { subjectIds: IDS, chapterId: "tg-6", subtopic: "A Deeper Dive into Drag", source: S,
    q: "Flying at a constant IAS, the total drag with increasing altitude will:",
    opts: ["Increase", "Decrease", "Not vary", "First decrease then increase"],
    ans: 2, exp: "Constant IAS means constant dynamic pressure, so drag does not vary with altitude." },

  // ── tg-7 Stalling, Spinning, and Recovery ──────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-7", subtopic: "Stalling, Spinning, and Recovery", source: S,
    q: "An aircraft stalls when:",
    opts: ["Airspeed falls below Vs", "The critical angle of attack is exceeded", "Power is reduced to idle", "Load factor reaches 2g"],
    ans: 1, exp: "The stall is purely an AOA phenomenon — exceed the critical angle (≈16°) and the wing stalls at any speed, in any attitude." },
  { subjectIds: IDS, chapterId: "tg-7", subtopic: "Stalling, Spinning, and Recovery", source: S,
    q: "In a 60° banked level turn, the stall speed increases by approximately:",
    opts: ["20%", "30%", "41%", "100%"],
    ans: 2, exp: "A 60° level turn gives a 2g load factor; Vs rises with the square root of load factor — √2 ≈ 1.41, i.e. about 41% higher." },
  { subjectIds: IDS, chapterId: "tg-7", subtopic: "Stalling, Spinning, and Recovery", source: S,
    q: "Compared with the power-off stall speed, the power-on stall speed is:",
    opts: ["Higher", "Lower", "The same", "Double"],
    ans: 1, exp: "Thrust's vertical component supports part of the weight and slipstream adds lift, so the power-on stall speed is lower." },
  { subjectIds: IDS, chapterId: "tg-7", subtopic: "Stalling, Spinning, and Recovery", source: S,
    q: "The first and most critical action in stall recovery is to:",
    opts: ["Apply full power", "Level the wings with aileron", "Move the control column forward to reduce AOA", "Raise the flaps"],
    ans: 2, exp: "Only reducing the AOA below the critical angle restores smooth airflow; power is applied simultaneously to minimise height loss." },
  { subjectIds: IDS, chapterId: "tg-7", subtopic: "Stalling, Spinning, and Recovery", source: S,
    q: "The generic spin recovery sequence is:",
    opts: ["Full power, ailerons into the spin, rudder with the rotation", "Power idle, ailerons neutral, full opposite rudder, elevator forward", "Power idle, full aileron opposite, elevator back", "Full power, rudder neutral, elevator forward"],
    ans: 1, exp: "Power to IDLE, ailerons NEUTRAL, FULL OPPOSITE rudder, then push the elevator forward to break the stall." },
  { subjectIds: IDS, chapterId: "tg-7", subtopic: "Stalling, Spinning, and Recovery", source: S,
    q: "A 20% reduction in aircraft weight reduces the stall speed by approximately:",
    opts: ["5%", "10%", "20%", "40%"],
    ans: 1, exp: "Vs varies with the square root of weight: a 20% lighter aircraft stalls about 10% slower." },

  // ── tg-8 High-Lift Devices ─────────────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-8", subtopic: "High-Lift Devices", source: S,
    q: "The flap type giving the greatest increase in lift, often multi-slotted on transport aircraft, is the:",
    opts: ["Plain flap", "Split flap", "Slotted flap", "Fowler flap"],
    ans: 3, exp: "The Fowler flap moves aft to increase wing area before deflecting down to add camber — the greatest lift gain of the trailing-edge flaps." },
  { subjectIds: IDS, chapterId: "tg-8", subtopic: "High-Lift Devices", source: S,
    q: "Lowering trailing-edge flaps:",
    opts: ["Increases Cʟₘₐₓ and increases the stalling angle", "Increases Cʟₘₐₓ but reduces the stalling angle", "Reduces Cʟₘₐₓ and the stalling angle", "Has no effect on the stalling angle"],
    ans: 1, exp: "Flaps raise Cʟₘₐₓ (lower stall speed) but the stall occurs at a smaller angle of attack." },
  { subjectIds: IDS, chapterId: "tg-8", subtopic: "High-Lift Devices", source: S,
    q: "Which flap produces the most drag for a given lift increase?",
    opts: ["Fowler flap", "Slotted flap", "Split flap", "Plain flap"],
    ans: 2, exp: "The split flap gives about the same lift as a plain flap but with more drag; the Fowler gives the least drag for its lift gain." },
  { subjectIds: IDS, chapterId: "tg-8", subtopic: "High-Lift Devices", source: S,
    q: "A slat is:",
    opts: ["A fixed gap in the leading edge", "A movable aerofoil section that forms part of the leading edge", "A hinged section of the trailing edge", "An upper-surface spoiler panel"],
    ans: 1, exp: "A slat moves forward and down opening a slot — the most effective leading-edge device, raising both Cʟₘₐₓ and the stalling angle." },
  { subjectIds: IDS, chapterId: "tg-8", subtopic: "High-Lift Devices", source: S,
    q: "Krueger flaps are often fitted to the inboard wing of swept-wing aircraft to:",
    opts: ["Reduce induced drag", "Promote a root stall before a tip stall", "Increase aileron effectiveness", "Act as speed brakes"],
    ans: 1, exp: "Krueger flaps hinge forward from the lower surface; used inboard they encourage the root to stall first, keeping the tips (and ailerons) flying." },

  // ── tg-9 Aircraft Stability ────────────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-9", subtopic: "Aircraft Stability", source: S,
    q: "Positive static stability means that after a disturbance the aircraft initially:",
    opts: ["Continues to diverge", "Remains in the new position", "Tends to return towards its original position", "Oscillates with growing amplitude"],
    ans: 2, exp: "Static stability is the INITIAL tendency; dynamic stability describes the motion over time that follows." },
  { subjectIds: IDS, chapterId: "tg-9", subtopic: "Aircraft Stability", source: S,
    q: "The primary contributor to longitudinal (pitch) stability is the:",
    opts: ["Wing dihedral", "Vertical fin", "Horizontal stabilizer (tailplane)", "Fuselage"],
    ans: 2, exp: "The tailplane, acting far behind the CG, generates restoring pitching moments when AOA is disturbed." },
  { subjectIds: IDS, chapterId: "tg-9", subtopic: "Aircraft Stability", source: S,
    q: "Moving the centre of gravity aft makes longitudinal stability:",
    opts: ["Greater", "Less", "Unchanged", "Neutral only at high speed"],
    ans: 1, exp: "Aft CG reduces the static margin (CG to neutral point distance); the aft CG limit guarantees a minimum margin of stability." },
  { subjectIds: IDS, chapterId: "tg-9", subtopic: "Aircraft Stability", source: S,
    q: "The main design feature providing lateral (roll) stability is:",
    opts: ["Sweepback", "Dihedral", "A high fin", "Anhedral"],
    ans: 1, exp: "With dihedral, a sideslip towards the dropped wing puts that wing at a higher AOA, generating the lift to roll it back level." },
  { subjectIds: IDS, chapterId: "tg-9", subtopic: "Aircraft Stability", source: S,
    q: "Dutch roll results from:",
    opts: ["Strong directional stability compared with lateral stability", "Strong lateral stability compared with directional stability", "Neutral static stability in pitch", "An aft CG"],
    ans: 1, exp: "When the dihedral (lateral) effect dominates the fin's directional stability, a coupled roll-yaw oscillation develops — countered by a yaw damper." },
  { subjectIds: IDS, chapterId: "tg-9", subtopic: "Aircraft Stability", source: S,
    q: "Spiral divergence is associated with:",
    opts: ["Directional stability stronger than lateral stability", "Lateral stability stronger than directional stability", "Equal lateral and directional stability", "Negative longitudinal stability"],
    ans: 0, exp: "Strong directional vs weak lateral stability lets a disturbance develop into a slowly tightening descending spiral — slow enough to correct easily." },

  // ── tg-10 Aircraft Controls ────────────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-10", subtopic: "Aircraft Controls", source: S,
    q: "The elevator controls movement about the:",
    opts: ["Longitudinal axis", "Lateral axis", "Normal axis", "Drag axis"],
    ans: 1, exp: "Elevator → pitch about the lateral axis; ailerons → roll about the longitudinal axis; rudder → yaw about the normal axis." },
  { subjectIds: IDS, chapterId: "tg-10", subtopic: "Aircraft Controls", source: S,
    q: "An anti-balance tab moves:",
    opts: ["Opposite to the control surface, reducing stick force", "In the same direction as the control surface, increasing stick force", "Only when selected by the pilot", "Only on the ground"],
    ans: 1, exp: "Anti-balance tabs move WITH the surface to add feel (stick force) and effectiveness; balance tabs move opposite to lighten the controls." },
  { subjectIds: IDS, chapterId: "tg-10", subtopic: "Aircraft Controls", source: S,
    q: "With a servo tab system, the pilot's controls are connected to:",
    opts: ["The main control surface directly", "The tab only", "Both surface and tab", "A hydraulic actuator"],
    ans: 1, exp: "The pilot moves only the tab; the aerodynamic force on the tab then drives the main surface." },
  { subjectIds: IDS, chapterId: "tg-10", subtopic: "Aircraft Controls", source: S,
    q: "Adverse aileron yaw is caused by:",
    opts: ["More induced drag on the down-going aileron's wing", "More induced drag on the up-going aileron's wing", "Rudder deflection", "Propeller torque"],
    ans: 0, exp: "The down-going aileron (rising wing) makes more lift AND more induced drag, yawing the nose away from the turn; differential or Frise ailerons reduce it." },
  { subjectIds: IDS, chapterId: "tg-10", subtopic: "Aircraft Controls", source: S,
    q: "When spoilers are used for roll control they:",
    opts: ["Cause strong adverse yaw", "Do not cause adverse yaw", "Increase lift on the down-going wing", "Can only be used on the ground"],
    ans: 1, exp: "Raising a spoiler dumps lift AND adds drag on the down-going wing, so the yaw is into the turn — no adverse yaw." },
  { subjectIds: IDS, chapterId: "tg-10", subtopic: "Aircraft Controls", source: S,
    q: "Ground spoilers (lift dumpers) are deployed on landing to:",
    opts: ["Increase lift for a gentle touchdown", "Dump lift so the full weight is on the wheels for effective braking", "Assist nose-wheel steering", "Reduce engine noise"],
    ans: 1, exp: "Dumping all wing lift transfers the aircraft's weight to the wheels, maximising brake effectiveness." },

  // ── tg-11 Piston Engine & Otto Cycle ───────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-11", subtopic: "Introduction to the Piston Engine and the Otto Cycle", source: S,
    q: "One complete four-stroke Otto cycle requires the crankshaft to rotate:",
    opts: ["180°", "360°", "720°", "1080°"],
    ans: 2, exp: "Four strokes (induction, compression, power, exhaust) = two full crankshaft revolutions = 720°." },
  { subjectIds: IDS, chapterId: "tg-11", subtopic: "Introduction to the Piston Engine and the Otto Cycle", source: S,
    q: "The piston engine is called a 'constant volume engine' because:",
    opts: ["Cylinder volume never changes", "Combustion occurs while the piston is momentarily stationary at TDC", "The fuel/air ratio is fixed", "Induction occurs at constant pressure"],
    ans: 1, exp: "Ignition just before TDC means combustion takes place at nearly constant volume — unlike the gas turbine's constant-pressure Brayton cycle." },
  { subjectIds: IDS, chapterId: "tg-11", subtopic: "Introduction to the Piston Engine and the Otto Cycle", source: S,
    q: "Valve overlap is the period when:",
    opts: ["Both valves are closed", "Both inlet and exhaust valves are partially open together", "The inlet valve is open twice", "Ignition occurs"],
    ans: 1, exp: "Around TDC at the end of the exhaust stroke both valves are open; exhaust-gas momentum helps draw in the fresh charge, improving volumetric efficiency." },
  { subjectIds: IDS, chapterId: "tg-11", subtopic: "Introduction to the Piston Engine and the Otto Cycle", source: S,
    q: "Brake Horsepower (BHP) is:",
    opts: ["IHP plus FHP", "IHP minus FHP", "FHP minus IHP", "Theoretical cylinder power"],
    ans: 1, exp: "BHP = Indicated HP − Friction HP: the usable power actually delivered to the propeller shaft." },
  { subjectIds: IDS, chapterId: "tg-11", subtopic: "Introduction to the Piston Engine and the Otto Cycle", source: S,
    q: "To improve efficiency, the inlet valve opens:",
    opts: ["Exactly at TDC", "Slightly before TDC and closes after BDC", "Slightly after TDC and closes before BDC", "Only during the power stroke"],
    ans: 1, exp: "Valve lead and lag extend the induction period, increasing the charge drawn into the cylinder." },

  // ── tg-12 Engine Components and Construction ───────────────────────────────
  { subjectIds: IDS, chapterId: "tg-12", subtopic: "Engine Components and Construction", source: S,
    q: "The thermal efficiency of a typical piston engine is approximately:",
    opts: ["10-15%", "25-28%", "50-55%", "70-75%"],
    ans: 1, exp: "Only about a quarter of the fuel's heat energy becomes useful work; the rest is lost to exhaust and cooling." },
  { subjectIds: IDS, chapterId: "tg-12", subtopic: "Engine Components and Construction", source: S,
    q: "The camshaft of a four-stroke engine rotates at:",
    opts: ["Crankshaft speed", "Twice crankshaft speed", "Half crankshaft speed", "Propeller speed"],
    ans: 2, exp: "Each valve must operate once per cycle (two crank revolutions), so the camshaft turns at half crankshaft speed." },
  { subjectIds: IDS, chapterId: "tg-12", subtopic: "Engine Components and Construction", source: S,
    q: "Excessive valve (tappet) clearance causes the valve to:",
    opts: ["Open early and close late", "Open late and close early", "Remain open", "Bounce at low RPM"],
    ans: 1, exp: "Too much clearance delays opening and advances closing, shortening the valve period; too little may stop the valve closing fully." },
  { subjectIds: IDS, chapterId: "tg-12", subtopic: "Engine Components and Construction", source: S,
    q: "Compression ratio is the ratio of:",
    opts: ["Total cylinder volume at BDC to volume at TDC", "Bore to stroke", "BHP to IHP", "Charge weight to cylinder volume"],
    ans: 0, exp: "CR = total volume (piston at BDC) ÷ clearance volume (piston at TDC)." },
  { subjectIds: IDS, chapterId: "tg-12", subtopic: "Engine Components and Construction", source: S,
    q: "Cylinders are not fired consecutively in order to:",
    opts: ["Save fuel", "Reduce vibration and crankshaft load", "Simplify the ignition system", "Increase volumetric efficiency"],
    ans: 1, exp: "A spread firing order (e.g. 1-3-4-2) distributes power impulses, reducing vibration and crankshaft stress." },

  // ── tg-13 Carburetion and Mixture Control ──────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-13", subtopic: "Carburetion and Mixture Control", source: S,
    q: "Fuel is drawn from the float chamber into the airstream because the venturi creates:",
    opts: ["High static pressure", "Low static pressure", "High fuel pressure", "A temperature rise"],
    ans: 1, exp: "Air accelerating through the venturi loses static pressure (Bernoulli); the pressure drop draws fuel into the airflow." },
  { subjectIds: IDS, chapterId: "tg-13", subtopic: "Carburetion and Mixture Control", source: S,
    q: "The accelerator pump prevents:",
    opts: ["A rich mixture at altitude", "A momentary weak mixture ('flat spot') when the throttle is opened quickly", "Carburettor icing", "Vapour lock"],
    ans: 1, exp: "Rapid throttle opening momentarily weakens the mixture; the accelerator pump injects extra fuel to bridge the hesitation." },
  { subjectIds: IDS, chapterId: "tg-13", subtopic: "Carburetion and Mixture Control", source: S,
    q: "As an aircraft climbs with no mixture adjustment, the carburettor mixture becomes:",
    opts: ["Progressively leaner", "Progressively richer", "Unchanged", "Stoichiometric"],
    ans: 1, exp: "The carburettor meters by volume; as density falls with altitude the same fuel mixes with less air mass — the mixture richens, so the pilot must lean." },
  { subjectIds: IDS, chapterId: "tg-13", subtopic: "Carburetion and Mixture Control", source: S,
    q: "A very rich mixture (about 10:1) is used for takeoff because:",
    opts: ["It produces maximum power", "The excess fuel cools the cylinder and helps prevent detonation", "It reduces fuel consumption", "It increases the octane rating"],
    ans: 1, exp: "Excess unburnt fuel has a cooling effect inside the cylinder, guarding against detonation at high power." },
  { subjectIds: IDS, chapterId: "tg-13", subtopic: "Carburetion and Mixture Control", source: S,
    q: "The chemically correct (stoichiometric) air-to-fuel ratio is approximately:",
    opts: ["10:1", "15:1", "17.4:1", "20:1"],
    ans: 1, exp: "About 15:1 air to fuel by weight — though engines run slightly richer for stable operation; ~17.4:1 may be used for economy cruise." },

  // ── tg-14 AVGAS and Combustion ─────────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-14", subtopic: "Aviation Gasoline (AVGAS) and Combustion", source: S,
    q: "AVGAS 100LL is coloured:",
    opts: ["Green", "Blue", "Red", "Straw/clear"],
    ans: 1, exp: "100LL (low lead) is blue; AVGAS 100 (high lead) is green." },
  { subjectIds: IDS, chapterId: "tg-14", subtopic: "Aviation Gasoline (AVGAS) and Combustion", source: S,
    q: "The octane rating of a fuel is a measure of its:",
    opts: ["Energy content", "Resistance to detonation", "Volatility", "Specific gravity"],
    ans: 1, exp: "Octane rating compares the fuel's anti-knock quality against iso-octane (100) and normal heptane (0); it says nothing about energy content." },
  { subjectIds: IDS, chapterId: "tg-14", subtopic: "Aviation Gasoline (AVGAS) and Combustion", source: S,
    q: "Detonation is:",
    opts: ["Ignition of the charge before the spark", "A violent uncontrolled explosion of the unburnt end-gas after normal ignition", "Normal rapid combustion", "Fuel boiling in the lines"],
    ans: 1, exp: "Detonation is the explosive combustion of the remaining 'end gas' due to excessive heat and pressure — causing knocking, power loss and engine damage." },
  { subjectIds: IDS, chapterId: "tg-14", subtopic: "Aviation Gasoline (AVGAS) and Combustion", source: S,
    q: "Pre-ignition is typically caused by:",
    opts: ["Too low an octane rating", "A local hot spot such as a glowing carbon deposit", "Retarded ignition timing", "Closing the throttle quickly"],
    ans: 1, exp: "Pre-ignition is the charge lighting BEFORE the spark, usually from an incandescent hot spot — distinct from detonation." },
  { subjectIds: IDS, chapterId: "tg-14", subtopic: "Aviation Gasoline (AVGAS) and Combustion", source: S,
    q: "Tetra-Ethyl Lead (TEL) is added to AVGAS to:",
    opts: ["Colour the fuel", "Increase its octane rating and resist detonation", "Lower its freezing point", "Lubricate the fuel pumps"],
    ans: 1, exp: "TEL raises the fuel's resistance to detonation, allowing higher compression ratios and power." },

  // ── tg-15 Engine Cooling Systems ───────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-15", subtopic: "Engine Cooling Systems", source: S,
    q: "Cowl flaps are normally opened during:",
    opts: ["Cruise", "Descent", "High-power, low-airspeed conditions such as takeoff and climb", "Engine shutdown only"],
    ans: 2, exp: "Open cowl flaps maximise cooling airflow when power is high and airspeed low; they are closed in cruise/descent to reduce drag and avoid over-cooling." },
  { subjectIds: IDS, chapterId: "tg-15", subtopic: "Engine Cooling Systems", source: S,
    q: "The CHT gauge sensor is a:",
    opts: ["Thermistor", "Thermocouple", "Capacitive probe", "Bourdon tube"],
    ans: 1, exp: "A thermocouple generates a voltage proportional to temperature; if only one is fitted, it goes on the hottest-running (usually a rear) cylinder." },
  { subjectIds: IDS, chapterId: "tg-15", subtopic: "Engine Cooling Systems", source: S,
    q: "Air cooling is preferred over liquid cooling for most aircraft piston engines because it is:",
    opts: ["More effective in the climb", "Simpler and lighter", "Quieter", "Immune to over-cooling"],
    ans: 1, exp: "Liquid systems cool well but are heavy; air cooling with fins, baffles and cowl flaps is simple and light." },
  { subjectIds: IDS, chapterId: "tg-15", subtopic: "Engine Cooling Systems", source: S,
    q: "Cooling fins on a cylinder serve to:",
    opts: ["Strengthen the cylinder", "Greatly increase the surface area for heat dissipation", "Direct the fuel spray", "Reduce exhaust back pressure"],
    ans: 1, exp: "Fins multiply the surface exposed to cooling air; baffles distribute the air evenly over all cylinders." },
  { subjectIds: IDS, chapterId: "tg-15", subtopic: "Engine Cooling Systems", source: S,
    q: "Over-cooling an engine is undesirable because it:",
    opts: ["Increases detonation", "Reduces available BHP and impairs fuel vaporisation", "Raises oil pressure", "Causes valve bounce"],
    ans: 1, exp: "An engine below its working temperature loses power and vaporises fuel poorly — cooling must be controlled, not maximised." },

  // ── tg-16 Engine Lubrication Systems ───────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-16", subtopic: "Engine Lubrication Systems", source: S,
    q: "In a dry-sump system the scavenge pump capacity is:",
    opts: ["Equal to the pressure pump", "25-50% larger than the pressure pump", "Half the pressure pump", "Unimportant"],
    ans: 1, exp: "The scavenge pump must clear oil from the sump faster than the pressure pump delivers it, so it is 25-50% larger." },
  { subjectIds: IDS, chapterId: "tg-16", subtopic: "Engine Lubrication Systems", source: S,
    q: "As oil temperature increases, its viscosity:",
    opts: ["Increases", "Decreases", "Is unchanged", "Doubles"],
    ans: 1, exp: "Hot oil flows more easily (lower viscosity); the Viscosity Index describes how well the oil holds its properties over a temperature range." },
  { subjectIds: IDS, chapterId: "tg-16", subtopic: "Engine Lubrication Systems", source: S,
    q: "'Hydraulicing' in a radial or inverted engine refers to:",
    opts: ["Loss of oil pressure in flight", "Oil draining into lower cylinders causing a hydraulic lock at start", "Foaming of the oil at altitude", "Use of oil to drive the propeller"],
    ans: 1, exp: "Incompressible oil pooled in a lower cylinder can wreck the engine on start — these engines are pulled through by hand first." },
  { subjectIds: IDS, chapterId: "tg-16", subtopic: "Engine Lubrication Systems", source: S,
    q: "Besides reducing friction, engine oil also serves to:",
    opts: ["Cool, clean, act as a hydraulic medium and indicate engine condition", "Increase compression ratio", "Enrich the mixture", "Boost magneto output"],
    ans: 0, exp: "Oil carries away heat and contaminants, powers items like variable-pitch propellers, and its pressure/temperature reveal engine health." },
  { subjectIds: IDS, chapterId: "tg-16", subtopic: "Engine Lubrication Systems", source: S,
    q: "A wet-sump lubrication system stores its oil:",
    opts: ["In a separate external tank", "In the sump at the bottom of the engine", "In the propeller hub", "In the wing tanks"],
    ans: 1, exp: "Wet sump = oil lives in the engine sump (simple, but poor for aerobatics); dry sump = separate tank with a scavenge pump." },

  // ── tg-17 Induction Icing and Ignition ─────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-17", subtopic: "Induction Icing and Ignition Systems", source: S,
    q: "Carburettor icing can occur at outside air temperatures as high as:",
    opts: ["0°C", "+10°C", "+22°C", "+35°C"],
    ans: 2, exp: "Fuel vaporisation plus the venturi pressure drop can cool moist air far below freezing even on a warm day — up to about +22°C OAT." },
  { subjectIds: IDS, chapterId: "tg-17", subtopic: "Induction Icing and Ignition Systems", source: S,
    q: "With a fixed-pitch propeller, carburettor icing is indicated by:",
    opts: ["A gradual drop in RPM", "A gradual drop in manifold pressure", "Rising CHT", "Falling oil pressure"],
    ans: 0, exp: "Fixed-pitch: gradual RPM drop. Constant-speed propeller: gradual manifold pressure drop." },
  { subjectIds: IDS, chapterId: "tg-17", subtopic: "Induction Icing and Ignition Systems", source: S,
    q: "When carburettor heat is first applied with ice present, the engine will:",
    opts: ["Immediately run smoothly", "Show a further drop in power before recovering as the ice melts", "Overspeed", "Backfire continuously"],
    ans: 1, exp: "Hot air is less dense so power drops first; recovery to normal (or above) confirms ice was present." },
  { subjectIds: IDS, chapterId: "tg-17", subtopic: "Induction Icing and Ignition Systems", source: S,
    q: "With the ignition switch OFF, the magneto primary circuit is:",
    opts: ["Open", "Grounded", "Connected to the battery", "Reversed"],
    ans: 1, exp: "OFF grounds the primary winding, preventing a spark. A broken ground wire gives a 'hot mag' — live even when switched off." },
  { subjectIds: IDS, chapterId: "tg-17", subtopic: "Induction Icing and Ignition Systems", source: S,
    q: "Each cylinder has two spark plugs fed by independent magnetos in order to:",
    opts: ["Double the engine RPM", "Provide redundancy and more complete, even combustion", "Allow the battery to be removed", "Reduce plug fouling only"],
    ans: 1, exp: "Dual ignition is for safety (one magneto can fail) and performance (two flame fronts burn the charge more completely)." },
  { subjectIds: IDS, chapterId: "tg-17", subtopic: "Induction Icing and Ignition Systems", source: S,
    q: "An impulse coupling:",
    opts: ["Boosts magneto output at high RPM", "Momentarily spins the magneto fast and retards timing for starting", "Connects the two magnetos", "Drives the fuel pump"],
    ans: 1, exp: "At cranking speed the magneto spark is weak; the spring-loaded impulse coupling flicks it over fast and retards the spark for starting." },

  // ── tg-18 Supercharging and Turbocharging ──────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-18", subtopic: "Supercharging and Turbocharging", source: S,
    q: "A turbocharger is driven by:",
    opts: ["Gearing from the crankshaft", "The energy of the exhaust gases", "An electric motor", "Bleed air"],
    ans: 1, exp: "The exhaust stream spins a turbine which drives the compressor — using waste energy, unlike a crankshaft-geared supercharger." },
  { subjectIds: IDS, chapterId: "tg-18", subtopic: "Supercharging and Turbocharging", source: S,
    q: "The waste gate of a turbocharger controls boost by:",
    opts: ["Restricting the air intake", "Bypassing exhaust gas around the turbine", "Varying the propeller pitch", "Cooling the intake charge"],
    ans: 1, exp: "Opening the waste gate sends exhaust overboard, slowing the turbine; closing it speeds the turbine and raises manifold pressure." },
  { subjectIds: IDS, chapterId: "tg-18", subtopic: "Supercharging and Turbocharging", source: S,
    q: "As a turbocharged aircraft climbs, the automatic controller maintains manifold pressure by:",
    opts: ["Progressively opening the waste gate", "Progressively closing the waste gate", "Enriching the mixture", "Reducing RPM"],
    ans: 1, exp: "Thinner air requires more turbine speed, so the Absolute Pressure Controller closes the waste gate as altitude increases." },
  { subjectIds: IDS, chapterId: "tg-18", subtopic: "Supercharging and Turbocharging", source: S,
    q: "Critical altitude is the altitude at which:",
    opts: ["The engine stops", "The waste gate becomes fully closed and rated boost can no longer be maintained above it", "Detonation begins", "The propeller reaches fine pitch"],
    ans: 1, exp: "Above critical altitude the fully-closed waste gate can no longer hold sea-level manifold pressure, and power falls with further climb." },
  { subjectIds: IDS, chapterId: "tg-18", subtopic: "Supercharging and Turbocharging", source: S,
    q: "Density altitude is:",
    opts: ["Pressure altitude corrected for non-standard temperature", "Height above the ground", "Indicated altitude corrected for instrument error", "True altitude above sea level"],
    ans: 0, exp: "Density altitude — pressure altitude corrected for temperature — is what the engine and wings actually 'feel'; high values degrade performance." },
];
