import type { DemoQuestion } from "./demo-questions";

// Curated exam-style questions authored from "Technical General for Aviators"
// by Capt. Pankaj Pahil — Parts III, IV & V (tg-19..tg-36).
const S = "Technical General for Aviators";
const IDS = ["technical-general"];

export const TECHBOOK_QUESTIONS_2: DemoQuestion[] = [
  // ── tg-19 Introduction to Gas Turbine Engines ──────────────────────────────
  { subjectIds: IDS, chapterId: "tg-19", subtopic: "Introduction to Gas Turbine Engines", source: S,
    q: "The gas turbine engine operates on the:",
    opts: ["Otto cycle (constant volume)", "Brayton cycle (constant pressure)", "Carnot cycle", "Diesel cycle"],
    ans: 1, exp: "Combustion in a gas turbine occurs at nearly constant pressure (Brayton cycle), continuously — unlike the piston engine's constant-volume Otto cycle." },
  { subjectIds: IDS, chapterId: "tg-19", subtopic: "Introduction to Gas Turbine Engines", source: S,
    q: "A divergent duct in subsonic flow:",
    opts: ["Speeds the air up and raises pressure", "Slows the air down and raises pressure", "Slows the air down and lowers pressure", "Has no effect"],
    ans: 1, exp: "Widening duct → velocity converts to pressure; used in subsonic intakes and after the compressor. Convergent ducts do the opposite." },
  { subjectIds: IDS, chapterId: "tg-19", subtopic: "Introduction to Gas Turbine Engines", source: S,
    q: "In a turbo-prop engine, thrust comes approximately:",
    opts: ["90% from the propeller, 10% residual jet thrust", "50% propeller, 50% jet", "10% propeller, 90% jet", "Entirely from the jet"],
    ans: 0, exp: "The turbine extracts most of the gas energy to drive the propeller; total output is measured in Equivalent Shaft Horsepower (ESHP)." },
  { subjectIds: IDS, chapterId: "tg-19", subtopic: "Introduction to Gas Turbine Engines", source: S,
    q: "By-pass ratio is the ratio of:",
    opts: ["Hot stream mass flow to cold stream mass flow", "Cold (by-pass) stream mass flow to hot (core) stream mass flow", "Fan diameter to core diameter", "Thrust to weight"],
    ans: 1, exp: "BPR = air ducted around the core ÷ air through the core. High-BPR fans (5:1+) are quieter and more fuel-efficient at subsonic speeds." },
  { subjectIds: IDS, chapterId: "tg-19", subtopic: "Introduction to Gas Turbine Engines", source: S,
    q: "The maximum temperature in a gas turbine is limited by:",
    opts: ["The fuel's octane rating", "The metallurgical limits of the nozzle guide vanes and turbine blades", "The compressor RPM", "The intake design"],
    ans: 1, exp: "Hotter combustion means better efficiency, but the NGVs and turbine blades set the metallurgical ceiling." },

  // ── tg-20 The Air Inlet ────────────────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-20", subtopic: "The Air Inlet", source: S,
    q: "A subsonic engine intake is shaped as a:",
    opts: ["Convergent duct", "Divergent duct", "Convergent-divergent duct", "Straight pipe"],
    ans: 1, exp: "The divergent intake slows ram air and raises its pressure before the compressor — ram pressure recovery." },
  { subjectIds: IDS, chapterId: "tg-20", subtopic: "The Air Inlet", source: S,
    q: "Supersonic intakes use movable ramps or spikes to:",
    opts: ["Increase the airflow velocity", "Control shockwave position and slow the air to subsonic speed", "Filter out foreign objects", "Generate extra thrust"],
    ans: 1, exp: "Compressors cannot accept supersonic flow; the intake geometry manages shockwaves to decelerate the air efficiently." },
  { subjectIds: IDS, chapterId: "tg-20", subtopic: "The Air Inlet", source: S,
    q: "Engine intake anti-icing typically uses:",
    opts: ["Electrical heater mats only", "Hot bleed air from the compressor", "De-icing boots", "Glycol spray"],
    ans: 1, exp: "Hot compressor bleed air heats the intake lip to stop ice forming and being ingested into the compressor." },
  { subjectIds: IDS, chapterId: "tg-20", subtopic: "The Air Inlet", source: S,
    q: "FOD refers to:",
    opts: ["Fan Overspeed Detection", "Foreign Object Damage from debris entering the intake", "Fuel On Demand", "Flight Operations Directive"],
    ans: 1, exp: "Stones, birds and other debris entering the intake can severely damage compressor blades — Foreign Object Damage." },

  // ── tg-21 Compressors ──────────────────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-21", subtopic: "Compressors", source: S,
    q: "A single stage of a centrifugal compressor can achieve a compression ratio of about:",
    opts: ["1.2:1", "4:1", "12:1", "30:1"],
    ans: 1, exp: "Centrifugal: robust, large frontal area, ~4:1 per stage. Axial stages give only ~1.2:1 each but can be stacked to 30:1 or more." },
  { subjectIds: IDS, chapterId: "tg-21", subtopic: "Compressors", source: S,
    q: "In an axial compressor, the stators:",
    opts: ["Accelerate the air", "Form divergent passages that convert velocity into pressure", "Spin with the rotor", "Cool the turbine"],
    ans: 1, exp: "Each stage: rotating blades accelerate the air, then stationary stator vanes (divergent passages) slow it, raising pressure." },
  { subjectIds: IDS, chapterId: "tg-21", subtopic: "Compressors", source: S,
    q: "A compressor surge is:",
    opts: ["A small RPM fluctuation", "A complete breakdown of airflow through the compressor, often with a loud bang", "Normal behaviour at takeoff power", "An oil system fault"],
    ans: 1, exp: "In surge, high-pressure air from the rear bursts forward out of the intake — thrust loss, rapid EGT rise, possible damage." },
  { subjectIds: IDS, chapterId: "tg-21", subtopic: "Compressors", source: S,
    q: "Compressor bleed valves are opened at low RPM to:",
    opts: ["Cool the cabin", "Increase axial velocity in the front stages and prevent stall", "Boost thrust", "Reduce EGT at takeoff"],
    ans: 1, exp: "Bleeding air from the middle stages keeps the front stages' airflow matched to their blade speed, preventing stall during low RPM and acceleration." },
  { subjectIds: IDS, chapterId: "tg-21", subtopic: "Compressors", source: S,
    q: "Multi-spool engines exist primarily to:",
    opts: ["Reduce engine weight", "Let each compressor section run at its own optimal speed across the RPM range", "Simplify maintenance", "Drive two propellers"],
    ans: 1, exp: "LP/IP/HP spools each driven by their own turbine avoid stall and keep the whole compressor efficient over a wide operating range." },

  // ── tg-22 Combustion Chambers ──────────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-22", subtopic: "Combustion Chambers", source: S,
    q: "The proportion of combustion chamber air actually burned with fuel (primary air) is about:",
    opts: ["20%", "40%", "60%", "100%"],
    ans: 0, exp: "Primary ~20% burns; secondary ~20% anchors the flame; tertiary ~60% cools the flame tube and dilutes the gas for the turbine." },
  { subjectIds: IDS, chapterId: "tg-22", subtopic: "Combustion Chambers", source: S,
    q: "The most modern and efficient combustion chamber design is the:",
    opts: ["Multiple can", "Tubo-annular (can-annular)", "Annular", "Reverse-flow can"],
    ans: 2, exp: "The single ring-shaped annular chamber gives the best combustion efficiency, temperature distribution and a shorter engine." },
  { subjectIds: IDS, chapterId: "tg-22", subtopic: "Combustion Chambers", source: S,
    q: "Tertiary air cools the combustion gases from a peak of roughly 2000°C to a turbine-entry temperature of:",
    opts: ["100-300°C", "500-700°C", "1000-1500°C", "1800-1900°C"],
    ans: 2, exp: "The film of tertiary air protects the flame-tube walls then mixes in, bringing gas temperature down to what the turbine can survive." },
  { subjectIds: IDS, chapterId: "tg-22", subtopic: "Combustion Chambers", source: S,
    q: "An engine can only be relit in flight:",
    opts: ["At any altitude and speed", "Within a specific relight envelope of altitude and airspeed", "Below 10,000 ft only", "With the APU running"],
    ans: 1, exp: "Outside the relight envelope the airflow may be too fast or the air too thin to support ignition." },
  { subjectIds: IDS, chapterId: "tg-22", subtopic: "Combustion Chambers", source: S,
    q: "Swirl vanes at the front of the flame tube serve to:",
    opts: ["Cool the casing", "Create a vortex that stabilises the flame", "Filter the fuel", "Increase exhaust velocity"],
    ans: 1, exp: "The swirling primary air creates a stable, anchored flame that stays alight across the operating range." },

  // ── tg-23 The Turbine Assembly ─────────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-23", subtopic: "The Turbine Assembly", source: S,
    q: "Nozzle Guide Vanes (NGVs):",
    opts: ["Rotate with the turbine disc", "Form convergent ducts that accelerate and direct gas onto the turbine blades", "Cool the exhaust", "Reverse the thrust"],
    ans: 1, exp: "Stationary NGVs accelerate the hot gas and aim it at the optimum angle onto the rotating turbine blades." },
  { subjectIds: IDS, chapterId: "tg-23", subtopic: "The Turbine Assembly", source: S,
    q: "The gradual stretching of turbine blades under heat and centrifugal load is called:",
    opts: ["Fatigue", "Creep", "Shear", "Flutter"],
    ans: 1, exp: "Creep is permanent elongation over time; blades have a finite life in operating cycles because of it." },
  { subjectIds: IDS, chapterId: "tg-23", subtopic: "The Turbine Assembly", source: S,
    q: "Turbine blades are commonly attached to the disc by a:",
    opts: ["Weld", "Fir-tree root fixing", "Single bolt", "Adhesive bond"],
    ans: 1, exp: "The fir-tree root allows thermal expansion while holding the blade against enormous centrifugal force." },
  { subjectIds: IDS, chapterId: "tg-23", subtopic: "The Turbine Assembly", source: S,
    q: "Modern turbine blades survive gas hotter than their alloy's melting point because they are:",
    opts: ["Painted with ceramic", "Hollow and internally cooled by compressor bleed air", "Made of titanium", "Spinning too fast to melt"],
    ans: 1, exp: "Cooler compressor air flows through intricate internal passages, keeping the blade metal below its limits." },
  { subjectIds: IDS, chapterId: "tg-23", subtopic: "The Turbine Assembly", source: S,
    q: "As gas passes through a turbine stage, its pressure, temperature and velocity:",
    opts: ["All increase", "All decrease", "Pressure rises, temperature falls", "Stay constant"],
    ans: 1, exp: "The turbine extracts energy from the gas to drive the compressor; the gas leaves with lower pressure, temperature and velocity." },

  // ── tg-24 Exhaust System and Thrust Reversal ───────────────────────────────
  { subjectIds: IDS, chapterId: "tg-24", subtopic: "The Exhaust System and Thrust Reversal", source: S,
    q: "A 'choked' propelling nozzle means the exhaust gas at the nozzle exit has reached:",
    opts: ["Maximum temperature", "The local speed of sound (Mach 1.0)", "Zero static pressure", "The turbine entry temperature"],
    ans: 1, exp: "Once choked, exit velocity can only rise by increasing gas temperature — e.g. with afterburner/reheat." },
  { subjectIds: IDS, chapterId: "tg-24", subtopic: "The Exhaust System and Thrust Reversal", source: S,
    q: "On a high by-pass turbofan, thrust reversal is achieved by:",
    opts: ["Reversing fan rotation", "Blocker doors redirecting the cold by-pass air forward through cascade vanes", "Clamshell doors in the hot exhaust only", "Variable-pitch turbine blades"],
    ans: 1, exp: "The cold-stream reverser blocks the fan duct and turns that air forward; the hot core flow is unaffected. Clamshell/bucket doors suit pure jets." },
  { subjectIds: IDS, chapterId: "tg-24", subtopic: "The Exhaust System and Thrust Reversal", source: S,
    q: "Thrust reversers can normally be deployed only when:",
    opts: ["Airspeed is below 80 kt", "Throttles are at idle and weight-on-wheels confirms the aircraft is on the ground", "The APU is running", "Flaps are retracted"],
    ans: 1, exp: "Safety interlocks require idle thrust levers plus ground (squat switch) logic before the reversers will deploy." },
  { subjectIds: IDS, chapterId: "tg-24", subtopic: "The Exhaust System and Thrust Reversal", source: S,
    q: "The exhaust cone behind the turbine serves to:",
    opts: ["Accelerate the gas to supersonic speed", "Smooth the gas flow and prevent turbulence", "Cool the turbine disc", "House the APU"],
    ans: 1, exp: "The cone fairs the flow off the turbine into the jet pipe; the final convergent propelling nozzle then accelerates it." },

  // ── tg-25 Engine Starting and APU ──────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-25", subtopic: "Engine Starting and Auxiliary Power Units (APU)", source: S,
    q: "A 'hot start' is one in which:",
    opts: ["EGT exceeds its maximum limit during start", "The engine fails to light up", "The engine accelerates too quickly", "Oil temperature is high before start"],
    ans: 0, exp: "Too much fuel for the available airflow sends EGT past its limit — the start must be aborted immediately." },
  { subjectIds: IDS, chapterId: "tg-25", subtopic: "Engine Starting and Auxiliary Power Units (APU)", source: S,
    q: "A 'hung start' is one in which the engine:",
    opts: ["Fails to rotate", "Lights up but stabilises below idle RPM with rising EGT", "Starts then flames out", "Overspeeds"],
    ans: 1, exp: "Usually insufficient starter power: light-up occurs but the engine won't accelerate to idle, while EGT climbs." },
  { subjectIds: IDS, chapterId: "tg-25", subtopic: "Engine Starting and Auxiliary Power Units (APU)", source: S,
    q: "After a wet start (no light-up), before another attempt the engine must be:",
    opts: ["Refuelled", "Motored over to blow out unburnt fuel", "Allowed to cool for 24 hours", "Inspected by maintenance only"],
    ans: 1, exp: "A blowout cycle clears pooled fuel so the next start doesn't torch." },
  { subjectIds: IDS, chapterId: "tg-25", subtopic: "Engine Starting and Auxiliary Power Units (APU)", source: S,
    q: "Self-sustaining speed during a start is the point where:",
    opts: ["The starter cuts out automatically at idle", "The turbine produces enough power to drive the compressor without the starter", "Fuel is first introduced", "EGT peaks"],
    ans: 1, exp: "Beyond self-sustaining speed the engine can accelerate on its own; the starter then drops out and the engine stabilises at idle." },
  { subjectIds: IDS, chapterId: "tg-25", subtopic: "Engine Starting and Auxiliary Power Units (APU)", source: S,
    q: "A Ram Air Turbine (RAT) provides:",
    opts: ["Cabin pressurisation", "Emergency hydraulic or electrical power from a turbine deployed into the airstream", "Engine starting air", "Extra thrust"],
    ans: 1, exp: "After a total power failure the RAT deploys and the airflow spins it to power essential flight controls and instruments." },

  // ── tg-26 Airframe Structures and Loads ────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-26", subtopic: "Airframe Structures and Loads", source: S,
    q: "Components designed to resist tension are called:",
    opts: ["Struts", "Ties", "Webs", "Frames"],
    ans: 1, exp: "Ties take tension; struts take compression. Riveted joints chiefly resist shear." },
  { subjectIds: IDS, chapterId: "tg-26", subtopic: "Airframe Structures and Loads", source: S,
    q: "The Design Ultimate Load is the Design Limit Load multiplied by a safety factor of typically:",
    opts: ["1.1", "1.25", "1.5", "3.0"],
    ans: 2, exp: "DUL = DLL × 1.5; the structure must withstand DUL without catastrophic failure." },
  { subjectIds: IDS, chapterId: "tg-26", subtopic: "Airframe Structures and Loads", source: S,
    q: "The design philosophy that assumes cracks will occur and ensures they grow slowly enough to be found at inspections is:",
    opts: ["Safe life", "Fail-safe", "Damage tolerant", "Monocoque"],
    ans: 2, exp: "Damage-tolerant design accepts that damage happens and manages its growth; safe-life retires parts early; fail-safe uses redundant load paths." },
  { subjectIds: IDS, chapterId: "tg-26", subtopic: "Airframe Structures and Loads", source: S,
    q: "In semi-monocoque construction, the members running lengthwise to stiffen the skin are:",
    opts: ["Formers", "Bulkheads", "Stringers", "Ribs"],
    ans: 2, exp: "Formers/frames give shape, bulkheads add major strength, and stringers run lengthwise preventing skin buckling." },
  { subjectIds: IDS, chapterId: "tg-26", subtopic: "Airframe Structures and Loads", source: S,
    q: "The primary structural component of a modern cantilever wing is the:",
    opts: ["Leading edge", "Torsion box formed by spars, ribs, stringers and skin", "Winglet", "Flap track"],
    ans: 1, exp: "The torsion (wing) box between front and rear spars resists the wing's bending and twisting loads." },

  // ── tg-27 Pneumatics, Air Conditioning and Pressurization ──────────────────
  { subjectIds: IDS, chapterId: "tg-27", subtopic: "Pneumatic Systems, Air Conditioning, and Pressurization", source: S,
    q: "The most common source of air for pneumatic services on a jet transport is:",
    opts: ["Ram air", "Engine compressor bleed air", "An electric compressor", "Exhaust gas"],
    ans: 1, exp: "Hot high-pressure air is bled from the engine compressors, with valves selecting LP or HP stages depending on engine RPM." },
  { subjectIds: IDS, chapterId: "tg-27", subtopic: "Pneumatic Systems, Air Conditioning, and Pressurization", source: S,
    q: "In the bootstrap air-cycle system, the large temperature drop is produced by:",
    opts: ["A heat exchanger", "Rapid expansion of the air across a turbine", "Mixing with ram air", "A refrigerant gas"],
    ans: 1, exp: "After pre-cooling and re-compression, the air expands across a turbine and its temperature plummets — the turbine's work helps drive the compressor." },
  { subjectIds: IDS, chapterId: "tg-27", subtopic: "Pneumatic Systems, Air Conditioning, and Pressurization", source: S,
    q: "Cabin pressure is controlled primarily by:",
    opts: ["Varying pack output", "Modulating the outflow valve(s)", "The dump valve", "Engine RPM"],
    ans: 1, exp: "Packs supply a constant mass flow; closing the outflow valve raises cabin pressure (lowers cabin altitude), opening it does the reverse." },
  { subjectIds: IDS, chapterId: "tg-27", subtopic: "Pneumatic Systems, Air Conditioning, and Pressurization", source: S,
    q: "The inward relief valve protects the structure when:",
    opts: ["Cabin pressure exceeds outside pressure", "Outside pressure exceeds cabin pressure, e.g. in a rapid descent", "The packs fail", "On the ground only"],
    ans: 1, exp: "Outward relief prevents exceeding max differential; inward relief prevents outside pressure crushing inwards during rapid descent." },
  { subjectIds: IDS, chapterId: "tg-27", subtopic: "Pneumatic Systems, Air Conditioning, and Pressurization", source: S,
    q: "A typical maximum cabin altitude maintained in cruise is:",
    opts: ["Sea level", "8,000 ft or lower", "15,000 ft", "25,000 ft"],
    ans: 1, exp: "Pressurisation keeps the cabin at a safe, comfortable altitude (≤ ~8,000 ft) while the aircraft cruises far higher." },

  // ── tg-28 Hydraulic Systems ────────────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-28", subtopic: "Hydraulic Systems", source: S,
    q: "Pascal's law states that pressure applied to a confined fluid:",
    opts: ["Acts only downward", "Is transmitted equally in all directions", "Decreases with distance", "Varies with fluid colour"],
    ans: 1, exp: "Equal transmission of pressure lets a small force on a small piston create a large force on a large piston — at the cost of travel distance." },
  { subjectIds: IDS, chapterId: "tg-28", subtopic: "Hydraulic Systems", source: S,
    q: "Skydrol (phosphate-ester) hydraulic fluid is coloured:",
    opts: ["Red", "Purple", "Blue", "Green"],
    ans: 1, exp: "Phosphate-ester fluid is purple, fire-resistant, used with butyl seals; mineral-based fluid is red with neoprene seals. They are NOT interchangeable." },
  { subjectIds: IDS, chapterId: "tg-28", subtopic: "Hydraulic Systems", source: S,
    q: "A hydraulic accumulator contains:",
    opts: ["Fluid only", "Fluid on one side of a piston/diaphragm and compressed nitrogen on the other", "Compressed oxygen", "A filter element"],
    ans: 1, exp: "The nitrogen charge stores energy: damping pressure fluctuations, meeting peak demands and providing emergency pressure." },
  { subjectIds: IDS, chapterId: "tg-28", subtopic: "Hydraulic Systems", source: S,
    q: "Hydraulic reservoirs on jet aircraft are often pressurised with bleed air to:",
    opts: ["Cool the fluid", "Ensure positive fluid supply to the pumps and prevent foaming at altitude", "Filter the fluid", "Operate the brakes directly"],
    ans: 1, exp: "Reservoir pressurisation stops pump cavitation and fluid foaming in the thin air at altitude." },
  { subjectIds: IDS, chapterId: "tg-28", subtopic: "Hydraulic Systems", source: S,
    q: "The most common pump type on large aircraft hydraulic systems is the:",
    opts: ["Constant delivery pump with automatic cutout", "Constant pressure (variable volume) pump", "Hand pump", "Centrifugal pump"],
    ans: 1, exp: "Constant-pressure pumps vary their output volume automatically to hold system pressure, removing the need for a cutout valve." },

  // ── tg-29 Landing Gear Systems ─────────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-29", subtopic: "Landing Gear Systems", source: S,
    q: "An oleo-pneumatic shock strut contains:",
    opts: ["Oil only", "Hydraulic fluid and compressed nitrogen", "Compressed air only", "Rubber blocks"],
    ans: 1, exp: "Fluid forced through an orifice damps the landing impact; the nitrogen charge acts as the spring supporting the aircraft." },
  { subjectIds: IDS, chapterId: "tg-29", subtopic: "Landing Gear Systems", source: S,
    q: "Torque links (scissors) on a landing gear leg:",
    opts: ["Absorb landing shock", "Allow the strut to compress while preventing it rotating", "Steer the nosewheel", "Lock the gear down"],
    ans: 1, exp: "The hinged scissors connect inner and outer cylinders: free vertical travel, no rotation." },
  { subjectIds: IDS, chapterId: "tg-29", subtopic: "Landing Gear Systems", source: S,
    q: "The gear selector cannot be moved UP on the ground because of:",
    opts: ["A hydraulic fuse", "Weight-on-wheels (squat switch) logic operating a selector lock", "The shimmy damper", "Brake pressure"],
    ans: 1, exp: "Air/ground logic locks the lever while weight is on the wheels; ground lock pins with red flags add a manual safeguard." },
  { subjectIds: IDS, chapterId: "tg-29", subtopic: "Landing Gear Systems", source: S,
    q: "Emergency gear extension after hydraulic failure typically works by:",
    opts: ["A second engine-driven pump", "Releasing the up-locks and letting the gear free-fall and lock down", "Electric motors", "Bleed air pressure"],
    ans: 1, exp: "With up-locks released, gravity and air loads swing the gear into the down-and-locked position." },
  { subjectIds: IDS, chapterId: "tg-29", subtopic: "Landing Gear Systems", source: S,
    q: "A shimmy damper prevents:",
    opts: ["Brake fade", "Rapid unstable oscillation of the nose wheel", "Tyre creep", "Gear retraction in flight"],
    ans: 1, exp: "The small hydraulic damper stops the nosewheel's rapid oscillations (shimmy) on takeoff and landing." },

  // ── tg-30 Wheels, Tyres and Brakes ─────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-30", subtopic: "Aircraft Wheels, Tyres, and Brakes", source: S,
    q: "Fusible plugs in transport-aircraft wheels:",
    opts: ["Lock the brakes when hot", "Melt at a set temperature to deflate the tyre in a controlled way and prevent explosion", "Measure tyre pressure", "Indicate creep"],
    ans: 1, exp: "Overheated brakes can burst a tyre; the fusible plug core melts first, releasing pressure safely." },
  { subjectIds: IDS, chapterId: "tg-30", subtopic: "Aircraft Wheels, Tyres, and Brakes", source: S,
    q: "Aircraft tyres are inflated with nitrogen because it:",
    opts: ["Is cheaper than air", "Is inert and does not support combustion", "Increases tyre pressure with heat", "Weighs less than air"],
    ans: 1, exp: "Inert nitrogen removes the fire/explosion risk of hot oxygen-bearing air inside the tyre." },
  { subjectIds: IDS, chapterId: "tg-30", subtopic: "Aircraft Wheels, Tyres, and Brakes", source: S,
    q: "The minimum aquaplaning speed in knots is approximately:",
    opts: ["9 × √(tyre pressure in PSI)", "3 × tyre pressure", "√(9 × weight)", "Half the touchdown speed"],
    ans: 0, exp: "V(aquaplane) ≈ 9√P. A wedge of water lifts the tyre off the runway, destroying braking and steering." },
  { subjectIds: IDS, chapterId: "tg-30", subtopic: "Aircraft Wheels, Tyres, and Brakes", source: S,
    q: "Compared with steel, carbon brakes are:",
    opts: ["Heavier but cheaper", "Lighter, absorb more heat and work better when hot", "Only used on light aircraft", "Prone to fade at high temperature"],
    ans: 1, exp: "Carbon-carbon discs save weight, absorb more energy and retain effectiveness at high temperatures." },
  { subjectIds: IDS, chapterId: "tg-30", subtopic: "Aircraft Wheels, Tyres, and Brakes", source: S,
    q: "The anti-skid system works by:",
    opts: ["Locking all wheels together", "Releasing and reapplying brake pressure on a wheel about to skid", "Applying the parking brake", "Reducing engine thrust"],
    ans: 1, exp: "Wheel-speed sensors detect impending lock-up; the control unit momentarily releases that wheel's pressure for maximum braking without a skid." },

  // ── tg-31 Aircraft Fuel Systems ────────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-31", subtopic: "Aircraft Fuel Systems", source: S,
    q: "The most common fuel tank type on large aircraft is the:",
    opts: ["Rigid tank", "Flexible bladder tank", "Integral tank (sealed wing structure)", "Drop tank"],
    ans: 2, exp: "Integral tanks use the sealed wing box itself as the tank — maximum capacity with no added tank weight." },
  { subjectIds: IDS, chapterId: "tg-31", subtopic: "Aircraft Fuel Systems", source: S,
    q: "Booster pumps in the tanks primarily serve to:",
    opts: ["Pressurise the cabin", "Supply fuel under low pressure to the engine pumps and prevent vapour lock", "Increase fuel temperature", "Mix the fuel additives"],
    ans: 1, exp: "Electric centrifugal pumps in the tanks keep positive pressure to the engine-driven pumps, preventing vapour lock at altitude." },
  { subjectIds: IDS, chapterId: "tg-31", subtopic: "Aircraft Fuel Systems", source: S,
    q: "Modern capacitive fuel gauging systems measure:",
    opts: ["Fuel volume", "Fuel mass (weight)", "Fuel temperature", "Tank pressure"],
    ans: 1, exp: "Measuring mass rather than volume stays accurate as fuel density changes with temperature." },
  { subjectIds: IDS, chapterId: "tg-31", subtopic: "Aircraft Fuel Systems", source: S,
    q: "The collector (feeder) tank is designed to:",
    opts: ["Vent excess fuel overboard", "Remain full during manoeuvres so the booster pumps never run dry", "Collect water from the fuel", "Store the fuel additives"],
    ans: 1, exp: "Located at the lowest point with the booster pumps, it guarantees fuel supply during attitude changes." },
  { subjectIds: IDS, chapterId: "tg-31", subtopic: "Aircraft Fuel Systems", source: S,
    q: "Cross-feed valves allow:",
    opts: ["Fuel jettison", "Fuel from any tank to feed any engine", "Refuelling in flight", "Mixing AVGAS with AVTUR"],
    ans: 1, exp: "Cross-feed and shut-off valves give supply flexibility and let a leaking tank or engine be isolated." },

  // ── tg-32 Ice and Rain Protection ──────────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-32", subtopic: "Ice and Rain Protection", source: S,
    q: "The difference between anti-icing and de-icing is:",
    opts: ["They are the same", "Anti-icing prevents ice forming; de-icing removes ice already formed", "De-icing is used only on the ground", "Anti-icing is mechanical only"],
    ans: 1, exp: "Anti-icing is continuous prevention (e.g. hot leading edges); de-icing is cyclic removal (e.g. inflatable boots)." },
  { subjectIds: IDS, chapterId: "tg-32", subtopic: "Ice and Rain Protection", source: S,
    q: "The most common wing ice protection on jet transport aircraft is:",
    opts: ["Pneumatic boots", "Thermal anti-icing using hot bleed air in the leading edges", "Electrical heater mats on the whole wing", "Glycol weeping wings"],
    ans: 1, exp: "Hot compressor bleed air ducted through the leading edges keeps them above freezing; boots are typical of smaller turboprops." },
  { subjectIds: IDS, chapterId: "tg-32", subtopic: "Ice and Rain Protection", source: S,
    q: "Pitot tubes, static ports and AOA vanes are protected from ice by:",
    opts: ["Bleed air", "Electrical heating", "Rubber boots", "Rain repellent"],
    ans: 1, exp: "Small critical sensors use electric heaters — as do cockpit windows." },
  { subjectIds: IDS, chapterId: "tg-32", subtopic: "Ice and Rain Protection", source: S,
    q: "Pneumatic de-icing boots remove ice by:",
    opts: ["Heating the leading edge", "Cyclic inflation that cracks the accumulated ice off", "Spraying alcohol", "Vibrating ultrasonically"],
    ans: 1, exp: "The rubber boots inflate in cycles, breaking the ice which the airstream then carries away." },

  // ── tg-33 Safety and Emergency Equipment ───────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-33", subtopic: "Safety and Emergency Equipment", source: S,
    q: "The Time of Useful Consciousness at 35,000 ft is approximately:",
    opts: ["5 minutes", "2 minutes", "30-45 seconds", "10 seconds"],
    ans: 2, exp: "At 35,000 ft a person has only 30-45 seconds of useful consciousness after losing oxygen — why crew masks must don in seconds." },
  { subjectIds: IDS, chapterId: "tg-33", subtopic: "Safety and Emergency Equipment", source: S,
    q: "Passenger chemical oxygen generators:",
    opts: ["Can be switched off when not needed", "Once started cannot be stopped and supply about 15 minutes of oxygen", "Provide oxygen for the whole flight", "Use compressed oxygen bottles"],
    ans: 1, exp: "Pulling the mask starts a sodium-chlorate/iron reaction that runs to completion — roughly 15 minutes of flow." },
  { subjectIds: IDS, chapterId: "tg-33", subtopic: "Safety and Emergency Equipment", source: S,
    q: "Crew diluter-demand oxygen masks supply 100% oxygen above approximately:",
    opts: ["10,000 ft", "18,000 ft", "32,000 ft", "40,000 ft"],
    ans: 2, exp: "Below ~32,000 ft the regulator mixes cabin air with oxygen on inhalation; above it, 100% oxygen is delivered." },
  { subjectIds: IDS, chapterId: "tg-33", subtopic: "Safety and Emergency Equipment", source: S,
    q: "Gaseous oxygen is stored in cylinders coloured:",
    opts: ["Red", "Green", "Yellow", "Black"],
    ans: 1, exp: "High-pressure oxygen cylinders are green." },
  { subjectIds: IDS, chapterId: "tg-33", subtopic: "Safety and Emergency Equipment", source: S,
    q: "Engine and APU fire zones are typically monitored by:",
    opts: ["Smoke detectors", "A continuous fire-wire or gas-filled sensing loop triggered by heat", "CCTV cameras", "The EGT gauge alone"],
    ans: 1, exp: "Continuous-loop detectors around the fire zones alarm at a set temperature; smoke detectors guard cargo holds and lavatories." },

  // ── tg-34 Fundamentals of Electricity ──────────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-34", subtopic: "Fundamentals of Electricity", source: S,
    q: "A voltmeter and an ammeter are connected, respectively:",
    opts: ["Both in series", "Both in parallel", "Voltmeter in parallel, ammeter in series", "Voltmeter in series, ammeter in parallel"],
    ans: 2, exp: "Voltage is measured across a component (parallel); current must flow through the meter (series)." },
  { subjectIds: IDS, chapterId: "tg-34", subtopic: "Fundamentals of Electricity", source: S,
    q: "Ohm's law states:",
    opts: ["V = I × R", "V = I / R", "V = R / I", "V = I² × R"],
    ans: 0, exp: "Voltage = Current × Resistance; and electrical power P = V × I watts." },
  { subjectIds: IDS, chapterId: "tg-34", subtopic: "Fundamentals of Electricity", source: S,
    q: "A trip-free circuit breaker:",
    opts: ["Cannot be reset", "Cannot be held closed against a fault current", "Trips only on the ground", "Replaces the battery"],
    ans: 1, exp: "Even if held in, a trip-free CB will open under fault current — it cannot be forced to feed a short." },
  { subjectIds: IDS, chapterId: "tg-34", subtopic: "Fundamentals of Electricity", source: S,
    q: "Once fully charged, a capacitor in a DC circuit:",
    opts: ["Passes DC freely", "Blocks the flow of DC", "Becomes a resistor", "Reverses the current"],
    ans: 1, exp: "A capacitor stores charge, appears to pass AC, but blocks steady DC once charged." },
  { subjectIds: IDS, chapterId: "tg-34", subtopic: "Fundamentals of Electricity", source: S,
    q: "A lead-acid battery is fully charged when its electrolyte's specific gravity is about:",
    opts: ["1.00", "1.15", "1.30", "1.60"],
    ans: 2, exp: "SG ≈ 1.30 indicates full charge; capacity is rated in ampere-hours and at least 80% charge is required before flight." },
  { subjectIds: IDS, chapterId: "tg-34", subtopic: "Fundamentals of Electricity", source: S,
    q: "Nickel-cadmium batteries are more susceptible than lead-acid to:",
    opts: ["Freezing", "Thermal runaway during charging", "Low voltage output", "Sulphation"],
    ans: 1, exp: "NiCd batteries are lighter and better in cold, but can overheat uncontrollably (thermal runaway) while charging." },

  // ── tg-35 DC Generation and Distribution ───────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-35", subtopic: "DC Generation and Distribution", source: S,
    q: "In a DC generator, the device that converts the armature's AC into DC output is the:",
    opts: ["Slip ring", "Commutator", "Rectifier diode", "Voltage regulator"],
    ans: 1, exp: "The commutator mechanically reverses the connections every half turn. Alternators instead rectify their AC output with solid-state diodes." },
  { subjectIds: IDS, chapterId: "tg-35", subtopic: "DC Generation and Distribution", source: S,
    q: "Compared with a DC generator, an alternator on a light aircraft:",
    opts: ["Is heavier and less efficient at low RPM", "Takes its high output current from stationary windings and works better at low RPM", "Needs no voltage regulation", "Produces DC directly"],
    ans: 1, exp: "The rotating-field/stationary-armature design avoids passing load current through brushes — lighter, more reliable, better at low RPM." },
  { subjectIds: IDS, chapterId: "tg-35", subtopic: "DC Generation and Distribution", source: S,
    q: "A voltage regulator holds generator output constant by:",
    opts: ["Varying engine RPM", "Adjusting the current through the field winding", "Switching loads off", "Changing the propeller pitch"],
    ans: 1, exp: "More field current = stronger magnetic field = higher output voltage; the regulator trims field current continuously." },
  { subjectIds: IDS, chapterId: "tg-35", subtopic: "DC Generation and Distribution", source: S,
    q: "In an earth-return electrical system:",
    opts: ["Two wires run to every component", "The airframe is used as the negative conductor", "The battery is isolated from the airframe", "Only AC can be distributed"],
    ans: 1, exp: "Grounding the negative side to the metal airframe halves the wiring — a major weight saving." },
  { subjectIds: IDS, chapterId: "tg-35", subtopic: "DC Generation and Distribution", source: S,
    q: "A zero reading on the alternator load meter in flight indicates:",
    opts: ["The battery is fully charged", "Alternator failure", "Normal cruise operation", "An open circuit breaker somewhere"],
    ans: 1, exp: "The load meter shows alternator output; zero in flight means the alternator has dropped offline." },

  // ── tg-36 AC Generation and Distribution ───────────────────────────────────
  { subjectIds: IDS, chapterId: "tg-36", subtopic: "AC Generation and Distribution", source: S,
    q: "The standard AC frequency in aircraft electrical systems is:",
    opts: ["50 Hz", "60 Hz", "400 Hz", "1000 Hz"],
    ans: 2, exp: "Aircraft use 400 Hz three-phase AC — higher frequency permits smaller, lighter machines." },
  { subjectIds: IDS, chapterId: "tg-36", subtopic: "AC Generation and Distribution", source: S,
    q: "A Constant Speed Drive Unit (CSDU) is used to:",
    opts: ["Drive the alternator at constant speed despite varying engine RPM", "Regulate DC voltage", "Start the engine", "Synchronise the propellers"],
    ans: 0, exp: "The hydromechanical CSDU converts variable engine speed to constant output speed, holding the 400 Hz frequency. Combined with the generator it forms an IDG." },
  { subjectIds: IDS, chapterId: "tg-36", subtopic: "AC Generation and Distribution", source: S,
    q: "A Transformer Rectifier Unit (TRU) converts:",
    opts: ["DC to AC", "115V AC to 28V DC", "28V DC to 115V AC", "400 Hz to 50 Hz"],
    ans: 1, exp: "The TRU steps the 115V AC down and rectifies it to 28V DC. The opposite job — battery DC to essential AC — is done by an inverter." },
  { subjectIds: IDS, chapterId: "tg-36", subtopic: "AC Generation and Distribution", source: S,
    q: "Before AC generators can be paralleled onto a common bus, they must match in:",
    opts: ["Temperature and pressure", "Voltage, frequency and phase sequence", "RPM only", "Field current"],
    ans: 1, exp: "Voltage, frequency and phase rotation must be synchronised; the system then shares real (kW) and reactive (kVAR) load equally." },
  { subjectIds: IDS, chapterId: "tg-36", subtopic: "AC Generation and Distribution", source: S,
    q: "Static wicks on trailing edges serve to:",
    opts: ["Improve aileron response", "Discharge airframe static electricity safely into the atmosphere", "Detect icing", "Reduce drag"],
    ans: 1, exp: "They bleed off static build-up, preventing interference with communications; bonding straps keep all metal parts at equal potential." },
];
