// Meteorology Ch.8 (Vertical Motion & Clouds / Stability) — VERIFIED. IC = IC Joshi QB.
export const CH8 = [
  { src:"IC", q:"Drizzle falls from:", opts:["Cirrostratus (CS)","Stratus (ST)","Nimbostratus (NS)","Cumulus (CU)"], ans:1, status:"VERIFIED", cite:"Drizzle falls from stratus." },
  { src:"IC", q:"Altostratus (AS) is:", opts:["A low sheet cloud","A medium-level sheet cloud","A cloud of large vertical growth","A high sheet cloud"], ans:1, status:"TEXT-FIX", cite:"AS is a medium (mid-level) sheet cloud. (Garbled first option cleaned.)" },
  { src:"IC", q:"Showers fall from:", opts:["Cumulus (CU)","Cumulonimbus (CB)","Altostratus (AS)","Altocumulus (AC)"], ans:1, status:"VERIFIED", cite:"Showery precipitation comes from convective CB/CU; CB gives the classic shower." },
  { src:"IC", q:"Heavy (severe) airframe icing is most likely in:", opts:["Cirrus (CI)","Cirrostratus (CS)","Stratus (ST)","Cumulonimbus (CB)"], ans:3, status:"VERIFIED", cite:"CB holds large supercooled droplets → severe icing." },
  { src:"IC", q:"To avoid icing, a pilot should prefer a cloud showing which optical phenomenon?", opts:["Halo","Corona","Iridescence (multicoloured cloud)"], ans:0, status:"VERIFIED", cite:"A halo means ice crystals (already frozen) → low icing; corona/iridescence means supercooled water." },
  { src:"IC", q:"The dark-grey cloud giving continuous rain is:", opts:["Altostratus (AS)","Nimbostratus (NS)","Stratus (ST)","Cumulonimbus (CB)"], ans:1, status:"VERIFIED", cite:"Nimbostratus gives continuous rain." },
  { src:"IC", q:"A uniform layer of cloud resembling fog but not touching the ground is:", opts:["Altostratus (AS)","Nimbostratus (NS)","Stratus (ST)"], ans:2, status:"VERIFIED", cite:"Stratus is fog-like layer cloud lifted off the surface." },
  { src:"IC", q:"The feathery cloud composed of ice crystals is:", opts:["Cirrus (CI)","Cirrostratus (CS)","Altostratus (AS)"], ans:0, status:"VERIFIED", cite:"Cirrus — high, feathery, ice-crystal cloud." },
  { src:"IC", q:"Nimbostratus (NS) cloud occurs at a:", opts:["Cold front","Warm front"], ans:1, status:"VERIFIED", cite:"NS is associated with the gentle uplift of a warm front." },
  { src:"IC", q:"A halo is associated with which cloud?", opts:["Altocumulus (AC)","Altostratus (AS)","Cirrostratus (CS)","Cirrus (CI)"], ans:2, status:"VERIFIED", cite:"Halo forms in cirrostratus (ice crystals)." },
  { src:"IC", q:"A corona is associated with which cloud?", opts:["Altostratus (AS)","Altocumulus (AC)","Cirrocumulus (CC)","Cirrostratus (CS)"], ans:1, status:"VERIFIED", cite:"Corona forms in thin water-droplet cloud such as altocumulus." },
  { src:"IC", q:"Lenticular clouds indicate the presence of:", opts:["A warm front","A cold front","Mountain waves"], ans:2, status:"VERIFIED", cite:"Lenticular (wave) clouds mark standing mountain waves." },
  { src:"IC", q:"The lowest level below which condensation (contrails) will NOT form is the:", opts:["Mintra level","Drytra level","Maxtra level"], ans:0, status:"VERIFIED", cite:"Mintra = minimum trail level." },
  { src:"IC", q:"Rain falling from a cloud but not reaching the ground is:", opts:["Virgo","Virga","Mirage"], ans:1, status:"VERIFIED", cite:"Virga = precipitation evaporating before reaching the surface." },
  { src:"IC", q:"A cumulonimbus with a distinct anvil is:", opts:["Castellanus","Capillatus","Uncinus"], ans:1, status:"VERIFIED", cite:"CB capillatus (incus) has the fibrous anvil top." },
  { src:"IC", q:"The cloud ceiling is the height of the lowest cloud covering:", opts:["3–4 oktas","8 oktas","5 oktas or more"], ans:2, status:"VERIFIED", cite:"Ceiling = lowest broken/overcast layer (≥5 oktas)." },
  { src:"IC", q:"Condensation trails do NOT form above the:", opts:["Maxtra level","Drytra level","Mintra level"], ans:0, status:"VERIFIED", cite:"Maxtra = maximum trail level." },
  { src:"IC", q:"A cloud is of operational significance when its base is below ____ m, or below the highest minimum sector altitude, whichever is greater:", opts:["1500","2000","1000"], ans:0, status:"VERIFIED", cite:"1500 m (5000 ft) is the operational-significance threshold." },
  { src:"IC", q:"Altocumulus with cumuliform protuberances (castellanus/floccus) indicates:", opts:["Stability","Instability","Neutrality"], ans:1, status:"VERIFIED", cite:"AC castellanus signals mid-level instability." },
  { src:"IC", q:"Hail may be experienced under the anvil of a CB:", opts:["True","False"], ans:0, status:"VERIFIED", cite:"Hail can be thrown out and fall from beneath the anvil." },
  { src:"IC", q:"If DALR = 9.8°C/km and ELR = 6.8°C/km, the (dry) atmosphere is:", opts:["Stable","Unstable","Indifferent"], ans:0, status:"VERIFIED", cite:"ELR < DALR → stable for unsaturated air." },
  { src:"IC", q:"If SALR = 5.5°C/km and ELR = 4.5°C/km, the (saturated) atmosphere is:", opts:["Unstable","Stable","Indifferent"], ans:1, status:"VERIFIED", cite:"ELR < SALR → absolutely stable." },
  { src:"IC", q:"When DALR > ELR > SALR, the atmosphere is:", opts:["Conditionally unstable","Latently stable","Potentially stable"], ans:0, status:"CORRECTED", cite:"SALR < ELR < DALR is 'conditional instability' (stable if dry, unstable if saturated). Corrected the term from 'conditionally stable'." },
  { src:"IC", q:"Unsaturated (dry) air is unstable when:", opts:["ELR = DALR","ELR > DALR","ELR < DALR"], ans:1, status:"VERIFIED", cite:"ELR steeper than the DALR → dry instability." },
  { src:"IC", q:"Saturated air is unstable when:", opts:["SALR = ELR","ELR > SALR","ELR < SALR"], ans:1, status:"VERIFIED", cite:"ELR steeper than SALR → saturated instability." },
  { src:"IC", q:"If ELR = SALR = DALR, the atmosphere is:", opts:["Stable","Unstable","Indifferent (neutral)"], ans:2, status:"VERIFIED", cite:"All rates equal → neutral/indifferent." },
  { src:"IC", q:"The DALR is:", opts:["The rate at which an unsaturated parcel cools as it ascends","The rate at which temperature falls with height in the environment","The rate at which a saturated ascending parcel cools"], ans:0, status:"VERIFIED", cite:"DALR = cooling rate of a rising unsaturated parcel (≈9.8°C/km)." },
  { src:"IC", q:"Surface temperature is 30°C. Using the DALR, the temperature at 2 km is:", opts:["18°C","10°C","42°C"], ans:1, status:"VERIFIED", cite:"30 − 2×10 = 10°C." },
  { src:"IC", q:"An isothermal atmosphere is:", opts:["Stable","Unstable","Neutral"], ans:0, status:"VERIFIED", cite:"Isothermal (and inversion) layers are very stable." },
  { src:"IC", q:"If the ELR is less than the SALR, the atmosphere is:", opts:["Absolutely unstable","Conditionally stable","Absolutely stable"], ans:2, status:"VERIFIED", cite:"ELR < SALR (and < DALR) → absolutely stable." },
  { src:"IC", q:"The DALR is approximately:", opts:["5°C/km","15°C/km","10°C/km"], ans:2, status:"VERIFIED", cite:"≈9.8 ≈ 10°C/km." },
  { src:"IC", q:"The SALR near mean sea level is about:", opts:["10°C/km","5°C/km","5°F/km"], ans:1, status:"VERIFIED", cite:"≈4–5°C/km at MSL (moisture-dependent)." },
  { src:"IC", q:"The SALR approaches the DALR:", opts:["At 0°C","At 15°F","At about −40°C"], ans:2, status:"VERIFIED", cite:"At very cold temperatures little latent heat is released, so SALR → DALR." },
  { src:"IC", q:"Dry air at 35°C forced to rise 1 km adiabatically attains:", opts:["29°C","25°C","45°C"], ans:1, status:"VERIFIED", cite:"35 − 10 = 25°C (DALR)." },
  { src:"IC", q:"An inversion in the atmosphere indicates:", opts:["Stability","Instability","Neutrality"], ans:0, status:"VERIFIED", cite:"An inversion is extremely stable." },
  { src:"IC", q:"An inversion is a ____ lapse rate:", opts:["Positive","Negative","Neutral"], ans:1, status:"VERIFIED", cite:"Temperature rising with height = negative lapse rate." },
  { src:"IC", q:"The ELR can be greater than the DALR:", opts:["True","False"], ans:0, status:"VERIFIED", cite:"A superadiabatic ELR occurs over strongly heated surfaces." },
  { src:"IC", q:"The process that largely determines the vertical temperature distribution of the atmosphere is:", opts:["Adiabatic","Isothermal","Isentropic"], ans:0, status:"VERIFIED", cite:"Adiabatic ascent/descent of air governs the vertical temperature profile." },
  { src:"IC", q:"A rise of temperature with height is called:", opts:["An inversion","A lapse","Normal"], ans:0, status:"VERIFIED", cite:"Inversion = temperature increasing with height." },
  { src:"IC", q:"Inversions are most common in:", opts:["Post-monsoon","Monsoon","Winter"], ans:2, status:"VERIFIED", cite:"Long clear winter nights favour radiation inversions." },
];
